regro/cf-scripts

- 01-make_graph.py
- requirements/run
> use requests rather than github3.py for 01 so we don't run out of

- 02-graph_upstream.py
fixes latest version when a prerelease is available
legacy PyPI uses the last release to populate 'info', whereas warehouse correctly uses the latest *stable* release
compare https://pypi.org/pypi/tornado/json (info.version = 4.5.3) with https://pypi.python.org/pypi/tornado/json (info.version = 5.0b1)
retrieving prerelease version produced an incorrect message about tornado being out of date in https://github.com/conda-forge/nbdime-feedstock/pull/11
The alternative is to parse, sort, and filter all of the versions in the legacy report yourself, I think.
PS autotick-bot is super cool!
> use warehouse pypi.org instead of legacy pypi.python.org

- conda_forge_tick/update_upstream_versions.py
Caused by https://github.com/conda-forge/esmf-feedstock/blob/master/recipe/meta.yaml#L9
> FIX: if no url in meta.yaml add to upstream bad

- 03-auto_tick.xsh
`bob` is causing issues again. In this case this is blocking progress for the bot backlog due to an outage over the weekend.
> write archived status into graph if PR fails with exact error message

- conda_forge_tick/update_upstream_versions.py
This blacklists version numbers containing ``a`` or ``b``.
Attn:
@justcalamari I guess I got to it first :)
@ocefpaf
@jakirkham
@ericdill
I'm putting up this PR so we can merge it if we want to and to continue the discussion. I guess I'd rather default to the safer approach (not bumping to dev versions) until we have the infrastructure to handle dev releases more formally (pushing to dev branches,/labels not updating everything to the dev versions when installing things, etc.) However, I would like to get input/consensus if possible, and am more than happy to follow the majority's opinion.
> blacklist a and b in version

- 03-auto_tick.xsh
re-render if the versions are the same.
This should cause the PRs for the bot to go faster
(after a bootstrap phase)
> write conda-smithy version for re-render into graph so we don't

- 03-auto_tick.xsh
This is a badge specific for conda-forge and in my experience it updates
immediately contrary to the anaconda badge which takes a day or to.
For illustration purposes here's the badge for pytest:
> Use conda-forge specific version badge in the PR template

- 03-auto_tick.xsh
- conda_forge_tick/migrators.xsh
The bot was running into a problem where it used `migrator.remote_branch()` before the `version` attribute was being set, causing an error. This should fix that.
Also I think it is useful to store the attributes of the node currently being migrated inside the migrator because other subclasses of Migrator might want to use other attributes of the node.
> Add attrs attribute to Migrator

- conda_forge_tick/auto_tick.xsh
- conda_forge_tick/git_utils.xsh
- conda_forge_tick/make_graph.py
- conda_forge_tick/migrators.xsh
- conda_forge_tick/update_upstream_versions.py
- conda_forge_tick/utils.py
- migrate_to_hash.py
- tests/test_migrators.py
- tests/test_path_lengths.py
> Migrator hash

- requirements/run
The bot failed on its most recent run, which I believe is due to pinning an old version of github3.py.
> Remove version pinning for github3.py

- conda_forge_tick/update_upstream_versions.py
- requirements/test
- tests/test_upstream_versions.py
Fixes #291.
This adds a simple, yet [not very widely applicable](https://github.com/search?q=org%3Aconda-forge+registry.npmjs.org&type=Code), source to, if the feedstock url is from `registry.npmjs.org`, make a call to `registry.npmjs.org` and return the `dist-tag` which is `latest` (the default). Like the PyPI source, it also will not return pre-release-y values in the name of the tag, as that also happens as the `dist-tags` feature is fairly buried. 
Not doing prereleases might be introducing an unwelcome opinion... thoughts? Both of the major upstream tools that use the namespace, `npm` and `yarn`, ignore them, so it seems reasonable enough.
> Add npm source

- conda_forge_tick/auto_tick.xsh
- conda_forge_tick/cli.xsh
This makes a separate deploy functionality which pushes up to github. The main benefit is that we can reduce our time pushing things to github for cf-graph. Note that this has a sister PR in [`circle_worker`](https://github.com/regro/circle_worker/pull/2) both need to go in at the same time.
> Sep deploy

- conda_forge_tick/make_graph.py
At 20 threads we hit the github abuse detection mechanism for about 50% of our PR updates.
Tone it down a bit.
> Reduce github request rate

- conda_forge_tick/migrators.xsh
This solves issues with `r-rcpp`.
> don't exclude bad upstreams from rebuilds

- conda_forge_tick/migrators.xsh
- tests/test_migrators.py
After PR https://github.com/conda-forge/r-base-feedstock/pull/61 was merged, the installation path for r-base is no longer different for Windows. As packages are rebuilt for the compiler migration, it would be nice if the license paths could also be updated so that the license files are properly packaged for Windows binaries.
This is just a start mainly to stimulate discussion. Long-term we'll want to update all GPL'd R packages, so it might be better to have this in a separate class definition. Suggestions and advice on how to implement this would be appreciated.
cc: @isuruf @bgruening 
xref: https://github.com/bgruening/conda_r_skeleton_helper/pull/24, https://github.com/conda-forge/r-base-feedstock/pull/61, #394, #395
> WIP: Fix file path to GPL license for R packages.

- conda_forge_tick/migrators.xsh
- tests/test_migrators.py
I created a regex that will update the file path for any R license file that is shipped with r-base. It can also handle any number of spaces between the line and the selector in case this was done manually and used something other than 2 spaces.
```
import re
regex_unix = re.compile('license_file: \'{{ environ\["PREFIX"\] }}/lib/R/share/licenses/(.+)\'\\s+# \[unix\]')
regex_win = re.compile('license_file: \'{{ environ\["PREFIX"\] }}\\\R\\\share\\\licenses\\\(.+)\'\\s+# \[win\]')
lines = ['license_file: \'{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3\'  # [unix]',
'license_file: \'{{ environ["PREFIX"] }}\R\share\licenses\GPL-3\'  # [win]',
'license_file: \'{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2\'  # [unix]',
'license_file: \'{{ environ["PREFIX"] }}\R\share\licenses\GPL-2\' …
```
> Use regex to update path for any R license.

- conda_forge_tick/auto_tick.xsh
- conda_forge_tick/make_graph.py
- conda_forge_tick/utils.py
- tests/test_utils.py
This PR modifies YAML `requirements` parsing to also parse those sections declared for `outputs`, mainly to fix the sort of problems seen in conda-forge/lal-feedstock#12 (the bot doesn't run when there are no top-level `requirements`).
> Enabled parsing of requirements in outputs

- conda_forge_tick/make_graph.py
> Just because a recipe is missing a URL doesn't make it automatically bad (eg for compiler migration)

- conda_forge_tick/auto_tick.xsh
- conda_forge_tick/make_graph.py
- conda_forge_tick/migrators.xsh
- conda_forge_tick/update_upstream_versions.py
- conda_forge_tick/utils.py
- requirements/run
- tests/test_migrators.py
- tests/test_utils.py
This is a basic migrator for doing the Arch rebuild.
* We are purposefully ignoring noarch here and initially operating within a bounded set of packages.
* In order to determine if a package is migrated we take a look inside the conda-forge-config.yml and check for certain values.  If those are present a package is skipped.  
* The current set of constraints yields about 120 packages to run this migrator on.
Additionally, this also adds a refactor to allow using `distributed` instead of `multiprocessing` for performing the initial graph building.
> Added migrator for aarch64 and ppc64le

- conda_forge_tick/auto_tick.xsh
- conda_forge_tick/migrators.xsh
The ``Rebuild`` migrator can be used to create objects without needing
to make new classes for each migration.
> simplify rebuild migrator system

- conda_forge_tick/auto_tick.xsh
Inspired by the OpenSSL migrator. I have roughly understood how this work but I did not understand how it determines which packages are already rebuild. Does it compare the pinnings of the package with the pinnings in `conda-forge-pinnings`? I.e. will this also work for future `libprotobuf` repins?
> Add libprotobuf migrator

- conda_forge_tick/auto_tick.xsh
Proj4 6.0.0 was a success IMO, only two left and they are already in PR\*. 
@scopatz and @mariusvniekerk I'm not sure if this is the right way to finish a migration, or even if we have to?
\* QGIS is quite complicated and may need patching to work with proj4 6 and postgis seems to have a conflict when installing gdal/proj4/postgresql that I'm investigating but it may take a while due to the high number of dependencies involved.
> end proj4 6.0.0 migration

- conda_forge_tick/auto_tick.xsh
Follow up on https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/221
Note to self: once this is over we may want to drop the pin on `pyqt` and let `conda-build 3` and `run_exports` that care of that one, and start a new migration to the `icu` with `run_exports`.
> migrate to qt 5.9.7

- conda_forge_tick/auto_tick.xsh
Note that this is an initial migrator, `glog` is not yet pinned. Does the code also work for this or does it need extra work for that?
Please don't merge until https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/226 has been merged and rolled out to the auto-tick bot.
> Add initial glog migrator

- conda_forge_tick/auto_tick.xsh
Follow up on the bot sub-group meeting today. We will keep `openssl` and `qt` open for a while. (Qt may be closed as soon as I fix the `qwtpolar` PR.)
> end zeromq and lz4 migration

- conda_forge_tick/auto_tick.xsh
As discussed in the previous bot-meeting the `qt` migration is "done," the remaining packages are either abandoned or not central to the `conda-forge` and will be updated when the maintainers there re-render.
This PR also adds a new migration to `proj4 6.1.0`. (Ping @snowman2.)
> remove qt migrations and add proj4 6.1.0

- conda_forge_tick/auto_tick.xsh
Updating pin here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/231
Fixes https://github.com/regro/cf-scripts/issues/505
> Add migrator for boost-cpp 1.70.0 pin

- conda_forge_tick/auto_tick.xsh
As we discussed in our meeting yesterday let's pause the `boost` migration, let the `boos-cpp` finish, and then we can re-activate this one.
> pause boost migration

- License
This changes the current license to add the conda-forge standard BSD, with the copyright holder as NumFOCUS
> add conda-forge license

- conda_forge_tick/auto_tick.xsh
Depends on https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/238
> Add migrator for libevent=2.1.10

- conda_forge_tick/auto_tick.xsh
There is only 1 open PR to tex-live and that feedstock is broken in a while. So this migration was a successful. Also ending the 100% completed libevent.
> end pixman migration

- conda_forge_tick/auto_tick.xsh
As discussed in today's meeting.
Note that the `boost-cpp` will be covered by the `boost` migration we are re-starting here. All others reached a dead end like `shogun`, `sage`, or `audi`, which require more work to get the feedstocks building again.
> end blas2, libprotobuf, boos-cpp and re-enable-boost

- conda_forge_tick/auto_tick.xsh
`zstd` actually complete :tada: 
All others either issued all the possible PRs or have shogun/shogun-cpp awaiting parents.
> end boost pyqt zstd hdf5 libprotobuf migrations

- conda_forge_tick/auto_tick.xsh
`geos` migration is done and we need a new one for `cfitsio` due to the recent ABI breakage.
> migrate cfitsio and end geos

- conda_forge_tick/auto_tick.xsh
- conda_forge_tick/migrators.xsh
This will migrate r-packages to 3.6 pinnings only and will only build on azure.
@isuruf I'm not sure this is correct :( This will probably not only run for r-packages now, isn't it?
> add r-base 3.6 migration and move all the build to azure

- conda_forge_tick/auto_tick.xsh
`cfitsio` completed and the others issued all the PRs, no `0 awaiting parent`.
> end gsl, cfitsio, pango, and readline migrations

- conda_forge_tick/auto_tick.xsh
Thanks to the awesome work by @isuruf and @mingwandroid in https://github.com/conda-forge/qt-feedstock/pull/110, with the help of @msarahan and the sage math project, we can now move to a modern `qt`!
> migrate to qt 5.12

- conda_forge_tick/auto_tick.xsh
We must migrate `libgdal` first and then un-comment the `gdal` migration.
xref.: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/263
> migrato to gdal 3

- conda_forge_tick/auto_tick.xsh
The ABI compatibility in `proj4` is improving. Maybe we can change to `x.x` in the next release. See https://abi-laboratory.pro/?view=timeline&l=proj
> migrate to proj4 6.1.1

- conda_forge_tick/auto_tick.xsh
- conda_forge_tick/migrators.xsh
This PR has code to migrate to gfortran 7 for osx. I've made an associated PR on the global pinning files [here](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/252).
pinging 
@scopatz 
@CJ-Wright 
@isuruf 
for viz and guidance
> ENH migrate to gfortran 7 for osx

- scripts/migrate_to_lzjson.py
This needs to be checked over, since I'd like to stop the
bot when we go to run this migration of the graph itself.
Overall this should reduce git thrashing a lot, 
since we will only touch the files we need to
and it will make the graph.json smaller.
Additionally this will make the state of individual
nodes much easier to read since they can be read as
json themselves.
> lazy json all the way to the nodes

- conda_forge_tick/auto_tick.xsh
This PR ends the gfortran 7 for OSX migration. We have issued all of the PRs we possibly can. The remaining ~10-13 feedstocks that need migrating have complicated build issues or actual package test failures that need the attention of those maintainers.
> MNT end gfortran 7 for OSX migration

- conda_forge_tick/auto_tick.xsh
We have more code related to the `openssl` migration here but I guess we should keep it. Maybe we can make it cleaner in a future re-factor.
> end openssl migration

- conda_forge_tick/auto_tick.xsh
This way we can restart bad migrations via the yaml
> Use obj_version number from yaml

- conda_forge_tick/update_upstream_versions.py
Dear cf-script maintainers and @conda-forge/r (@bgruening @jdblischak @cbrueffer @dpryan79 @daler @johanneskoester),
Lots of manual R feedstocks version updates were done in the past due to the bot missing / not seeing available updates on CRAN. Even after lots of updates, still around 3-10% of the R package get outdated after some month.
One of the reasons seems to be that libraries.io does not see all cran packages and version, e.g. compare:
* https://cran.r-project.org/web/packages/xfun/index.html (version 0.10)
* https://libraries.io/cran/xfun (version 0.8)
This PR changes the CRAN() versions source to directly use the cran index, instead of the libraries.io indirection. This should be much more current, accurate and faster, as a local index is used instead of  one request per …
> Get CRAN upstream versions directly from CRAN instead of librariesIO

- conda_forge_tick/update_upstream_versions.py
context: https://github.com/regro/cf-scripts/pull/630
The second commit fixes the previous seen issues with dask, by not keeping the cran index inside the cran class, which get serialized for every dask job and causes memeory issues already on job submission.
This time fully locally tested without any additonal changes :) 
@CJ-Wright Can we give this another try?
Thanks!
> Get cran upstream versions directly from cran v2

- conda_forge_tick/auto_tick.xsh
This way we don't end up rebuilding things for a build req.
@regro/auto-tick
> use host if host, use build if not host

- conda_forge_tick/status_report.py
It's annoying when the migrator listing ordering changes. :smiley:
> sort migrators in status report

- conda_forge_tick/auto_tick.xsh
- conda_forge_tick/migrators.xsh
- tests/test_migrators.py
This PR adds the migration for `matplotlib` to `matplotlib-base`. Closes #705
> ENH matplotlib-base migration

- conda_forge_tick/auto_tick.xsh
It appears that we are seeing a lot of failures on the matplotlib-base migration do to a non-working TK backend in the CI environment. I propose that we stop the migration and then restart it later after we have added `MPLBACKEND='Agg'` to the environment in CI.
@CJ-Wright for viz
> ENH stop matplotlib-base migration for a bit

- conda_forge_tick/cli.xsh
This PR fixes #712 by adding a dummy argument that accepts input, but does nothing with it.
> Add dummy argument to deploy() function

- conda_forge_tick/utils.py
@CJ-Wright this is a minor change, and isort run, that fixes some of the deprecation warnings when running the conda-forge by-numbers notebook.
> fix deprecation

- conda_forge_tick/update_upstream_versions.py
Issue:
- Version number from the `spacy-models` repository contains characters that are not a part of the version. Because of this, the updates do not get picked by the bot.
Changes:
- Perform a regex match to extract version number from the `ver` string such that everything starting at the first digit gets picked up in the pattern.
All of the expected version patterns expected by [`VersionOrder`](https://github.com/conda/conda/blob/da8b5a812bb17d83012f3a0bb63ef7158f1e846e/conda/models/version.py#L47) start with a numeric digit as well.
This fixes #707.
> Extract version starting at the first digit

- conda_forge_tick/auto_tick.xsh
Currently we do 30 and it takes 20 mins so 60 should put us at 40mins, which should leave some breathing room for the other parts to be within the 1 hour time limit.
> increase number of version bump PRsto deal with backlog

- conda_forge_tick/migrators/arch.py
I got a request for the python version of this by email. so this is at least a start.
> Add occt to the arch migrator

- conda_forge_tick/migrators/arch.py
Closes #729 
@regro/auto-tick for CR
> DOC make sure aarch migrator PR body uses the parent text too

- conda_forge_tick/auto_tick.py
Love the new graph!
This adds the PR URL (if available) to each node that has one, which becomes clickable when the SVG is not shown as an `img` tag. While this sets a bunch of empty strings, they just get removed. I suppose a fallback value could be just to the feedstock URL itself (wasn't sure where that would come from in hte data). This does make the generated SVG a fair amount chunkier, but a good amount richer.
I couldn't tell how to test the generated SVG locally, but have used this feature a fair amount in the past.
> Add URL to status graph nodes

- docs/github_actions_infrastructure.rst
I was pretty surprised by this line in the docs, implying that if e.g. the Mac build fails but Linux passes then it'll still get merged – but that's [not what the code does](https://github.com/regro/cf-autotick-bot-action/blob/master/conda_forge_tick_action/automerge.py#L73).
> fix doc on merge criteria

- conda_forge_tick/auto_tick.py
This PR turns off the pip check migrator.
cc @xhochy @isuruf @jakirkham @mariusvniekerk @CJ-Wright @regro/auto-tick
> DEP turn off pip check migrator

- conda_forge_tick/auto_tick.py
- conda_forge_tick/migrators/version.py
- tests/test_migrators.py
- tests/test_version_migrator.py
- tests/test_yaml/version_sha1.yaml
- tests/test_yaml/version_sha1_correct.yaml
A recipe used a sha1 hash stored in a jinja2 variable called sha256. 🤦‍♂ 
We can now handle that.
Closes #839
> TST add test for alternate hashes with weird jinja2 names

- conda_forge_tick/auto_tick.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/version.py
I checked the rest of the migrators and they all rerender anyways so I think we are good here. I've also changed the rerender to opt-out and lowered the PR numbers a bit to start.
> ENH always rerender for versions

- conda_forge_tick/auto_tick.py
I made a mistake when testing #853 which prevents it from properly working (it requires **both** the output and the top level recipe name to be requirement instead of either).
Assuming I've tested it properly this time, this PR fixes the issue.
Before:
```
aarch64 and ppc64le addition graph size: 644
grpc127 graph size: 1
python38 graph size: 2025
root620000 graph size: 1
boost172 graph size: 165
matplotlib-to-matplotlib-base graph size: 228
```
After:
```
aarch64 and ppc64le addition graph size: 644
grpc127 graph size: 1
python38 graph size: 2025
root620000 graph size: 7  # <- 6 more packages found
boost172 graph size: 165
matplotlib-to-matplotlib-base graph size: 228
```
Finishes fixing #852
cc @beckermr @duncanmmacleod
> Better match package output names when doing migrations (#852)

- conda_forge_tick/url_transforms.py
- tests/test_url_transforms.py
This fixes some of the issues we have seen with `{{version}}` as opposed to `{{ version }}` in urls.
To do:
> ENH do a little extra jinja2 munging for urls

- conda_forge_tick/auto_tick.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/migration_yaml.py
- tests/test_migration_yaml_migration.py
- tests/test_yaml/boost.yaml
- tests/test_yaml/boost_out.yaml
- tests/test_yaml/conda_build_config.yaml
- tests/test_yaml/krb.yaml
- tests/test_yaml/krb_out.yaml
- tests/test_yaml/pypy.yaml
- tests/test_yaml/pypy_out.yaml
Closes #912
CC: @mariusvniekerk @beckermr
This introduces a function for merging the conda build config and a migration.
The function preserves selectors by not loading the yamls for either.
This causes the function to only implement a subset of the variant algebra.
However, this should cover most use cases that we currently have, including
the case where `zip_keys` is used and is completely represented in the migraiton.
The API is designed to be flexable so that future implementations can cover more
of the variant algebra.
Overall this makes the migration UX better as it requires fewer human made PRs, with a resonable expection that the bot issued PRs will be correct.
To the best of my knowledge this doesn't disrupt any of our existing UX.
> add function for merging migrations into conda build config and add pinning to all migrations

- conda_forge_tick/auto_tick.py
This PR adds a random hash to our branch names. This way if we miss some PR json, the bot will merrily issue a new PR.
> ENH use random branch names so that we can easily reissue missed PRs

- conda_forge_tick/auto_tick.py
This PR sets a max PR limit for migrators that is up to 50 PRs. Migrators will still not start out with this many, but they can bump up to this many if they want.
> ENH allow up to 50 PRs

- conda_forge_tick/auto_tick.py
- conda_forge_tick/cli.xsh
- conda_forge_tick/migrators/migration_yaml.py
- tests/test_patch_dict.py
This PR has three things
1. We now check that the graph can be loaded before we deploy it. If it cannot, we deploy to a branch for debugging and stop the bot.
2. I added the ability to pause migrations.
3. I added the ability to patch the conda-forge.yml from the migrator via a syntax like
```yaml
conda_forge_yml_patches:
provider.linux_ppc64le: azure
```
This will allow us to set this only for the R migration.
> ENH more fixes for R

- conda_forge_tick/migrators/license.py
cc @CJ-Wright 
xref: https://github.com/conda-forge/r-genabel.data-feedstock/pull/5
> ENH allow archived packages for generating recipe edits for R licenses

- conda_forge_tick/mamba_solver.py
- tests/test_mamba_solvable.py
This PR adds in a `.*` for pins in the requirement strings before feeding them to mamba.
cc @CJ-Wright @wolfv 
closes #987
> ENH add in `.*` for mamba solvability test

- conda_forge_tick/mamba_solver.py
- conda_forge_tick/migrators/disabled/legacy.py
This PR fixes an error where we don't account for outputs that would be built when checking if a recipe's envs can be solved.
> ENH make sure to exclude things that would be built in mamba check

- conda_forge_tick/mamba_solver.py
I think these if statements are why some migrations appear to not push.
> PROD warn when solvability check fails due to files not being found

- conda_forge_tick/all_feedstocks.py
- conda_forge_tick/auto_tick.py
- conda_forge_tick/make_graph.py
This PR pulls a list of non-archived feedstocks from the admin-migrations repo. It then uses that list and correctly sets archived on each feedstock.
> ENH compute archived from admin-migrations

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
This adds a GitHub Action as a CI service to check for the pre-commit hooks. It should help when reviewing style (black) and other hooks present in the `.pre-commit-config.yaml` file. Note that, at the moment, there are massive failures with the `mypy` and `check-yaml` hooks. Not sure they are real failures though.
PS: I can send a new commit fixing the style but I wanted to ask if that is OK first b/c it will be a massive commit.
> run pre-commit as a GHA

- conda_forge_tick/cli.xsh
- conda_forge_tick/make_graph.py
- conda_forge_tick/new_update_versions.py
- conda_forge_tick/update_sources.py
As mentioned by @CJ-Wright and @beckermr this new PR aims some alterations on the original version of
`update_upstream_versions` code to generate a JSON file containing the required new versions outside the `graph` structure. Is also, now communicates with the others functions of that module.
Now, I've created a separate module for the upstream sources in the library. A test in a separate repo using Circle CI, was made with an good result (The code runs) [Circle Ci](https://app.circleci.com/pipelines/github/viniciusdc/ts-graph/46/workflows/cf6da52d-df5d-485d-9aaf-6c142ce10962/jobs/51).
There are still some missing alterations as: 
1. Some sources still do some  alterations directly to the `graph` structure;
2. As cited by CJ, I still need to implement it on the `cli.ssh` file to be read …
> New main update version and sources module.

- conda_forge_tick/new_update_versions.py
Due to the expensive time consuming usage of the actual `update upstream version` I've inserted the `pool` mode, as also, implements the function to choose the mode accordingly to the current `CONDA_FORGE_TICK_DEBUG` status.
See as references the issue [#842 ] and PR's [#1048 , #1043 ].
> Attempt to Update upstream version process pool 

- conda_forge_tick/new_update_versions.py
Reduced the number of `workers` from 20 to 10. There were some memory problems with [Circle Ci](https://app.circleci.com/pipelines/github/regro/circle_worker/11168/workflows/88d4f002-22a5-4dbd-8848-e26a2c019099/jobs/27484).
> Changes to `max_workers`

- conda_forge_tick/new_update_versions.py
@beckermr @viniciusdc
I think this fixes the issues that a few maintainers have experienced with missing bot updates
closes https://github.com/regro/cf-scripts/issues/1072 (I think)
> run upstream update if bad is from upstream update

- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators/version.py
Note that this will need a PR in webservices to make the most of this and some advertising.
The hope here is that ABI migration PRs are more likely to break if there are any changes that need to be applied to the feedstock. Enabling migration automerge will greatly speed up uptake of pins, similar to the R 4.0 migration.
@beckermr @isuruf @scopatz
> Allow automerge for version or migrations only

- conda_forge_tick/auto_tick.py
We are currently letting these errors cause the migration to not be marked as done. This is stalling python38 where ppl added the migrational yml by hand.
> PROD catch commit errors

- conda_forge_tick/auto_tick.py
- conda_forge_tick/make_graph.py
- conda_forge_tick/profiler.py
- conda_forge_tick/update_prs.py
This should enable us to inspect more functions with more freedom.
> NEW profiler decorator

- conda_forge_tick/make_graph.py
Reverts regro/cf-scripts#1099
@CJ-Wright This has a bug. Killed the bot.
> Revert "only new versions"

- conda_forge_tick/utils.py
This has been killing the bot. 
cc @scopatz @isuruf @CJ-Wright
> BUG catch system exit call in conda-build

- conda_forge_tick/auto_tick.py
- conda_forge_tick/make_graph.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/utils.py
This PR enables migrations of compilers via two new features in the migration yaml.
1. You can now add an `include_by_build_only` key which cases the bot to only look at build sections when figuring out if it should include a node in the graph. The bot still uses host+run+test for making edges.
2. You can now add an `override_cbc_keys` key which is a list of things that should appear in host/build for a package to be included in the migration. This will allow folks to list things like `fortran_compiler_stub` when migrating against the `fortran_compiler_version` key, for example.
This will also help the CUDA 11 migration if I am not mistaken. 
xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/794
xref: https://github.com/conda-forge/conda-forge.github.io/issues/1160
> ENH enable mirgations of build keys w/ compilers

- conda_forge_tick/auto_tick.py
Since we want to always check for solvability when doing migrations, actually do so.
> Check for solvable more frequently

- conda_forge_tick/migrators/migration_yaml.py
This PR makes sure to always include the pinnings feedstock in the included nodes for rebuilds. The bot is not issuing PRs to close migrations, and I think this is why.
> BUG make sure to always add pinnings in the included nodes

- conda_forge_tick/auto_tick.py
We should skip the top-level and cycles for solvable checks.
> ENH skip cycles for solvable checks

- conda_forge_tick/auto_tick.py
- conda_forge_tick/mamba_solver.py
- tests/test_mamba_solvable.py
This will ensure that we don't issue a PR when not all python versions
have a valid run environment
> Add pinning propogation to the mamba checks.

- conda_forge_tick/mamba_solver.py
- mypy.ini
- tests/test_mamba_solvable.py
This adds in support for injecting virtual packages into the solve space allowing us to solve for things like `__glibc`, `__cuda` etc.
Additionally this opens up a future prospect to instead of ignoring self outputs , we can just make a fake channel that contains them and have the solve work as normal.
> Improve mamba solver pins

- conda_forge_tick/status_report.py
Things get marked as bad when they error and then they are filtered, so we have to catch their status this way too.
> BUG make sure to report bot error and not awaiting parents

- conda_forge_tick/mamba_solver.py
- tests/test_mamba_solvable.py
This should fix the jpeg errors and avoid us having to maintain a list of openssl-like version schemes.
> DEP remove explicit pinning stuff since not needed

- conda_forge_tick/migrators/license.py
This PR will swallow download errors in the license mini-migrator.
cc @CJ-Wright
> ENH swallow errors in license migrator

- conda_forge_tick/auto_tick.py
This will propagate the errors to the status page so people can look at them.
> REF don't swallow rerendering errors

- conda_forge_tick/mamba_solver.py
- tests/test_mamba_solvable.py
Sometimes libcfgraph has the run export as a single string. This catches that.
> BUG fix string bug in mamba solver

- conda_forge_tick/migrators/cross_compile.py
Fixes https://github.com/regro/cf-scripts/issues/1222
> Don't add libtool to libtool

- conda_forge_tick/status_report.py
This PR computes recently closed migrations. It compares the old status json to the new one and records anything not present. It then adds in stuff already closed in a two week window. Due to the way it works, it will be several weeks before the status page will get populated with these.
> ENH compute recently closed migrations

- conda_forge_tick/utils.py
It turns out when we use ChainDB for requirement aggregation, it makes a mess when aggregating `None` with lists. We get a `None` for a requirements section in some cases like this
```
requirements:
build:
- blah   # [not win]
```
When the selectors are evaluated, it leaves
```
requirements:
build:
```
which results in a `None` for `build`. 
This PR fixes this issue by setting `None`s to empty lists if we find them.
> BUG fix requirement aggregation for Nones

- conda_forge_tick/utils.py
- tests/test_utils.py
This should fix #1269. Without this fix, setdefault does not work in the context manager and that is causing us to loose PRs when the initial list is empty, i.e. when a feedstock is brandnew.
> BUG only purge the data in memory when leaving the context manager

- conda_forge_tick/audit.py
- conda_forge_tick/contexts.py
- conda_forge_tick/utils.py
- tests/test_utils.py
This adds a property to LazyJson that always has the data. I am using it to make a copy of the data in the context classes.
> BUG enable proper copy for context

- .pre-commit-config.yaml
- conda_forge_tick/audit.py
- conda_forge_tick/auto_tick.py
- conda_forge_tick/feedstock_parser.py
- conda_forge_tick/git_utils.py
- conda_forge_tick/make_graph.py
- conda_forge_tick/migrators/arch.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/utils.py
- tests/test_feedstock_parser.py
- tests/test_migration_yaml_migration.py
- tests/test_migrators.py
- tests/test_security.py
- tests/test_utils.py
This is a follow on to #1122 by @CJ-Wright. I have copied bits of code from there and made some slight changes to how it works. We now keep all outputs in the lut and (at least attempt) to always put requirements through it to find feedstocks in the graph.
> ENH set outputs again

- conda_forge_tick/migrators/migration_yaml.py
@beckermr I think this fixes the migrate arrow-cpp pr into arrow-cpp branches.
> exclude the pkgs being migrated themselves

- conda_forge_tick/auto_tick.py
This is causing some migrations that come next to be skipped even though they may rerender just fine.
> ENH do not set bad for rerender errors

- conda_forge_tick/pypi_name_mapping.py
This should prevent the situation where we might prefer archived feedstocks
> Don't bother generating pypi mappings for archived feedstocks

- conda_forge_tick/auto_tick.py
cc @isuruf 
I think a recent change in the pinnings file triggered this edge case. It turns out the bot also does not care about None or undefined.
> BUG make sure to remove any blank versions

- conda_forge_tick/migrators/migration_yaml.py
> Include test requirements only if we are building that node

- conda_forge_tick/auto_tick.py
cc @CJ-Wright This should let the bot always close migrations.
> HACK never check solvable for pinning PRs

- conda_forge_tick/update_sources.py
- tests/test_url_exists.py
Here is a version of #1348 that we can merge right away. I have put in a specific list of things that use the new `curl`-based test. everything else uses the old `wget`-based one. This should satisfy all parties.
@CJ-Wright want to do the honors?
cc @isuruf 
closes #1348
> REF use an allow list for curl

- conda_forge_tick/migrators/cos7.py
This PR makes sure the migrator for cos7 doesn't muck with feedstocks using the new os_version stuff.
> ENH make sure feedstock is not using new OS version stuff

- tests/test_version_migrator.py
- tests/test_yaml/version_cupy.yaml
- tests/test_yaml/version_cupy_correct.yaml
This PR adds a (passing) test to make sure the bot can migrate the cupy feedstock. 
As this test works, any errors in cupy versions not appearing are due to solver or rerendering issues. 
cc @jakirkham @leofang
> TST add test for cupy

- conda_forge_tick/auto_tick.py
- conda_forge_tick/git_utils.py
This PR has the bot ship PRs for versions that hash properly but cannot be rerendered locally. Hopefully, this will mean we let more maintainers know about possible version bumps and they can fix the rerendering errors.
closes #1370
> ENH ship rerender errors for version PRs anyways

- conda_forge_tick/utils.py
This should swallow conda build exits and raise errors.
> REF catch system exit from conda build

- conda_forge_tick/update_sources.py
For example, gnuradio tagged the master branch with 3.10.0.0git as a development version after a 3.9.0.0 release, but the bot picked up this tag as a new release. (No PR was issued because, predictably, there was not a corresponding release tarball.) Even now with a 3.9.1.0 release, the bot is stuck on 3.10.0.0git because it is higher. To fix that particular issue even after/if this commit is accepted, I'm guessing the graph will need to be fixed [here](https://github.com/regro/cf-graph-countyfair/blob/455feb52dd97877205d0c4c056c7004310de3869/node_attrs/gnuradio.json#L5695).
I don't think anyone would use "git" in a version string and not have it mean a development version, so it seems like a safe change to me.
> Add "git" to list of dev_vers strings that cause version to be ignored.

- conda_forge_tick/migrators/cross_compile.py
- tests/test_cross_compile.py
As requested by @isuruf in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1495#issuecomment-840023155
> Add R host dependencies to build for cross-compiling

- conda_forge_tick/auto_tick.py
- conda_forge_tick/migrators/migration_yaml.py
This PR changes the ordering of yaml rebuilds to run PRs without errors first. This should help us cope with time limits when lots of things are not solvable.
> REF run non-errored PRs first

- conda_forge_tick/update_sources.py
- conda_forge_tick/update_upstream_versions.py
- conda_forge_tick/utils.py
This PR makes sure we try the jinja2 edit for raw versions.
> ENH use jinja2 version if we can

- conda_forge_tick/make_graph.py
This PR skips updating versions for nodes that have changed.
> BUG skip updating versions for changed nodes

- conda_forge_tick/update_sources.py
In order to properly support packages that exist ONLY as prerelease (eg portions of opentelemetry) we need to allow pypi to return that version
> Support pre-release versions from PyPI

- conda_forge_tick/migrators/cross_compile.py
- tests/test_cross_compile.py
The `GuardTestingMigrator` did not have a default for `CONDA_BUILD_CROSS_COMPILATION`,
which probably caused builds failing with `unbound variable` messages.
On my machine the tests in `test_cross_compile.py` pass. (All tests pass except for some URLs that don't exist.)
This hopefully fixes #1424.
> Add default for CONDA_BUILD_CROSS_COMPILATION

- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/migration_yaml.py
This PR will allows us to ignore deps for certain nodes in certain migrations. It is designed to handle pypy37-windows and matplotlib. 
closes #1434
> ENH support ignoring deps per node

- conda_forge_tick/pypi_name_mapping_static.yaml
See naming difference here: https://pytorch.org/get-started/locally/
> Add pytorch pypi_name_mapping_static.yaml

- conda_forge_tick/auto_tick.py
- conda_forge_tick/migrators/version.py
This PR adds a topological sort to the version graph to help correlated version PRs.
closes #1445
> ENH add topological sort

- conda_forge_tick/auto_tick.py
This PR proposes simpler solver check logic. We have settled on a policy (through our actions and time) of
1. All migrators have solver checks on by default except versions.
2. We allow migrators to turn off their solver checks.
3. We allow people to opt-in to all solver checks.
> REF simplify solver check logic

- conda_forge_tick/auto_tick.py
- tests/test_yaml/version_multisrclistnoup.yaml
- tests/test_yaml/version_multisrclistnoup_correct.yaml
This PR closes some custom migrators we no longer need.
> DEP disable migrators we no longer need

- conda_forge_tick/migrators/core.py
This PR would close migrations issued at 14 days after all PRs are issued instead of our current 30. Lots of stuff is lingering and 30 feels too long now. I am also hoping this will help with the bot's memory footprint and overall performance, but that seems much less likely.
> PROD close migrations with all PRs issued after 14 days instead of 30

- conda_forge_tick/recipe_parser/_parser.py
- tests/test_recipe_parser.py
This PR fixes the issue @leofang noticed in #1499. 
The approach I have taken is to fix only this edge case when
1. A selector was munged
2. The key-value pair is split across two lines
3. the yaml parser used the `?` format for keys. See Wikipedia and yeah this is weird!
Hopefully, the code is specific enough to not cause other issues later.
Closes #1499
> BUG make sure split keys are handled properly in recipe parser

- tests/test_audit.py
- tests/test_mamba_solvable.py
It appears the greyskull API has changed. As we are not doing those audits, I added a skip decorator to the test.
> TST fix tests

- conda_forge_tick/recipe_parser/_parser.py
Fixing a spelling error in this stuff.
> BUG misnamed function for split key-value pairs

- .github/workflows/tests.yml
- conda_forge_tick/audit.py
- conda_forge_tick/migrators/version.py
- conda_forge_tick/recipe_parser/_parser.py
- conda_forge_tick/update_deps.py
- tests/test_audit.py
- tests/test_cross_compile.py
- tests/test_migrators.py
- tests/test_update_deps.py
This PR has grayskull+depfinder recipe updates. It works as follows.
The bot.inspection key in the conda-forge.yml can have one of six possible values:
- hint: generate hints using source code (backwards compatible)
- hint-all: generate hints using all methods
- hint-source: generate hints using only source code
- hint-grayskull: generate hints using only grayskull
- update-all: update recipe using all methods
- update-source: update recipe using only source code
- update-grayskull: update recipe using only grayskull
The default is hint-source.
Recipe updates have the following restrictions (safety first!)
- the recipe can only have a single output
- recipe updates are only applied in the host and run sections
- dependencies are added but never removed
- if a package name matches an …
> ENH grayskull+depfinder updates

- .github/workflows/tests.yml
- conda_forge_tick/audit.py
- conda_forge_tick/auto_tick.py
- conda_forge_tick/git_utils.py
- conda_forge_tick/migrators/arch.py
- conda_forge_tick/migrators/conda_forge_yaml_cleanup.py
- conda_forge_tick/migrators/cos7.py
- conda_forge_tick/migrators/cross_compile.py
- conda_forge_tick/migrators/disabled/legacy.py
- conda_forge_tick/migrators/duplicate_lines.py
- conda_forge_tick/migrators/extra_jinj2a_keys_cleanup.py
- conda_forge_tick/migrators/jinja2_vars_cleanup.py
- conda_forge_tick/migrators/license.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators/mpi_pin_run_as_build.py
- conda_forge_tick/migrators/pip_check.py
- conda_forge_tick/migrators/pip_wheel_dep.py
- conda_forge_tick/migrators/use_pip.py
- conda_forge_tick/migrators/version.py
- conda_forge_tick/utils.py
- conda_forge_tick/xonsh_utils.py
- conda_forge_tick/xonsh_utils.pyi
- tests/test_migration_yaml_migration.py
- tests/test_migrators.py
- tests/test_security.py
I keep seeing odd failures in the bot where it looks like it is not in the right path when changing working directories. I cannot tell how this is happening. See this issue + log: https://github.com/regro/autotick-bot/issues/479
I am trying swapping out the xonsh dir change for a pure python, mostly as a stab in the dark.
> REF use pushd instead of xonsh

- conda_forge_tick/migrators/arch.py
As noted in the [documention](https://conda-forge.org/docs/maintainer/conda_forge_yml.html#test-on-native-only) (added in https://github.com/conda-forge/conda-forge.github.io/commit/2275ee0eec00353157e2e6e4887586ce700aaa3e), the old form of this is now deprecated. The new testing syntax was added (and old deprecated) in https://github.com/conda-forge/conda-smithy/commit/7d0bfffe0c902fbe3b694ac02330027920669ad2.
This PR updates the autotick migrator to use this new syntax.
I.. do not know how to exhaustively test this. The instructions in the README seem a little out-of-date, I can run `pytest` on the `tests/` directory and get roughly the same number of failures as the main branch (+/- apparently flaky tests), but `tests/test_migrators.py` test file only seems to check the recipe yaml, …
> Use newer 'test:' syntax when migrating osx_arm64

- conda_forge_tick/update_sources.py
- conda_forge_tick/update_upstream_versions.py
- tests/test_upstream_versions.py
This would save some manual work for several feedstocks:
```python
>>> from conda_forge_tick import update_sources
>>> nv = update_sources.NVIDIA()
>>> nv.next_ver_func('cuda', '11.6.1')
'11.6.2'
>>> nv.next_ver_func('cuda', '11.6.2')
'11.7.0'
>>> nv.next_ver_func('cutensor', '1.4.0')
'1.5.0.3'
>>> nv.next_ver_func('cuquantum', '22.03.0')
'22.05.0.41'
```
A few feedstocks ~~(ex: cuSPARSELt)~~ would require NVIDIA to change the binary archive (which is an ongoing work) but those should not be a blocker for this PR.
Note: I feel this might require some minor changes in the recipes (ex: include the build version in the version string), so let's also discuss necessary changes in this PR.
cc: @jakirkham @kkraus14 @kmittman @jaimergp @beckermr
> Add NVIDIA package source

- conda_forge_tick/pypi_name_mapping_static.yaml
The Seaborn package has some oddities going on with its package names (#1513), which this static override fixes.
> Add Seaborn static mapping

- conda_forge_tick/auto_tick.py
This PR adds a migrator to rename build to python-build in recipes.
> ENH add rename from build to python-build

- conda_forge_tick/mamba_solver.py
This fixes the
```
Error: not solvable [...] Encountered problems while solving:\n - nothing provides __win needed by [...]
```
seen in the Py 3.11 migration.
> Add __win to faked virtual packages

- conda_forge_tick/auto_tick.py
Since this is now `main`, update the docstring accordingly.
https://github.com/regro/cf-scripts/blob/c30554fcb230f3f0a92c925dd118b2c9a6ff0bda/conda_forge_tick/auto_tick.py#L163
> Update `base_branch` docstring default

- conda_forge_tick/pypi_name_mapping.py
i'd like to get this info in json too. it's programmatically used in depfinder in its yaml format which is substantially slower to load than json (~30x). i _think_ this should just transparently work. this will change the output format of `mappings/pypi/import_name_priority_mapping.yaml` because json.dump doesn't know what to do with `list_reverseiterator`
```
TypeError: Object of type list_reverseiterator is not JSON serializable
```
Is updating the output of import_name_priority_mapping.yaml to look like the following snippet instead going to be a problem for anything else?
```diff
-  ranked_conda_names: !!python/object/apply:builtins.reversed
-    args:
-    - - pycryptodome
-      - pycrypto
-    state: 1
+  ranked_conda_names:
+  - pycrypto
+  - pycryptodome
```
> Add json map to mapping output

- conda_forge_tick/auto_tick.py
This PR adds a timeout to the solver checks after 90 days. This will get some of our migrations moving.
> ENH timeout solver checks after 90 days

- conda_forge_tick/pypi_name_mapping_static.yaml
Currently the Grayskull mapping favors ruamel_yaml over ruamel.yaml.
This requires #1642 in order to take effect.
> Add ruamel.yaml to static mapping

- conda_forge_tick/pypi_name_mapping_static.yaml
There is no such PyPI package.
My guess is that this was probably meant to be [opencv-python](https://pypi.org/project/opencv-python/), which is already in the mapping. Or was this deliberate? (ping: @mariusvniekerk)
> Remove spurious python-opencv static mapping

- conda_forge_tick/pypi_name_mapping.py
This is somewhat of a follow-up to #1638. Thanks so much @beckermr for the quick merge on that!
Tiny values are evidently due to rounding error. (There is a large gap in orders of magnitude between positive values and these tiny values.)
This should stabilize `ranked_hubs_authorities.json`.
> Clip tiny hub/authority scores to zero

- .pre-commit-config.yaml
- conda_forge_tick/pypi_name_mapping.py
This PR consists of a single commit 98e51a2 on top of #1640.
Since the input mappings are indexed by `import_name`, it sometimes happens that there are multiple `Mapping` objects with the same `pypi_name`. Currently we pick an arbitrary one, but this PR makes it explicit that we should favor one from the static mapping if it's defined. Otherwise emit a warning.
> Prefer statically defined matches in PyPI Grayskull mapping

- conda_forge_tick/pypi_name_mapping.py
This PR consists of a single commit 2406b43 on top of #1640.
Due to concatenating the graph mapping and the static mapping, there might be two candidates with the same `conda_name` but different PyPI names. Currently we pick an arbitrary one (whichever one appears last in the list). This PR changes this behavior to favor matches defined in the static mapping, and to otherwise emit a warning.
> Prefer statically defined matches in PyPI import mapping

- conda_forge_tick/pypi_name_mapping.py
- conda_forge_tick/pypi_name_mapping_static.yaml
- environment.yml
- tests/test_pypi_name_mapper.py
This is a single commit e481b53 on top of #1640.
This makes sure that we deal with only canonicalized PyPI names, as defined by PyPA's `packaging` package.
[Diff](https://gist.github.com/maresb/ec2ba446305650052ff59836fad76f3e)
> Canonicalize pypi names

- conda_forge_tick/pypi_name_mapping.py
This is a single commit 17ccf56 on top of #1640.
The `convert_to_grayskull_style_yaml` function reindexes from the import name to the PyPI name. In case there are multiple PyPI names for a given import name, only the winner is represented in the resulting Grayskull mapping. Here we add the missing PyPI names back in.
[Diff](https://gist.github.com/maresb/9b967049cc7783a877f0014960ddad5e)
> Add missing pypi mappings

- conda_forge_tick/pypi_name_mapping.py
This corrects a few type annotations for which I couldn't be this specific originally since the `PypiName` type was defined in a separate branch.
Thanks a lot @beckermr for all the recent merges!!!
> Improve type annotations for add_missing_pypi_names

- conda_forge_tick/feedstock_parser.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators_types.pyi
Very specifically for https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1359, though hopefully useful in general.
I thought about this a bit, but I'm completely new to this codebase, and it's a bit hard to penetrate TBH. I mainly tried to follow Matthew's [idea](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1359#issuecomment-1029945907).
The migrator for fortran-only-on-windows would then look like:
```
__migrator:
kind:
version
migration_number: 1
build_number: 1
longterm: True
platform_allowlist:  # new
- win_64           # new
override_cbc_keys:
- fortran_compiler_stub
```
The underscore in `win_64` comes from the same pattern [elsewhere](https://github.com/regro/cf-scripts/blob/36cdec4560688d99aeced594f9d7e5da10e093b2/conda_forge_tick/feedstock_parse …
> add platform_allowlist for migrator

- conda_forge_tick/auto_tick.py
closes #1677 
This won't fix older PRs but should prevent new bot-rerun labels from being missed.
> BUG make sure to keep PR labels for bot-rerun

- conda_forge_tick/migrators/migration_yaml.py
For multiline commit messages (with more filled out bodies), split the commit message into multiple lines and only keep the 1st line of the commit message for use in the PR title.
> Use commit message's 1st line in migrator PR title

- conda_forge_tick/lazy_json_backends.py
- conda_forge_tick/make_graph.py
- tests/test_lazy_json_backends.py
This PR fixes a bug where remote DBs were updated with intermediate results for graph nodes.
> BUG make sure to only update remote DBs once when making the graph

- conda_forge_tick/migrators/migration_yaml.py
Improve visibility of additional details from the `commit_message` by including in the migrator PR's body message.
> Include `commit_message` body in `pr_body`

- conda_forge_tick/migrators/migration_yaml.py
As `super().pr_body(...)` adds its own text after the `additional_body` constructed by this migrator, make sure to have an `<hr>` right before that text so that the sections are not blended together.
Also quotes the `commit_body` text to make sure it stands out as separate from other text.
> Slight formatting tweaks to YAML migrator's PR body text

- conda_forge_tick/migrators/dep_updates.py
- conda_forge_tick/migrators/version.py
grayskull directly uses BaseException. 
closes #1743 
closes #1742 
closes #1741
> BUG catch'em all

- conda_forge_tick/migrators/version.py
- conda_forge_tick/update_sources.py
- conda_forge_tick/update_upstream_versions.py
- tests/test_upstream_versions.py
- tests/test_version_migrator.py
- tests/test_yaml/version_aws_sdk_cpp.yaml
- tests/test_yaml/version_aws_sdk_cpp_correct.yaml
xref: https://github.com/conda-forge/aws-sdk-cpp-feedstock/issues/662
This test confirms the current code works if it finds the version. It should have shipped 1.11.132 last week but did not. Thus I think this means that the bot did not find the version. I will check that next
> TST add test for random fraction to keep

- conda_forge_tick/pypi_name_mapping_static.yaml
PyPI uses "fastjsonschema" while conda uses "python-fastjsonschema"
> Add fastjsonschema to pypi_name_mapping_static.yaml

- conda_forge_tick/auto_tick.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/libboost.py
- tests/test_libboost.py
- tests/test_yaml/libboost_carve_after_meta.yaml
- tests/test_yaml/libboost_carve_before_meta.yaml
- tests/test_yaml/libboost_cctx_after_meta.yaml
- tests/test_yaml/libboost_cctx_before_meta.yaml
- tests/test_yaml/libboost_fenics_after_meta.yaml
- tests/test_yaml/libboost_fenics_before_meta.yaml
- tests/test_yaml/libboost_gudhi_after_meta.yaml
- tests/test_yaml/libboost_gudhi_before_meta.yaml
- tests/test_yaml/libboost_poppler_after_meta.yaml
- tests/test_yaml/libboost_poppler_before_meta.yaml
- tests/test_yaml/libboost_rdkit_after_meta.yaml
- tests/test_yaml/libboost_rdkit_before_meta.yaml
- tests/test_yaml/libboost_scipopt_after_meta.yaml
- tests/test_yaml/libboost_scipopt_before_meta.yaml
This is ~a draft~ the implenentation for https://github.com/conda-forge/boost-feedstock/pull/164
The main rule is:
* if `boost-cpp` is only a host dep, replace it with `libboost-headers` (that doesn't have nor need a run-export)
* if `boost-cpp` is also a run dep, remove it there and turn the host dep into `libboost-devel` (which has a run-export)
Additionally, `boost` is renamed to `libboost-python-devel`.
I tried to base myself on https://github.com/regro/cf-scripts/pull/1602, but found that I needed some more control, especially for multi-output recipes. Since everything is already parsed and re-parsed many times, I went with a dead-simple solution that avoids having to identify exactly where in the meta.yaml a given requirement comes from, but have a broad section (based on the …
> Piggyback migrator for boost unification

- conda_forge_tick/migrators/libboost.py
- tests/test_libboost.py
- tests/test_yaml/libboost_arrow_after_meta.yaml
- tests/test_yaml/libboost_arrow_before_meta.yaml
I noticed that something was going wrong, turns out I had not taken enough care with deps that have caps & pins.
The arrow-recipe for example only has a single `- boost-cpp >1.70` (which should become `- libboost-headers`), and so detection didn't do the right thing.
Fix-up for #1668
> Boost piggyback follow-up

- conda_forge_tick/auto_tick.py
Comes from https://matrix.to/#/!mPxkHLLyiXutAGtuaf:gitter.im/$0AVaD6APc2TPw1OsZoEPH76C86zjexoe1tV0gTTssxQ?via=gitter.im&via=matrix.org
The current output is a bit unreadable:
This hopefully improves it a bit.
> format not solvable error messages

- .github/workflows/bot-bot.yml
- .github/workflows/bot-cache.yml
- .github/workflows/bot-delete-old-runs.yml
- .github/workflows/bot-feedstocks.yml
- .github/workflows/bot-make-graph.yml
- .github/workflows/bot-prs.yml
- .github/workflows/bot-pypi-mapping.yml
- .github/workflows/bot-update-status-page.yml
- .github/workflows/bot-versions.yml
- .github/workflows/tests.yml
- autotick-bot/condarc
- autotick-bot/install_bot_code.sh
Going back to conda w/ libmamba solver.
> REF back to conda

- conda_forge_tick/migrators/dep_updates.py
The grayskull update of `harlequin` fails since some versions, but the log message `Dep update failed! KeyError('version')` doesn't help me find the issue. Thus I would like to have some more information in the log.
> Log the traceback of an exception during dependency update

- environment.yml
- tests/test_update_deps.py
This is required to work with newer poetry dependency definitions.
> Update to latest grayskull

- conda_forge_tick/update_sources.py
This is a fix for #1550
#1441 would be really great to fix this issue for everybody in long term.
Here is branch naming convention in oneDNN: https://github.com/oneapi-src/oneDNN/issues/1779
> update_sources: ignore preview candidate (pc) versions

- .pre-commit-config.yaml
Produces false negatives for strings, and should not be necessary, because black already takes care of trailing commas.
> remove `add-trailing-comma` pre-commit hook

- .github/workflows/tests.yml
Although in the current situation this error has no effect, the GitHub Actions workflow should not contain typos in environment variables.
> FIx Typo In Test GitHub Actions Workflow

- conda_forge_tick/cli.py
- conda_forge_tick/update_prs.py
- conda_forge_tick/update_upstream_versions.py
- tests/test_cli.py
- tests/test_upstream_versions.py
This part of #2131 adds the functionality of updating one single package and refactors the `update_upstream_versions.py` code. It also adds helpful debug output and tests the entire refactored code.
> Support Updating Single Package, Refactoring update_upstream_versions

- README.md
- conda_forge_tick/all_feedstocks.py
- conda_forge_tick/auto_tick.py
- conda_forge_tick/backend_settings.py
- conda_forge_tick/cli.py
- conda_forge_tick/depfinder_api.py
- conda_forge_tick/deploy.py
- conda_forge_tick/executors.py
- conda_forge_tick/feedstock_parser.py
- conda_forge_tick/lazy_json_backends.py
- conda_forge_tick/lazy_json_backups.py
- conda_forge_tick/make_graph.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/cross_compile.py
- conda_forge_tick/migrators/dep_updates.py
- conda_forge_tick/migrators/license.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators/version.py
- conda_forge_tick/pypi_name_mapping.py
- conda_forge_tick/status_report.py
- conda_forge_tick/update_deps.py
- conda_forge_tick/update_prs.py
- conda_forge_tick/update_recipe/version.py
- conda_forge_tick/update_sources.py
- conda_forge_tick/update_upstream_versions.py
- conda_forge_tick/utils.py
- tests/test_cli.py
- tests/test_lazy_json_backends.py
- tests/test_upstream_versions.py
- tests/test_utils.py
> [!IMPORTANT]
> This PR is an extension of #2139. #2139 should be reviewed and merged first.
As part of my work on #2123, this PR adds the following changes:
- The logger config is now handled centrally in `setup_logging` instead of configuring each module-level logger individually
- Add an `--online` CLI option that downloads missing dependency graph files from GitHub on demand (uses the new GithubLazyJsonBackend)
- Added tests
> Refactor Logging, Add GitHub Graph Backend

- conda_forge_tick/pypi_name_mapping_static.yaml
`lrcalc` refers to the c library, while `python-lrcalc` is the python wrapper, see https://github.com/conda-forge/lrcalc-feedstock/blob/main/recipe/meta.yaml#L42C11-L42C24.
CC: @isuruf
> Add static name mapping for lrcalc

- .github/workflows/bot-pypi-mapping.yml
- conda_forge_tick/cli.py
- conda_forge_tick/deploy.py
- conda_forge_tick/import_to_pkg.py
This PR adds the import to package mapping jobs to the bot, moving it out of libcfgraph. Once the maps are complete here, we can move the pypi name mappings to use this data and then turn off libcfgraph.
> ENH add import to package mapping

- conda_forge_tick/path_lengths.py
This PR attempts to make topological sorts stable.
> BUG make topological sort stable too

- conda_forge_tick/backend_settings.py
- conda_forge_tick/depfinder_api.py
- conda_forge_tick/import_to_pkg.py
- conda_forge_tick/lazy_json_backends.py
- conda_forge_tick/migrators/pip_wheel_dep.py
- conda_forge_tick/pypi_name_mapping.py
- conda_forge_tick/update_deps.py
- tests/test_lazy_json_backends.py
This PR changes the code to use the import to package mappings generated by the bot. With this change, we can turn off libcfgraph and deprecate it.
> REF use local import to pkg mappings

- conda_forge_tick/auto_tick.py
- conda_forge_tick/deploy.py
This PR tries deploying the data to github as we go to keep the bot's state safer. We had tried this before but had had trouble with it. A lot has changed including easier github deploys due to changes in the backend schema. So let's try again.
> ENH attempt to deploy as we go to avoid GHA kills

- conda_forge_tick/pypi_name_mapping_static.yaml
We are trying for a push on https://github.com/conda-forge/opencv-feedstock/issues/293 to help users moving from pypi
Thanks!
> Create alias for opencv-python-headless to opencv

- .github/workflows/bot-bot.yml
- .github/workflows/bot-cache.yml
- .github/workflows/bot-make-graph.yml
- .github/workflows/bot-prs.yml
- .github/workflows/bot-versions.yml
This PR moves the primary backend to the file interface so that changes made in the github repo are propagated to mongodb automatically. 🤞 
closes #2262
> PROD move file to primary backend

- conda_forge_tick/auto_tick.py
- conda_forge_tick/feedstock_parser.py
This PR adds special casing for feedstocks that have weird circular deps for bootstrapping. The example here is flit vs flit-core.
closes #2275
xref: https://github.com/conda-forge/flit-feedstock/issues/38 which if addressed would mean we do not need this PR
> BUG special-case bootstrapping stuff

- conda_forge_tick/migrators/cstdlib.py
- tests/test_stdlib.py
- tests/test_yaml/stdlib_rdkit_after_meta.yaml
- tests/test_yaml/stdlib_rdkit_before_meta.yaml
First follow-up to #2135 after looking at a failure in the rdkit feedstock, which uses a conda-build corner case that I hadn't thought of (and really dislike...)
> Fix corner case in stdlib piggyback

- .github/workflows/relock.yml
- autotick-bot/relock_me.py
Auto-label the relock PRs so they can be easily omitted in PR searches (same label as Dependabot ones).
> Label relock PRs

- conda_forge_tick/migrators/cstdlib.py
- tests/test_yaml/stdlib_rdkit_after_meta.yaml
See discussion in https://github.com/regro/cf-scripts/issues/2328
CC @isuruf @beckermr
> do not add stdlib to outputs without compilers

- conda_forge_tick/migrators/conda_forge_yaml_cleanup.py
This PR makes sure the abi_migration branches are strings so they pass the json schema validation.
xref: https://github.com/conda-forge/conda-smithy/issues/1890
> ENH make sure branches are strings

- conda_forge_tick/auto_tick.py
Now that we've fixed the initial set of [issues](https://github.com/regro/cf-scripts/issues/2328) uncovered by running the stdlib migrator (#2135) for the boost 1.84 migration, it should be time to roll it out to all migrations.
CC @beckermr @isuruf
> switch on stdlib-piggyback for all migrations

- conda_forge_tick/models/README.md
> fix: link to VersionPrInfo model

- conda-lock.yml
- conda_forge_tick/utils.py
- environment.yml
- pyproject.toml
- tests/conftest.py
This PR fixes a bug where I used CI to detect if we are running tests but this is also set for production jobs. I fixed it by using pytest-env and a custom variable to indicate testing.
> BUG use different envvar for detecting testing

- conda_forge_tick/feedstock_parser.py
- conda_forge_tick/update_upstream_versions.py
- conda_forge_tick/utils.py
- tests/test_container_tasks.py
This PR fixes issues where long JSON blobs caused problems at the CLI. For now we will fall back to redownloading the feedstock attributes from github via a raw url. It also puts in the absolute path of the python interpreter to try and speed things up.
> BUG fallback to feedstock names for long json blobs

- conda_forge_tick/feedstock_parser.py
This PR deduplicates the meta_yaml dicts aggregated over various platforms. It will cause a lot of turnover in the bot metadata for a while, but should reduce the overall size on disk eventually.
> ENH dedupe meta.yaml aggregated over platforms

- .github/workflows/bot-cache.yml
This is causing the mongodb backend to be out of sync with the github repo.
> BUG do not cache in CI if primary backend is file

- conda_forge_tick/utils.py
This PR adds `load_file_regex` to our custom jinja2 env. I am not going to add all of the others quite yet since it is actually nice to see the errors from what is missing.
> BUG some recipes use load_file_regex

- .github/workflows/bot-bot.yml
- .github/workflows/bot-delete-old-runs.yml
- .github/workflows/bot-feedstocks.yml
- .github/workflows/bot-make-graph.yml
- .github/workflows/bot-prs.yml
- .github/workflows/bot-pypi-mapping.yml
- .github/workflows/bot-update-status-page.yml
- .github/workflows/bot-versions.yml
- .github/workflows/tests.yml
- README.md
- autotick-bot/bump_bot_team.py
- autotick-bot/delete_old_runs.py
- conda_forge_tick/all_feedstocks.py
- conda_forge_tick/auto_tick.py
- conda_forge_tick/deploy.py
- conda_forge_tick/env_management.py
- conda_forge_tick/git_utils.py
- conda_forge_tick/update_prs.py
- conda_forge_tick/utils.py
- tests/conftest.py
- tests/test_env_management.py
- tests/test_security.py
This PR centralizes all of the tokens to just be BOT_TOKEN as opposed to GITHUB_TOKEN and PASSWORD.
> REF use BOT_TOKEN as only cred

- conda_forge_tick/auto_tick.py
I am cleaning up yet more shared state in prep for running migrators in separate processes.
> DEP do not set attrs on migrator

- conda_forge_tick/utils.py
This one fixes a bug where the container run env var was not being set properly.
> BUG did not set container run env var properly

- conda_forge_tick/auto_tick.py
- conda_forge_tick/migrators/cstdlib.py
This was already brought up in #2372, and discussed in today's core call as well (no objection to turning it on despite the limitation about templated output names). Since we haven't had any notable issues I can remember over the last ~2 weeks, I think it's a good time to add it to the version migrator as well now.
Also pick up a drive-by fix for making the sysroot regex pattern catch some more relevant cases.
> add stdlib piggyback to version_migrator

- conda_forge_tick/auto_tick.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/numpy2.py
Fixes #2469; goes hand-in-hand with (the migrator filename used in) https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5790
This is a baby version of #2135 / #1668, where we've already extensively tested the used functionality. Strictly speaking, we could even avoid the whole dance with `_slice_into_output_sections` and just directly remove any lines matching the regex pattern for `pin_compatible("numpy",...)` in the meta.yaml. However, I left it in for now in case anyone wants to add some logic that takes into account existing host-/run-dependencies, because then we need to operate on a per-section basis.
> add mini-piggyback migrator for removing `pin_compatible("numpy"...)`

- .github/workflows/tests.yml
- .pre-commit-config.yaml
- conda_forge_tick/os_utils.py
- conda_forge_tick/rerender_feedstock.py
- conda_forge_tick/utils.py
- docker/run_bot_task.py
- tests/test_container_tasks.py
> BUG make sure rerenders work and set permissions correctly

- conda_forge_tick/pypi_name_mapping_static.yaml
igl-feedstock is the python bindings. After install of igl, `pip check` fails, e.g.:
`napari-threedee 0.0.17 requires libigl, which is not installed.`
On pypi this package is `libigl`, even though the import is igl.
I think this PR should harmonize that?
> Update pypi_name_mapping_static.yaml to add igl

- conda_forge_tick/migrators/migration_yaml.py
The formatting of the commit message in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5790 gets completely busted by stripping all linebreaks here (presumably done to use a single quote indent?!), see for example: https://github.com/conda-forge/matplotlib-feedstock/pull/376.
To fix this, keep whitespace unchanged and indent the quote correctly, the processed `additional_body` would look like this:
<details>
<summary>raw</summary>
Note extra `> ` at the top because we're only slicing the `splitlines()` from `[1:]`, which I've kept because it's a security if someone forgets the double-linebreak. It doesn't get rendered anyway.
```
>
> TL;DR: The way we build against numpy has changed as of numpy 2.0. This bot
> PR has updated the recipe to account for the changes (see …
```
> keep formatting of migrator commit_message; consistently use quote indent

- conda_forge_tick/migrators/cstdlib.py
- conda_forge_tick/migrators/libboost.py
- tests/test_container_tasks.py
- tests/test_libboost.py
- tests/test_stdlib.py
- tests/test_yaml/stdlib_gz-common_after_meta.yaml
- tests/test_yaml/stdlib_libhdbpp-timescale_after_meta.yaml
> REF make libboost migrator more robust

- .github/workflows/keepalive.yml
The keep alive v2 action allows to use the GH API instead of dummy commits. However, it comes with a few pitfalls 🤔 
- The API call keeps a _workflow_ alive, not the entire repository. So we need to either add the step to every workflow to keep alive, or use the `workflows` setting. This is prone to break.
- We need to update the `permissions` in the workflow too. Note this was not properly configured before either, and probably would have ended up failing.
For that reason, I'm reverting back to commit mode (`use_api: false`) that simply keeps everything operational without further work (and it's also future proof in case more cron based workflows are added). I don't think we care too much about the commit history, but let me know otherwise.
> Use commits for keep alive again

- conda_forge_tick/migrators/cstdlib.py
- tests/test_yaml/stdlib_go_after_meta.yaml
> don't remove `m2w64_` prefix in stdlib piggyback

- README.md
- tests/conftest.py
- tests/test_container_tasks.py
- tests/test_upstream_versions.py
This PR changes the tests to run mostly without containers. It also turns off container tests unless docker is available and the right image has been built locally.
closes #2550
> TST run tests mostly without containers

- tests/test_container_tasks.py
This PR makes sure to swallow errors in the docker tests if we encounter them.
cc @h-vetinari
> BUG make sure to swallow errors

- conda_forge_tick/auto_tick.py
- conda_forge_tick/lazy_json_backends.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/arch.py
- conda_forge_tick/migrators/broken_rebuild.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/dep_updates.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators/version.py
- tests/test_migrator_to_json.py
This PR is a start on dumping and loading migrators from JSON. The goal is to eventually separate out the creation of migrators from running them.
> ENH dump migrators to json

- conda_forge_tick/deploy.py
Missed this bit from putting migrators to JSON.
> BUG do not deploy empty dirs

- conda_forge_tick/status_report.py
Assuming this works well for a while, we will move over the bot job itself too.
> ENH run status page from pre-built migrators

- tests/test_container_tasks.py
This PR fixes a bug where the tests didn't pass if parts of the feedstock were out of date.
> BUG make sure tests always pass for latest version

- conda_forge_tick/auto_tick.py
- conda_forge_tick/contexts.py
- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/arch.py
- conda_forge_tick/migrators/broken_rebuild.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/matplotlib_base.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators/replacement.py
- conda_forge_tick/migrators/version.py
- tests/test_migration_yaml_migration.py
- tests/test_migrators.py
This PR removes the migrator contexts to further isolate the migrators from graph state so that they have their full state serialized as json. This will allow them to be run on demand without access to the full graph, in isolated environments like containers, etc.
> DEP remove migrator context

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/migration_yaml.py
This PR should ramp PRs for migrators better. It starts them slow, then bumps them up in rate for a while and then back down. Hopefully, this will emphasize newly merged migrators a bit over older ones that have gone through most of their work.
> ENH ramp PRs better

- conda_forge_tick/auto_tick.py
- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/migration_yaml.py
OK @h-vetinari here is an initial attempt at issuing PRs after many failed solver attempts per feedstock. Right now I set this to 100 attempts. A bot job takes ~2 hours, so the bot will try a PR for about a week before issuing it. This matches the other timescales we give maintainers to fix things up. We don't actually notify folks of failed solver attempts, but if we did, the week would be the right timescale.
> ENH force issue PRs after many many solver attempts

- conda_forge_tick/auto_tick.py
We are getting the wrong attempts field in the bot metadata for skipping solver checks for versions.
> BUG make sure to get proper attempts for Version migrator

- conda_forge_tick/migrators/migration_yaml.py
This bug is preventing pinning PRs from being made. This is the cause of why the bot never made the proper orc PR. 
cc @h-vetinari
> BUG need to set pin_impact attribute

- conda_forge_tick/migrators/version.py
It turns out we were not logging the exceptions here. Let's do that to figure this out. 
xref: #2656
> BUG make sure to log error

- conda_forge_tick/update_sources.py
- tests/test_upstream_versions.py
Pick up release prefix from the archive URL.
After this changes version at is picked up properly:
```
> CF_TICK_IN_CONTAINER=true python -m conda_forge_tick.cli --debug --online update-upstream-versions --job=1 --n-jobs=1 spirv-headers
2024-05-22 15:26:16,058 DEBUG    conda_forge_tick.update_upstream_versions || Fetching latest version for spirv-headers from Github...
2024-05-22 15:26:16,058 DEBUG    conda_forge_tick.update_sources || Found version prefix from url: vulkan-sdk-
2024-05-22 15:26:16,058 DEBUG    conda_forge_tick.update_upstream_versions || Using URL https://github.com/khronosgroup/spirv-headers/releases.atom
2024-05-22 15:26:16,801 DEBUG    conda_forge_tick.update_upstream_versions || Found version 1.3.283.0 on Github
2024-05-22 15:26:16,801 INFO …
```
> Use version prefix from github URL

- conda-lock.yml
- conda_forge_tick/deploy.py
- conda_forge_tick/git_utils.py
- conda_forge_tick/utils.py
- environment.yml
- mypy.ini
- tests/test_utils.py
This PR removed `doctr_run` and the corresponding dependency from our repo.
Why?
- In the very near future, `GitCli` should be able to run commands that require token hiding in outputs. However, I cannot easily use `doctr_run` for it because I need more control over the subprocess `CompletedProcess` return object. 
- With this change, I have `run_command_hiding_token` which is equivalent to `doctr_run` as well as `print_subprocess_output_strip_token`, allowing me to run the subprocess with token hiding logic manually.
- doctr is quite a big dependency just to get a 10-line function, so probably it's a good idea to remove it anyway.
> Replace doctr_run with our own token-preserving function

- conda_forge_tick/feedstock_parser.py
The model validation caught a bug in that old platforms are not being removed. This bug appears to be completely silent and harmless, but we should fix anyways.
> BUG make sure to remove old platform info from node attrs

- conda_forge_tick/make_graph.py
- docker/run_bot_task.py
This PR is a followup to #2667. The node data comes from the container and so we need to clear the dict on the host side before we update.
> BUG need to clear out old data instead of doing updates

- conda_forge_tick/migrators/arch.py
- tests/test_migrator_to_json.py
This PR ensures the init of the arch migrators doesn't use graph attributes. This way they can be used in isolated envs.
> ENH ensure arch migrator does not use graph data on init from json

- conda_forge_tick/migration_runner.py
- tests/test_container_tasks.py
This PR makes the tests a bit more robust but also possibly more fragile. It also turns containers back on since it is working.
> TST improve tests of version PRs in containers

- conda_forge_tick/auto_tick.py
- conda_forge_tick/executors.py
- conda_forge_tick/git_utils.py
- conda_forge_tick/lazy_json_backends.py
- conda_forge_tick/update_prs.py
- tests/test_executors.py
- tests/test_git_utils.py
In my efforts about adding easier local debugging for the bot, we need a way to let the bot run without the need of having a conda-forge GitHub token available. Accomplishing this is not easy with the current codebase because the git and token logic is baked into it.
With this PR, I begin to decouple the git logic and make everything interfacing with GitHub replaceable by a dry run backend (that is currently still unused). To keep the PR small, not all git operations but only some now use the new object-oriented git approach. Further PRs will follow that replace more of the logic.
> Begin Building on a modular Git Backend

- conda_forge_tick/provide_source_code.py
- docker/run_bot_task.py
This PR puts the i/o capture right over the conda-build call that seems to escape the higher level i/o redirect.
> BUG redirect right at the source for getting source code

- conda_forge_tick/url_transforms.py
- tests/test_url_transforms.py
This adds _yet another_ URL to try, namely the basically-now-ubiquitous [PEP625](https://peps.python.org/pep-0625/) form:
```
old    package-name-0.0.0.tar.gz
V
new    package_name-0.0.1.tar.gz
```
> Also try mangling sdist urls to match pep625

- conda_forge_tick/migrators/cstdlib.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators/mpi_pin_run_as_build.py
#2698 didn't fix #2696, as seen [here](https://github.com/conda-forge/petsc-feedstock/pull/204/files#diff-ff61408cdc05bc9667deeadb55e4aaceb1371972076b6bf6934f9008920f2bd2). It also adds an _additional_ trailing newline, even if there is one.
I found 3 places where trailing newlines could be mishandled:
- yaml migrator (only affects conda-forge-pinning, I think)
- cstdlib (#2698 adds an _additional_ trailing newline rather than ensuring one exists)
- mpi_pin_run_as_build - I'm pretty sure this is actually the one that was affecting the petsc feedstock, which prompted #2696 . I was able to run the migrator on petsc and it re-stripped the trailing newline.
reissue and extend #2696. GitHub didn't give me a reopen button, perhaps because the branch had been deleted.
> consistently ensure trailing newline in recipe conda_build_config.yaml

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/r_ucrt.py
- tests/test_r_ucrt.py
> Add R UCRT cleanup mini migrator

- .pre-commit-config.yaml
- conda_forge_tick/feedstock_parser.py
- pyproject.toml
black is [not intended to be used next to ruff-format](https://docs.astral.sh/ruff/faq/#is-the-ruff-linter-compatible-with-black):
> Ruff is designed to be used alongside a formatter (like Ruff's own formatter, or Black) and, as such, will defer implementing stylistic rules that are obviated by automated formatting.
In fact, the current pre-commit setup actively prevents me from committing a file where black and ruff format conflict with each other.
This is why I propose to remove `black` from this project, since we already have `ruff-format`.
Also, `ruff` has support for [`I` rules that are comparable with `isort`](https://docs.astral.sh/ruff/rules/#isort-i). Since `isort` has no profile for `ruff-format` (only for `black`) we should also switch over to using these rules instead of using …
> Remove Black Formatter, replace isort by ruff rules

- .github/workflows/bot-bot.yml
- tests/test_container_tasks.py
- The original threw an exception if `docker` was missing.
- Not all tests using `docker` used `HAVE_CONTAINERS`
> fix: `HAVE_CONTAINERS` check

- conda_forge_tick/feedstock_parser.py
- docker/run_bot_task.py
- tests/test_container_tasks.py
- tests/test_migration_yaml_migration.py
- tests/test_migrators.py
- tests/test_security.py
- Some error handling is moved from `populate_feedstock_attributes` to `load_feedstock_local`
- This allowed to handle bad responses earlier and a bit less awkward
- Special case a few places which require `meta_yaml` to be present
> feat: Extend feedstock functions to allow for `recipe_yaml`

- environment.yml
It is already a transitive dependency, but since it will be used directly to render recipes, I think it makes sense to mention it here as well.
> chore: Add rattler-build dependency

- tests/test_version_migrator.py
- tests/test_yaml/version_polars_mixed_selectors.yaml
- tests/test_yaml/version_polars_mixed_selectors_correct.yaml
- tests/test_yaml/version_polars_name_selectors.yaml
- tests/test_yaml/version_polars_name_selectors_correct.yaml
- tests/test_yaml/version_polars_variant_selectors.yaml
- tests/test_yaml/version_polars_variant_selectors_correct.yaml
This PR add xfail tests for the feature requested in #2833. The current [polars-feedstock](https://github.com/conda-forge/polars-feedstock) uses name selectors but also the two other scenarios should be supported.
> Add xfail tests for #2833 (support sources that depend on conda build config variants)

- conda_forge_tick/auto_tick.py
- conda_forge_tick/executors.py
- conda_forge_tick/git_utils.py
- conda_forge_tick/lazy_json_backends.py
- conda_forge_tick/update_prs.py
- tests/test_executors.py
- tests/test_git_utils.py
This should resolve the errors we observed in https://github.com/regro/cf-scripts/actions/runs/9465733947/job/26075864527
We erroneously returned the directory name of the feedstock and not the full feedstock path in `get_repo`.
> Readd Git backend, again

- .github/workflows/test-model.yml
The model check should only be run periodically and on request, not on pushes to master or PRs.
xref https://github.com/regro/cf-scripts/issues/2244#issuecomment-2200064651
For debugging, it is still possible to run this on request or locally.
Unfortunately, there is no other good way to remove confusion about the red crosses: https://github.com/orgs/community/discussions/15452
> model check should not run on PRs or pushes

- typos.toml
Seems like my original pattern for `.git` and `.pixi` didn't actually work
> chore: Extend typo extend-exclude glob

- .github/workflows/release.yml
- autotick-bot/install_bot_code.sh
- conda_forge_tick/utils.py
- environment.yml
- pyproject.toml
Description:
This PR updates the deps for scm and uses the latest tag for docker
Checklist:
Cross-refs, links to issues, etc:
xref: #2894
> feat: update deps for scm and use `latest` for docker tag

- .github/pull_request_template.md
- .github/workflows/release.yml
- .github/workflows/tests.yml
This PR adds caching of docker layers to speed up the build.
> feat: cache docker image layers too

- conda_forge_tick/recipe_parser/_parser.py
- tests/test_recipe_parser.py
jinja2 variables with selectors but not repeated were not properly reported as having selectors applied. This PR fixes that.
> fix: make sure to put selectors in for all jinja2 vars

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/status_report.py
This PR adds code to try and keep paused migrators around in the bot system.
xref #2885 
closes #2885
> fix: keep paused migrators in status reports

- conda_forge_tick/make_migrators.py
This PR removes the build to python-build migrator per https://github.com/conda-forge/conda-forge.github.io/issues/2269.
xref: https://github.com/conda-forge/conda-forge.github.io/issues/2269
> feat: remove build to python-build migration

- conda_forge_tick/migrators/version.py
This PR disables dependency checking by default for version migrations. Folks can still opt-in if they want.
closes #2929
> feat: disable dependency checking by default

- .github/workflows/relock.yml
- autotick-bot/relock_me.py
This PR fixes a bug where we did not update for all pinnings packages. We used to pull the pinnings packages directly, but now we only use the conda package so we have to always update.
> fix: always update for deps and skip making PR if it already exists

- conda_forge_tick/migrators/core.py
> feat: print the bad attr we find for debugging purposes

- conda_forge_tick/auto_tick.py
This PR fixes a bug where rerender errors were making nodes be flagged as bad. It happened because we moved rerendering to containers so the error string changed.
xref: #2961
> fix: do not set bad for rerender errors

- conda_forge_tick/migrators/migration_yaml.py
- tests/test_container_tasks.py
- tests/test_migration_runner.py
This PR modifies the PR description for migrations to include a link to the migration page on conda-forge.org. This may help (will help me) maintainers understand the status of the whole migration and where their package update sits in the grand scheme of things.
> Link to migration on conda-forge.org in PR description

- README.md
- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/migration_yaml.py
> Allow migrating compilers using `include_build`

- conda_forge_tick/feedstock_parser.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/cross_compile.py
- conda_forge_tick/migrators/cstdlib.py
- conda_forge_tick/migrators/dep_updates.py
- conda_forge_tick/migrators/duplicate_lines.py
- conda_forge_tick/migrators/extra_jinj2a_keys_cleanup.py
- conda_forge_tick/migrators/jinja2_vars_cleanup.py
- conda_forge_tick/migrators/jpegturbo.py
- conda_forge_tick/migrators/libboost.py
- conda_forge_tick/migrators/license.py
- conda_forge_tick/migrators/matplotlib_base.py
- conda_forge_tick/migrators/numpy2.py
- conda_forge_tick/migrators/pip_check.py
- conda_forge_tick/migrators/pip_wheel_dep.py
- conda_forge_tick/migrators/qt_to_qt_main.py
- conda_forge_tick/migrators/r_ucrt.py
- conda_forge_tick/migrators/use_pip.py
- conda_forge_tick/migrators/version.py
This PR skips all migrators on the v1 schema for now. 
closes #2918
> feat: skip all migrators on schema v1 for now

- conda_forge_tick/auto_tick.py
Building upon #3000, this PR refactors the solvability checking code in auto_tick.
#3000 needs to be merged first.
> (Git-5) Refactor Solvability Check in auto_tick

- conda_forge_tick/migrators/migration_yaml.py
- tests/test_migrators_v1.py
- tests/test_recipe_yaml/sample_matplotlib.yaml
- tests/test_recipe_yaml/scipy_migrate.yaml
I added some tests modeled after the other migration tests. 
The matplotlib test currently raises an NotImplemented Error: 
```
elif isinstance(recipe_yaml, str):
raise NotImplementedError(
"recipe_yaml generic parsing not implemented yet! Ensure the feedstock has .ci_support files."
)
```
@beckermr - do we need to do that first? I am not entirely sure what this code does.
> feat: test v1 recipe.yaml migrations

- conda_forge_tick/migration_runner.py
This should fix the run url not being put in the bot PR descriptions properly.
> fix: ensure RUN_URL is passed to container

- conda_forge_tick/container_cli.py
This PR removes old rerender code.
> fix: remove old rerender code

- conda_forge_tick/lazy_json_backends.py
- conda_forge_tick/utils.py
This PR ensures that the code will work with networkx >=3.6.
> fix: ensure code works with API change in networkx>=3.6

- conda_forge_tick/pypi_name_mapping_static.yaml
This PR adds a static override for pyyaml for pypi mappings. The issue here is that the pyyaml recipe has two imports for testing (`yaml` and `_yaml`), and this confuses the bot's code. I don't want to fix that since TBH the code the bot is using here is complex and not where we should be going. So a manual override is expedient. 
closes #3031
> fix: add static override for pyyaml

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/flang.py
- tests/test_flang.py
- tests/test_yaml/flang_lapack_after_meta.yaml
- tests/test_yaml/flang_lapack_before_meta.yaml
- tests/test_yaml/flang_mfront_after_meta.yaml
- tests/test_yaml/flang_mfront_before_meta.yaml
- tests/test_yaml/flang_pcmsolver-split_after_meta.yaml
- tests/test_yaml/flang_pcmsolver-split_before_meta.yaml
- tests/test_yaml/flang_plplot_after_meta.yaml
- tests/test_yaml/flang_plplot_before_meta.yaml
- tests/test_yaml/flang_prima_after_meta.yaml
- tests/test_yaml/flang_prima_before_meta.yaml
This one was harder than usual because of some fun Python regex bugs and the "take all consecutive compilers in a block" logic. 🙃 
I'll note that the target here (as for most piggyback migrators) is not 100% perfection, but to reliably switch over to flang. It's better that a bot PR fails spuriously and we fix it manually, rather than that it is rerendered incorrectly (i.e. not activating flang) and merged prematurely simply because CI is green.
Here the diffs for the before/after in the tests for ease of review (minus the spurious version bumps from abusing the version migrator as a crutch), generated with
```
git diff HEAD:tests/test_yaml/flang_<pkg>_before_meta.yaml..HEAD:tests/test_yaml/flang_<pkg>_after_meta.yaml
```
<details>
<summary>lapack</summary>
```diff
diff --git …
```
> Add piggyback migrator for flang

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/pypi_org.py
- tests/test_pypi_org.py
- tests/test_yaml/pypi_org_seaborn_after_meta.yaml
- tests/test_yaml/pypi_org_seaborn_before_meta.yaml
Smithy now [warns](https://github.com/conda-forge/conda-smithy/pull/2104) feedstocks to switch from pypi.io to pypi.org. I remember @ocefpaf saying we should write a minimigrator, but cannot find the message across several channels now.
This PR would be a pretty simple way to write a migrator (with a test), plus enable it for all migrations. Feel free to use this as the basis if you want to write your own implementation, or you can add tests for favourite feedstocks with how the before/after should look (note: due to limitations of the testing infrastructure, we need to attach a minimigrator to _something_, and the easiest thing is a version migrator).
```diff
>git diff HEAD:tests/test_yaml/pypi_org_seaborn_before_meta.yaml..HEAD:tests/test_yaml/pypi_org_seaborn_after_meta.yaml
diff --git …
```
> add piggyback migrator that changes pypi.io to pypi.org

- conda_forge_tick/provide_source_code.py
- tests/test_container_tasks.py
This PR fixes a bug where I was not properly using conda-build to parse variant config files when getting the source.
> fix: use conda-build to parse variant files normally when getting source

- conda_forge_tick/url_transforms.py
- tests/test_url_transforms.py
I am trying to catch more pypi errored versions.
> fix: try munged pypi urls with middle section left alone

- conda_forge_tick/update_recipe/version.py
- tests/test_version_migrator.py
- tests/test_yaml/version_21cmfast_correct.yaml
- tests/test_yaml/version_algotree.yaml
- tests/test_yaml/version_algotree_correct.yaml
- tests/test_yaml/version_dash_extensions_correct.yaml
- tests/test_yaml/version_pypiurl_correct.yaml
- tests/test_yaml/version_pyrsmq_correct.yaml
This PR uses the PyPI api directly to get urls. It should be faster than the existing guess-and-check approach to transforming urls. 
fixes #3146
> feat: use pypi api directly to get urls

- environment.yml
This PR pins pydantic to <2.10 for now due to failing test.
xref: #3177
> chore: pin pydantic to <2.10 for now

- conda_forge_tick/update_deps.py
- tests/test_update_deps.py
- tests/test_yaml/ngmix.json
This PR allows grayskull to run on packages with github urls.
closes #3169
> fix: allow grayskull to run on github urls

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/noarch_python_min.py
- conda_forge_tick/status_report.py
- tests/test_noarch_python_min_migrator.py
Trying again with build sections now included for `noarch: python`.
> fix: ensure we migrate build sections for `noarch: python`

- conda_forge_tick/make_migrators.py
- conda_forge_tick/status_report.py
I forgot to cut down the input nodes to only those that need a migration.
> fix: use proper graph for `noarch: python` min migrator

- conda_forge_tick/make_migrators.py
This PR removes the edges from the `noarch: python` migrator graph in an attempt to fix the status page (which shows all things being children of all things).
> fix: remove edges from noarch python migrator graph

- conda_forge_tick/make_migrators.py
This PR adds a set of default mini-migrators for every thing we can.
> fix: use mini-migrators for everything

- conda_forge_tick/update_sources.py
- conda_forge_tick/update_upstream_versions.py
- tests/test_upstream_versions.py
This PR puts version feed updates before raw urls. Hopefully it saves us time and is more reliable. I feel like someone may have suggested this in the past and I was not in support for some reason, but now I cannot recall. Let's go ahead and see what rustles up.
> fix: try version feeds before raw urls

- conda_forge_tick/migrators/noarch_python_min.py
This PR will fix feedstocks marked as "awaiting parents" in the status page. The current filter condition excludes things already migrated, but that is not right. It should only exclude things the never need a migration. The bot can then decide what to do when it attempts to migrate them.
> fix: wrong filter condition for `noarch: python` python_min migration

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/cross_compile.py
- conda_forge_tick/migrators/cstdlib.py
- conda_forge_tick/migrators/dep_updates.py
- conda_forge_tick/migrators/duplicate_lines.py
- conda_forge_tick/migrators/extra_jinj2a_keys_cleanup.py
- conda_forge_tick/migrators/flang.py
- conda_forge_tick/migrators/jinja2_vars_cleanup.py
- conda_forge_tick/migrators/jpegturbo.py
- conda_forge_tick/migrators/libboost.py
- conda_forge_tick/migrators/license.py
- conda_forge_tick/migrators/matplotlib_base.py
- conda_forge_tick/migrators/noarch_python_min.py
- conda_forge_tick/migrators/numpy2.py
- conda_forge_tick/migrators/pip_check.py
- conda_forge_tick/migrators/pip_wheel_dep.py
- conda_forge_tick/migrators/pypi_org.py
- conda_forge_tick/migrators/qt_to_qt_main.py
- conda_forge_tick/migrators/r_ucrt.py
- conda_forge_tick/migrators/use_pip.py
This PR fixes another error in the status page for the `noarch: python` min migration.
> fix: get correct total graph for noarch py min

- conda_forge_tick/events/pr_events.py
This PR only updates the event if the data has changed.
> fix: only update PR if needed

- .github/workflows/bot-prs.yml
- .github/workflows/bot-update-status-page.yml
This PR updates the PR jobs to run once a day and puts the status page on a loop.
It is the counterpart to https://github.com/conda-forge/conda-forge-webservices/pull/794 and should be merged after that one. With both changes, the bot should react to PR events and has a once-a-day loop to cleanup any missed events.
> feat: update PR jobs to run once a day and put status page on a loop

- conda_forge_tick/make_graph.py
This PR moves the run exports adjustment to the nodes to the global graph making stage. It is preparation for pushing updates to node metadata via events.
> refactor: move run exports adjustment to global op when making graph

- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators/noarch_python_min.py
- conda_forge_tick/migrators/replacement.py
This PR ensures that all migrations ignore bad PRs when issuing things.
fixes #3272
> fix: use ordering of PRs ignoring bad ones

- autotick-bot/bump_bot_team.py
- conda_forge_tick/deploy.py
- conda_forge_tick/migrators/core.py
This PR fixes an issue where conflicts happen that can be resolved if the files are committed. It is due to the batching.
closes #3276
> fix: add conflicts when pull fails

- conda_forge_tick/auto_tick.py
- conda_forge_tick/make_graph.py
- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/version.py
- conda_forge_tick/update_prs.py
- conda_forge_tick/update_upstream_versions.py
- tests/test_upstream_versions.py
This PR switches to the `secrets` module in order to generate true random numbers. The bot relies on randomly selecting items to update and we need true randomness to ensure everything gets an update eventually. The code was using a true random set of bytes to seed a deterministic RNG, but this scheme should be better and easier to manage since there is no global state to keep track of. I also added updates to only a random fraction of nodes to the version update job to help prevent failures.
> fix: use secrets random numbers to get true random numbers and update only a fraction of versions

- conda_forge_tick/events/pr_events.py
- conda_forge_tick/git_utils.py
- conda_forge_tick/update_prs.py
Trying more fixes for out of order updates.
> fix: try last-modified instead of etag to avoid oo updates

- conda_forge_tick/lazy_json_backends.py
The github api needs this call to pull large files.
> fix: use special api call for large files

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/xz_to_liblzma_devel.py
- tests/test_xz_liblzma_devel.py
- tests/test_yaml/libtiff_with_liblzma_devel.yaml
- tests/test_yaml/libtiff_with_xz.yaml
Mini-Migrator to rename `xz` to `liblzma-devel` if `xz` is listed in `host`.
Fixes #3318
> Add mini-migrator for xz->liblzma-devel

- .github/workflows/bot-bot.yml
- .github/workflows/bot-feedstocks.yml
- .github/workflows/bot-make-graph.yml
- .github/workflows/bot-make-migrators.yml
- .github/workflows/bot-migrate-schema.yml
- .github/workflows/bot-prs.yml
- .github/workflows/bot-pypi-mapping.yml
- .github/workflows/bot-update-nodes.yml
- .github/workflows/bot-update-status-page.yml
- .github/workflows/bot-versions.yml
- autotick-bot/install_bot_code.sh
- conda_forge_tick/cli.py
- conda_forge_tick/deploy.py
- conda_forge_tick/os_utils.py
This PR cleans the disk space less to make the bot runs more efficient.
> feat: clean disk space less to make bot runs more efficient

- .github/workflows/bot-feedstocks.yml
- .github/workflows/bot-make-graph.yml
- .github/workflows/bot-make-migrators.yml
- conda_forge_tick/all_feedstocks.py
- conda_forge_tick/make_graph.py
- conda_forge_tick/make_migrators.py
This PR moves the code back to always using the deploy step and relying on the GH API there. If we ever run out of token requests, the bot should default to its normal git CLI pull and push.
> feat: always use deploy step and rely on GH API push there

- conda_forge_tick/events/pr_events.py
> fix: refresh before testing label

- conda_forge_tick/update_prs.py
We update them at random, so it is better to do all of the updates for a given PR.
> fix: update a PR with everything or nothing

- conda_forge_tick/auto_tick.py
> fix: migrators with no nodes do not need min time

- README.md
- conda_forge_tick/auto_tick.py
- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/migration_yaml.py
This was 100, now it is 10. Let'em go!
> feat: try PRs only 10 times

- conda_forge_tick/auto_tick.py
> fix: do not set pr_info bad for version migration errors

- conda_forge_tick/auto_tick.py
> fix: let them all go

- conda_forge_tick/auto_tick.py
> feat: push PRs w/ rerender comment if not doing solver checks and rerender fails

- conda_forge_tick/migrators/cstdlib.py
- tests/test_stdlib.py
- tests/test_yaml/stdlib_pysyntect_after_meta.yaml
- tests/test_yaml/stdlib_pysyntect_before_meta.yaml
- tests/test_yaml/stdlib_unicorn_after_meta.yaml
- tests/test_yaml/stdlib_unicorn_before_meta.yaml
See the tests for what happened.
> fix: edge cases in cstdlib for comments and test section before build

- environment.yml
Fixes the env relocking which doesn't work for forks.
> prod: add rattler-build-conda-compat to deps

- .github/workflows/bot-bot.yml
- .github/workflows/bot-cache.yml
- .github/workflows/bot-events.yml
- .github/workflows/bot-feedstocks.yml
- .github/workflows/bot-make-graph.yml
- .github/workflows/bot-make-migrators.yml
- .github/workflows/bot-prs.yml
- .github/workflows/bot-pypi-mapping.yml
- .github/workflows/bot-update-nodes.yml
- .github/workflows/bot-update-status-page.yml
- .github/workflows/bot-versions.yml
- .github/workflows/keepalive.yml
- .github/workflows/release.yml
- .github/workflows/relock.yml
- .github/workflows/test-model.yml
- .github/workflows/tests-reusable.yml
The comments behind the hash are not version pins, but solely intended as human-readable translation. This PR updates all external GitHub Actions to the latest compatible version and changes the comment to the full version string. Dependabot supports updating this.
We also now use `supercharge/mongodb-github-action` because it is actively maintained and functionally equivalent to the Action we used before.
> [minor fix] fix GitHub Actions version comments

- conda_forge_tick/git_utils.py
- conda_forge_tick/lazy_json_backends.py
The GH API changed and we need to catch an additional set of exceptions for testing if files exist.
> fix: catch other GH exceptions for no object

- conda_forge_tick/update_recipe/version.py
- tests/test_migrators.py
- tests/test_v1_yaml/version_polars.yaml
- tests/test_v1_yaml/version_polars_correct.yaml
- tests/test_v1_yaml/version_polars_variants.yaml
- tests/test_version_migrator.py
- tests/test_yaml/version_polars_by_variant.yaml
- tests/test_yaml/version_polars_by_variant_correct.yaml
This PR adds tests for sources that conditionally depend on conda-build-config variants. The feature is used by popular feedstocks (rust-feedstock, polars-feedstock).
> add tests for sources that depend on conda build config variants (recipe v0 & v1)

- conda_forge_tick/migrators/migration_yaml.py
Some how we missed enabling v1 recipes for regular YAML ABI migrations. :/
closes #3716
This might solve some of the other incorrect "awaiting parents" feedstocks on the status page as well. I checked pytorch explicitly.
> fix: need to allow schema version 1 for yaml migrations

- conda_forge_tick/migrators/conda_forge_yaml_cleanup.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/utils.py
- tests/test_cfyaml_cleanup_migrator.py
- tests/test_migrators.py
- tests/test_v1_yaml/version_cfyaml_cleanup_simple.yaml
- tests/test_v1_yaml/version_cfyaml_cleanup_simple_correct.yaml
Enable `CondaForgeYAMLCleanup` migrator for v1 recipes.  Since it works on `conda-forge.yml` only, it does not require any changes.  So the most of the changes are related to extending the test.
> Enable `CondaForgeYAMLCleanup` migrator for v1 recipes

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/cross_compile.py
- tests/test_cross_compile.py
- tests/test_v1_yaml/cross_compile/python_recipe_b2h.yaml
- tests/test_v1_yaml/cross_compile/python_recipe_b2h_bhskip.yaml
- tests/test_v1_yaml/cross_compile/python_recipe_b2h_bhskip_correct.yaml
- tests/test_v1_yaml/cross_compile/python_recipe_b2h_buildok.yaml
- tests/test_v1_yaml/cross_compile/python_recipe_b2h_buildok_correct.yaml
- tests/test_v1_yaml/cross_compile/python_recipe_b2h_correct.yaml
Add support for v1 recipes in `Build2HostMigrator`, and extend the relevant tests. I've also replaced the explicit schema version check with a `super()` call.
From the list on #3642
> Support recipe v1 in Build2HostMigrator

- conda_forge_tick/migrators/cross_compile.py
- tests/test_cross_compile.py
Enable support for v1 recipes in `CrossCompilationForARMAndPower` minimigrator and add a test for it.
Part of #3642
> Enable recipe v1 for `CrossCompilationForARMAndPower` and add a test

- tests/test_cross_compile.py
- tests/test_yaml/cross_compile/config_recipe.yaml
- tests/test_yaml/cross_compile/config_recipe_correct.yaml
- tests/test_yaml/cross_compile/config_recipe_correct_cmake.yaml
- tests/test_yaml/cross_compile/config_recipe_correct_make_check.yaml
This PR should fix some of the flaky readline cross-compile tests.
> fix: change url in readline recipe tests to a stable url

- .github/workflows/release.yml
- autotick-bot/compute_next_version.py
Somehow the release workflow got out of order, as reported in #3864.
this PR fixes that by properly computing the maximum version tag instead of using the most recent tag.
Closes #3864
> fix: find the last version tag as the max to fix a race condition

- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/__init__.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/nvtools.py
- tests/mock_nvtools_migrator_feedstock/conda-forge.yml
- tests/mock_nvtools_migrator_feedstock/recipe/build.sh
- tests/mock_nvtools_migrator_feedstock/recipe/meta.yaml
- tests/mock_nvtools_migrator_feedstock_ref/conda-forge.yml
- tests/mock_nvtools_migrator_feedstock_ref/recipe/build.sh
- tests/mock_nvtools_migrator_feedstock_ref/recipe/meta.yaml
- tests/test_migrator_nvtools.py
This PR is ready for us to fix some initialization issue in this migrator class. I will push changes to the test suite to catch this bug too.
Reverts regro/cf-scripts#3882
> NEW: Migrate NVIDIA redist feedstocks to use cf-nvidia-tools AGAIN

- conda_forge_tick/migrators/nvtools.py
Tweaking the NVIDIA Tools migrator to fix formatting in the commit message and to add title, commit message, and branch name.
> DOC: Fixup nvtools migration message

- Dockerfile
Currently, I cannot execute some (any?) commands in the Docker container on my local machine (MacOS). Reason is that the `conda` user does not have sufficient permissions for the `/opt/autotick-bot` directory which contains the code of the bot.
**Before:**
```text
$ docker run --rm --net host conda-forge-tick:test conda-forge-tick-container parse-feedstock 
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Traceback (most recent call last):
File "/opt/conda/envs/cf-scripts/bin/conda-forge-tick-container", line 5, in <module>
from conda_forge_tick.container_cli import cli
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1138, in …
```
> fix(dockerfile): chown code directory for conda user

- Dockerfile
- conda_forge_tick/container_cli.py
- conda_forge_tick/feedstock_parser.py
- tests/conftest.py
- tests/test_make_graph.py
- tests/test_migrators.py
- tests/test_recipe_yaml_parsing.py
- tests/test_staticlib.py
```
A function’s touch should leave no trace,
No hidden change, no state misplaced.
Let inputs stay as first they came,
Pure and true—untouched, the same.
```
This PR removes side effects from the `load_feedstock_local` and `populate_feedstock_attributes` functions.
Instead of modifying the `sub_graph` parameter, we create a new dictionary in the function body and return that one.
Rationale: As of now, `try_load_feedstock` **is flawed if run without containers**.
https://github.com/regro/cf-scripts/blob/160c08d1e846272182b5d27a4e640d1b2fce6137/conda_forge_tick/make_graph.py#L100-L115
This is because in no-container mode, the return value `data` of `load_feedstock` is identical to `attrs` which is cleared a few lines after. Hence, we always return a LazyJSON object which is empty besides …
> fix: remove side effects from feedstock loading

- conda_forge_tick/migrators/recipe_v1.py
- tests/test_v1_yaml/version_pytorch.yaml
- tests/test_v1_yaml/version_pytorch_correct.yaml
Modify the v1 recipe condition combiner not to merge non-adjacent conditions.  While this is not really a problem for dependencies (though it could break original dependency grouping), it did lead to reordering test commands that could lead to breaking the recipe.
The algorithm aims to be as simple as possible.  It iterates over lists tail-to-head and folds an "if" into the preceding item if it has the same condition.
Fixes #3933
> Do not combine non-adjacent conditions in v1 recipes

- conda_forge_tick/migrators/recipe_v1.py
- tests/test_recipe_v1.py
- tests/test_v1_yaml/version_pytorch_correct.yaml
Extend the v1 recipe condition combiner to detect negations of trivial conditions (`x` vs. `not x`, provided that `x` does not use `and`, `or` or `if` operators).
> Support combining trivial negations in v1 recipes

- autotick-bot/install_bot_code.sh
- conda-lock.yml
- conda_forge_tick/all_feedstocks.py
- conda_forge_tick/auto_tick.py
- conda_forge_tick/contexts.py
- conda_forge_tick/deploy.py
- conda_forge_tick/feedstock_parser.py
- conda_forge_tick/git_utils.py
- conda_forge_tick/import_to_pkg.py
- conda_forge_tick/lazy_json_backends.py
- conda_forge_tick/make_graph.py
- conda_forge_tick/migrators/pip_wheel_dep.py
- conda_forge_tick/pypi_name_mapping.py
- conda_forge_tick/settings.py
- conda_forge_tick/update_deps.py
- conda_forge_tick/update_upstream_versions.py
- environment.yml
- tests/conftest.py
- tests/test_contexts.py
- tests/test_lazy_json_backends.py
- tests/test_settings.py
- tests/test_upstream_versions.py
In #3417, I proposed to introduce a settings module to centralize the configuration of the bot. However, it had 2 flaws:
- It was not proposed in a separate PR.
- It loaded environment variables at import time, which complicates modifying them between CLI invocations.
This separate PR improves upon the old approach by using `pydantic-settings` to manage a global settings object. The values of the settings object are read from environment variables. As an advantage,
- environment variables can be modified, taking effect immediately on their next usage (because they aren't cached)
- the entire settings object can be overridden with another one, which allows type-safe settings modifications (e.g. for testing)
To keep the scope of this PR under control, not all configuration values are moved …
> feat: introduce global settings object

- .gitignore
- conda_forge_tick/update_sources.py
This PR ensures we parse recipes properly as v0/v1 when getting new versions via raw urls.
> fix: ensure we parse as v1 when searching for new versions via raw urls

- conda_forge_tick/container_cli.py
- tests/test_make_migrators.py
The newly added v1 support for `create_migration_yaml_creator` added in #3970 is currently broken because there is an unrelated bug in the `parse_recipe_yaml` container CLI. This PR fixes the issue.
Logs: https://github.com/regro/cf-scripts/actions/runs/14226411844/job/39866904255#step:7:1546
FYI @xhochy
> fix: log_level argument for parse_recipe_yaml is not correct in container cli

- conda_forge_tick/update_sources.py
This increases the default timeout for `wget --spider` calls from 2 seconds to 5 seconds.
Resolves #3977.
> feat: Increase timeout for checking url exists from 2 seconds to 5 seconds

- .pre-commit-config.yaml
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/version.py
After the report from https://github.com/regro/cf-scripts/issues/4018, I realized what happened only later. Sorry for closing that one too early. This should restrict the list to only direct deps.
closes #4018
> fix: only report direct deps in version PR dep versions

- conda_forge_tick/pypi_name_mapping_static.yaml
- https://github.com/symengine/symengine.py is https://anaconda.org/conda-forge/python-symengine on conda
- https://github.com/sagemath/memory_allocator is https://anaconda.org/conda-forge/memory-allocator on conda (`_` > `-`)
> fix: add static overrides for `symengine` and `memory_allocator`

- conda_forge_tick/migrators/cross_compile.py
- tests/test_cross_compile.py
Fixes an issue where the `GuardTestingWinMigrator` would emit:
```cmd
if not %CONDA_BUILD_SKIP_TESTS%==1 (
..
)
```
However, if the variable is not defined this would resolve to:
```cmd
if not ==1 (
..
)
```
which causes a cryptic error. (See https://github.com/conda-forge/freetype-feedstock/pull/61#issuecomment-2835494439)
This PR modifies the migrator such that the following is inserted instead
```cmd
if not "%CONDA_BUILD_SKIP_TESTS%"=="1" (
..
)
```
Which, if `CONDA_BUILD_SKIP_TESTS` is undefined resolves to:
```cmd
if not ""=="1" (
..
)
```
> fix: quote windows testing guard

- .gitattributes
This should result in merge conflicts just taking one file instead of manually trying to merge two lockfiles together.
I use this for pixi.lock as well and it works great.
> Add conda-lock.yml to gitattributes

- conda_forge_tick/cf_tick_schema.json
- conda_forge_tick/config_schema.py
- conda_forge_tick/events/pr_events.py
- conda_forge_tick/update_prs.py
This PR adds a bot option `remake_prs_with_conflicts` that can be set to `False` to optionally turn off remaking PRs with conflicts.
Closes #4300
> feat: optionally turn off remaking dirty PRs

- tests/test_container_tasks.py
Fix a failing test due to #4517
> switch external feedstock in test_container_tasks_provide_source_code_local

- .pre-commit-config.yaml
- conda_forge_tick/feedstock_parser.py
- conda_forge_tick/utils.py
- tests/test_feedstock_parser.py
For fenics-basix, the ordering of the outputs from rattler-build was causing us to grab the wrong version. It is really hard for the bot know which output has the preferred version. This PR adds some heuristics based on feedstock names and how context variables are set. That should help.
> fix: use heuristic to prefer correct versions for feedstocks

- .pre-commit-config.yaml
This PR swaps to a new mirror for the typos pre-commit hook in order to fix a mutable tag warning with the original repo. #4310 downgraded typos to v1 due to this problem. I also ran autoupdate on the other hooks.
> Fix typos warning for mutable reference v1

- conda_forge_tick/auto_tick.py
- conda_forge_tick/cf_tick_schema.json
- conda_forge_tick/config_schema.py
- conda_forge_tick/migrators/version.py
- conda_forge_tick/status_report.py
- conda_forge_tick/update_upstream_versions.py
- conda_forge_tick/version_filters.py
- tests/test_auto_tick.py
- tests/test_upstream_versions.py
- tests/test_version_filters.py
Adds support for ignoring odd minor version updates for odd/even version schemes.
I think we want to ignore them both for checking and storing upstream version changes and for auto tick of the version, but please let me know if there is a different architecture we want.
Closes #1152.
> Add support for ignoring odd minor versions

- .pre-commit-config.yaml
- autotick-bot/compute_next_version.py
- conda_forge_tick/auto_tick.py
- conda_forge_tick/config_schema.py
- conda_forge_tick/depfinder_api.py
- conda_forge_tick/deploy.py
- conda_forge_tick/events/push_events.py
- conda_forge_tick/lazy_json_backends.py
- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/arch.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators_types.py
- conda_forge_tick/recipe_parser/_parser.py
- conda_forge_tick/status_report.py
- mypy.ini
- tests/test_auto_tick.py
- tests/test_container_tasks.py
This will ultimately be the way we enable mypy for all files in this repo: Step by step. This PR enables mypy for all top-level modules and tests starting with a letter from a to e.
> chore: enforce mypy for all files starting with a letter from a-e

- conda_forge_tick/auto_tick.py
- conda_forge_tick/make_graph.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/models/pr_info.py
- conda_forge_tick/models/version_pr_info.py
Per #4749, this PR adds the timestamp of the last solver attempt to the bot metadata and uses exp backoff to retry PRs. I have updated the pydantic model and added hooks into all of the schema handling. Some of the schema handling sections are likely not needed since this data was never recorded in the old bot model. However, it is easier to treat things uniformly. 
We should actually remove the schema migration handling code at some point and bake in the new schemas, but not today.
> feat: record timestamp of last PR attempt and use exp backoff

- README.md
- conda_forge_tick/auto_tick.py
- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators/noarch_python_min.py
- conda_forge_tick/migrators/nvtools.py
- conda_forge_tick/migrators/staticlib.py
After we moved to exponential backoff, we no longer need this parameter for the migrators. It was used to determine the migrator's share of time. So now we parameterize this directly.
> feat: remove max_solver_attempts and refactor to parameterize migrator shares directly

- conda_forge_tick/update_sources.py
- conda_forge_tick/update_upstream_versions.py
- tests/test_update_sources.py
- tests/test_upstream_versions.py
This PR cleans up some cruft in source version fetching, adds a few type hints, and accounts for excludes when fetching versions.
> fix: clean up cruft in source version fetching and include excludes

- .github/workflows/tests-reusable.yml
- conda_forge_tick/migrators/core.py
- conda_forge_tick/models/pr_info.py
- conda_forge_tick/utils.py
- tests/test_yaml/depfinder.json
This PR removes the keys section from the pr_info json blob. 
These steps need to be done in the order below in order to merge this PR:
> fix: remove extra keys section from pr_info

- conda_forge_tick/auto_tick.py
- conda_forge_tick/make_migrators.py
- conda_forge_tick/migrators/core.py
- conda_forge_tick/migrators/migration_yaml.py
- conda_forge_tick/migrators/staticlib.py
- conda_forge_tick/status_report.py
- conda_forge_tick/utils.py
- tests/test_migrator_to_json.py
This PR 
- centralizes the migrator naming code
- makes the Version migrator on-the-fly so it is more up to date
> feat: make version migrator on-the-fly and use consistent names
