regro/cf-scripts

03-auto_tick.xsh

print traceback on non github errors in an attempt to figure out what is

---

03-auto_tick.xsh

for cran packages replace _ with -

---

00.sh
01.sh
02.sh
03-auto_tick.xsh
03.sh
setup.sh

This would allow us to change most of the behaviors of the travis workers by PRing into this repo. Currently one must PR into the workers, which is a pain for standardization.
PRs to the workers will need to go in after this goes in.

WIP: build travis shell scripts for more flexibility

---

03-auto_tick.xsh

~Do you install the python library before running this script?~
Also any thoughts about converting this to a pure python script?

Use conda_forge_tick.utils.parsed_meta_yaml

---

conda_forge_tick/make_graph.py
conda_forge_tick/update_upstream_versions.py

Catch exceptions and don't stop running

---

03-auto_tick.xsh

This PR has an improved (?) PR message. 
Closes #104 
@CJ-Wright for viz

DOC improved PR message

---

00.xsh
01.xsh
02.xsh
03.xsh
configure_workers.xsh
setup.sh
travis_template.yml

``.travis.yml`` files via jinja
Attn: @scopatz

reorg travis, move to xonsh based scripting, and template

---

03-auto_tick.xsh

Closes #136 
Attn:
@scopatz @justcalamari @ocefpaf
Please feel free to wordsmith/change

add rever info

---

03-auto_tick.xsh

Update jinja var for build if exists

---

conda_forge_tick/make_graph.py
conda_forge_tick/update_upstream_versions.py

WIP: Add nodes to the graph even if there is a problem

---

03-auto_tick.xsh
setup.sh

also use latest conda (since 4.3 doesn't have conda.models.version?)

If run completes put bad False

---

03-auto_tick.xsh

fixed rerender logic and cleaned up code

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh

force rerender for compiler

---

conda_forge_tick/migrators.xsh
tests/test_migrators.py

Fix rerender

---

conda_forge_tick/auto_tick.xsh

PR_json is a list of tuples and exception bad should happen to the

---

conda_forge_tick/__init__.py
conda_forge_tick/all_feedstocks.py
conda_forge_tick/auto_tick.xsh
conda_forge_tick/cli.py
conda_forge_tick/make_graph.py
conda_forge_tick/migrators.xsh
conda_forge_tick/path_lengths.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
find_cycles.py
migrate_to_hash.py
pred_test.py
run_tests.py
setup.py
tests/test_migrators.py
tests/test_path_lengths.py
top_dependencies.py

Remove bad and upstream_bad files plus some stylistic changes

---

conda_forge_tick/update_upstream_versions.py

fix for tbb

---

03.xsh

Add diagnostics for why we are failing out on files.

have 03 report space usage at end of run

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/path_lengths.py

Update in topological order

---

conda_forge_tick/make_graph.py
conda_forge_tick/migrators.xsh
tests/test_migrators.py

Check for gcc and bump build number in compiler migration and track host requirements

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh

start noarch and have migrator based pr limits, also force rerender

---

conda_forge_tick/make_graph.py
conda_forge_tick/update_upstream_versions.py

@mariusvniekerk I took some inspiration from libcflib's use of futures to try to speed up upstream tracking.

use futures to speed up upstream (maybe)

---

conda_forge_tick/make_graph.py

Temporary fix since many packages are breaking make_graph.

Filter None from req in make_graph

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh
tests/test_migrators.py

run update-cb3 on noarch if no host in requirements

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/git_utils.xsh
conda_forge_tick/make_graph.py

This will allow us to know which prs have been merged / closed, allowing
us to track the progess of certain migrations easier.

Refresh for PRed key

---

conda_forge_tick/git_utils.xsh
conda_forge_tick/make_graph.py

Attn: @justcalamari @mariusvniekerk

Fix pr_json

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh
tests/test_migrators.py

Check if conda dep in noarch filter

---

conda_forge_tick/make_graph.py
conda_forge_tick/migrators.xsh
conda_forge_tick/utils.py
tests/test_migrators.py

Remove pinning migrator

---

conda_forge_tick/migrators.xsh
tests/test_migrators.py

better pin filter

---

conda_forge_tick/auto_tick.xsh

This reverts commit a1e26378484cf1860d42670fb58e297b554b918e.

Revert "stop bot"

---

conda_forge_tick/migrators.xsh

add more things for compiler check

---

conda_forge_tick/migrators.xsh

Attrs:
@isuruf
@mariusvniekerk

don't run if 3 PRs for that feedstock are open

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/make_graph.py
conda_forge_tick/migrators.xsh
requirements/run

This simplifies a bunch of really annoying syntax and allows us to get
the correct PRed_json every time

use frozendict for migrator_uid.

---

conda_forge_tick/utils.py
tests/test_utils.py

lazy json so we can store all the json elsewhere but still interface

---

conda_forge_tick/git_utils.xsh
conda_forge_tick/make_graph.py
conda_forge_tick/migrators.xsh

if `bot-rerun` label close and remove from PRed_json and PRed

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh

run rebuild migrations in number of decendents order

---

conda_forge_tick/make_graph.py

randomize github requests

---

.travis.yml
conda_forge_tick/auto_tick.xsh
conda_forge_tick/test_status.py

Add build and run to requirements again?

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh

This properly sorts by the number of decendents.
This took 5 mins to write, don't worry I'm still studying.

use total graph for measuring decendents

---

conda_forge_tick/migrators.xsh

This allows us to easily control the behavior of build_number bumping

Update bump_build_number to have a class defined callback.

---

conda_forge_tick/migrators.xsh

Remove old legacy call

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh

This should be enough metadata for any fancy ui?

WIP Add additional metadata to the migrator status dictionaries

---

conda_forge_tick/git_utils.xsh

This might fix the metis problem #386

use ``git merge upstream master --theirs`` to try to deal with conflicts

---

conda_forge_tick/git_utils.xsh

Maybe this fixes the metis problem? (May be a bit overkill, though).
@scopatz
@jakirkham

hard reset to upstream

---

conda_forge_tick/git_utils.xsh

It seems we can't reset onto a url so we add the upstream remote

add remote

---

conda_forge_tick/migrators.xsh
tests/test_migrators.py

cc @bgruening, @jdblischak, @johanneskoester, @daler, @cbrueffer

Noarch generic for r recipes

---

conda_forge_tick/migrators.xsh
tests/test_migrators.py

Remove the skip win32 line

---

conda_forge_tick/auto_tick.xsh

Revert "Stop rebuilds until some r packages are rebuilt"

---

conda_forge_tick/auto_tick.xsh

remove archived from status

---

README.md

Add instructions for setting up local test environment.

---

conda_forge_tick/migrators.xsh

Closes #418 
closes https://github.com/conda-forge/tbb-feedstock/issues/29

fix issue for self cycles

---

conda_forge_tick/migrators.xsh

no more 1000 build numbers for version bumps

---

conda_forge_tick/update_upstream_versions.py

This fixes a long standing issue when checking if there are newer version of r packages

urls can be lists

---

conda_forge_tick/git_utils.xsh

This fixes a bug from #466 which doesn't trigger because the PRs are already
closed, causing it to not trip the if statement.

now branches are removed if they are closed and old

---

conda_forge_tick/git_utils.xsh

Sometimes it can delete active PRs if a PR re-uses a branch

don't delete branches which are too old

---

conda_forge_tick/migrators.xsh

This fixes issues like those in https://circleci.com/gh/regro/circle_worker/6281
This does NOT fix the underlying issue, but prevents it from wreaking havoc.

Fixed issue where a single bad version could break the whole bot

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/make_graph.py
conda_forge_tick/migrators.xsh
conda_forge_tick/utils.py
tests/test_utils.py

fix migrator uid use and use internal dump/load rather than json

---

conda_forge_tick/auto_tick.xsh

Pending freetype pin see: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/215

refactor rebuild creation and create function for freetype

---

conda_forge_tick/auto_tick.xsh

Please merge https://github.com/regro/cf-scripts/pull/492 first.

Proj4 migrator

---

conda_forge_tick/auto_tick.xsh

See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/218

Add migrator for lz4-c 1.8.3 pin

---

conda_forge_tick/auto_tick.xsh

Follow up on https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/220
Ping @minrk

zeromq migration

---

conda_forge_tick/auto_tick.xsh

migrate pyqt to 5.9.2

---

conda_forge_tick/auto_tick.xsh

Pinning update: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/232

Add migrator for zstd 1.4.0

---

conda_forge_tick/auto_tick.xsh

Follow up on https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/233

migrate to hdf5 1.10.5

---

conda_forge_tick/auto_tick.xsh

xref https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/236
xref: https://github.com/conda-forge/cairo-feedstock/pull/48

Migrate Pixman 0.38

---

conda_forge_tick/migrators.xsh

I'll also have a look at fixing the dependencies that pop up along the way.

Add pyarrow to aarch64 rebuild

---

conda_forge_tick/auto_tick.xsh

new pinning: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/241

Add migrator for libprotobuf 3.8

---

conda_forge_tick/auto_tick.xsh

Handle manually PRed migrators

---

conda_forge_tick/auto_tick.xsh

Merge only after https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/242

migrate to readline 8

---

conda_forge_tick/auto_tick.xsh

~~Merge after https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/243~~
Ready for review.

migrate to geos 3.7.2

---

conda_forge_tick/auto_tick.xsh

add r-base migrator

---

conda_forge_tick/auto_tick.xsh

This reverts commit 0c0c0b6241a994f73896766f09afd5eeb449f3b3.

Revert "add r-base migrator"

---

conda_forge_tick/auto_tick.xsh

Does what it says. I hope — I haven't worked with this package before.

Start migrating to the Pango 1.42.x series.

---

conda_forge_tick/migrators.xsh

Build failed at https://circleci.com/gh/regro/circle_worker/9188
@mariusvniekerk, when migration failed, will the bot try again when this PR is merged?

Fix opening meta.yaml

---

conda_forge_tick/auto_tick.xsh

Hi,
could we have 25 builds over the weekend? I guess could finish the migration then quickly.
Thanks,
Bjoern

can we have 25 over the weekend?

---

conda_forge_tick/auto_tick.xsh

We have migrated 1600 packages in the last day and are mostly done.
If someone can merge this in 3-4h that would be phenomenal.

slow down the R migration

---

conda_forge_tick/auto_tick.xsh

Both issued all the PRs and the ones failing seems to be abandoned.

end graphviz and icu migrations

---

conda_forge_tick/migrators.xsh

Needed in https://github.com/conda-forge/twisted-feedstock/pull/10

add bcrypt

---

conda_forge_tick/auto_tick.xsh

end libgdal and start gdal

---

conda_forge_tick/auto_tick.xsh

All the PRs were issued, no awaiting parents.

end gdal migration

---

conda_forge_tick/update_upstream_versions.py

fixes break from https://github.com/conda-forge/staged-recipes/pull/9162

---

conda_forge_tick/auto_tick.xsh

Another successful migration comes to an end. How did we manage these before the bot? Thanks @CJ-Wright for making this happen!

end proj migration

---

conda_forge_tick/utils.py

ENH: sort link output so output is consistent

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/make_graph.py
conda_forge_tick/migrators.xsh
conda_forge_tick/test_status.py
scripts/migrate_to_unify_pred.py

Unify PRed and PRed_json

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/make_graph.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
scripts/migrate_to_bot_rerun.py
scripts/migrate_to_lzjson.py

This will put the feedstock data into their own files
making it easier to read/write to them via third party tools.
Note that this needs a migration of our existing graph into this structure.

Use lazyjson payload for feedstock info

---

conda_forge_tick/update_upstream_versions.py

Fixes https://github.com/regro/cf-scripts/issues/322
Fixes https://github.com/regro/cf-scripts/issues/476

Remove false positives with RawURL

---

conda_forge_tick/auto_tick.xsh

Store the actual url we failed on along with the error code

Better handling for urlerrors

---

conda_forge_tick/make_graph.py

log success

---

conda_forge_tick/make_graph.py

have consistant hash type

---

conda_forge_tick/migrators.xsh

Don't merge unless you can support/fix. Although review would be great!

fix bad comparisons, which looked at the PR objects which are unique

---

conda_forge_tick/migrators.xsh

Add a few more packages to arch migrator:
protobuf,
cvxpy,
gevent,
gunicorn,
sympy,
tqdm

Add protobuf,cvxpy,gevent,gunicorn,sympy,tqdm to migrator

---

conda_forge_tick/auto_tick.xsh

Closes https://github.com/regro/cf-scripts/issues/624
Noarch packages don't have ABI incompatibilities since they don't link so they
never need to be in a rebuild. This removes noarch pythons from our python rebuild.
Also support excluding things from the rebuild, in the case of python
the c compilers

support exclusions and don't migrate noarch packages

---

conda_forge_tick/update_upstream_versions.py

Reverts regro/cf-scripts#630
Due to fall over caused by this with dask 
https://circleci.com/gh/regro/circle_worker/11126

Revert "Get CRAN upstream versions directly from CRAN instead of librariesIO"

---

conda_forge_tick/migrators.xsh
conda_forge_tick/status_report.py
conda_forge_tick/utils.py
tests/test_migrators.py

This would update licenses where possible

initial pass at license bot

---

conda_forge_tick/migrators.xsh
conda_forge_tick/utils.py

Closes https://github.com/regro/cf-scripts/issues/642

use official render and config to get jinja vars in

---

docs/migrators.rst

more migration docs

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh

go slow for the first 10 PRs, which should give us time to stop any issues, then go much faster to distribute to the community

---

conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh

fix license to use broken out list and add pip and license to pinning migrations

---

conda_forge_tick/migrators.xsh
conda_forge_tick/status_report.py

This should cut down on some of our git thrashing.
@regro/auto-tick

better sorting for the status

---

.travis.yml
conda_forge_tick/make_graph.py

handle multi output recipes better by linking them back to the parent feedstock

---

conda_forge_tick/update_upstream_versions.py

First iteration of auto tick bot that supports ROSDistro.

add rosdistro to auto tick bot

---

conda_forge_tick/migrators.xsh

Let's add some NLP packages to the migrator.

add some NLP packages to aarch64/ppc64le migrator

---

conda_forge_tick/migrators.xsh

if .ci_support doesn't exist make it

---

conda_forge_tick/auto_tick.xsh

This way we combine run and build the rebuild picking if strong run exports
CC @isuruf

handle strong run_exports

---

conda_forge_tick/status_report.py

This way when people ask where they can help we can point to this list

make unmaintained name friendlier

---

conda_forge_tick/migrators.xsh

add piggy back migrators to migration yaml migrator

---

conda_forge_tick/git_utils.xsh
conda_forge_tick/make_graph.py
requirements/run

Revert "Batch requests in order to avoid rate limiting failures"

---

conda_forge_tick/auto_tick.xsh

Just watched a series of terminator movies in the plane and decided to give the bot a time off before we have a skynet situation.
PS: Ah, and the py38 migration is broken at the moment.

stop the bot for a while

---

.gitignore
conda_forge_tick/auto_tick.xsh
conda_forge_tick/migrators.xsh
conda_forge_tick/utils.py
tests/test_migrators.py

Revert "Lets try this again!"

---

conda_forge_tick/auto_tick.xsh

end qt migration

---

conda_forge_tick/migrators.xsh

Needed for testing a formula (boost-histogram)

Add pytest benchmark

---

conda_forge_tick/migrators.xsh

As suggested in https://github.com/conda-forge/iminuit-feedstock/pull/23#issuecomment-553522810
cc @CJ-Wright

Update PR description for ArchRebuild

---

conda_forge_tick/git_utils.xsh

@regro/auto-tick please review and merge! This bug has caused no PRs to be issued for 3 days and has potentially corrupted the graph database.

remove pull_request from push_repo signature

---

conda_forge_tick/git_utils.xsh

This way the logs are a bit nicer

quiet git things

---

conda_forge_tick/git_utils.xsh

Reverts regro/cf-scripts#716
It seems that didn't work, will debug separately and re-issue a PR

Revert "quiet git things"

---

conda_forge_tick/migrators/core.py

This PR updates the PR message for the new web services command. Do not merge until https://github.com/conda-forge/conda-forge-webservices/pull/283 is done.
supersedes #730

DOC update PR message for new web services command

---

conda_forge_tick/migrators/arch.py

This should fix the formatting issue.
@CJ-Wright for viz and CR

BUG format text properly

---

conda_forge_tick/migrators/core.py

This PR adds the `[bot-automerge]` slug to PR titles for version bumps.
@CJ-Wright for code review
Closes #752

ENH add bot-automerge slug

---

conda_forge_tick/migrators/core.py

xref: https://github.com/conda-forge/pyhamcrest-feedstock/pull/9 (make certain to rerun that one)

add extra partition for spaces

---

conda_forge_tick/make_graph.py
conda_forge_tick/migrators/arch.py
conda_forge_tick/migrators/core.py

include the bot key from the conda-forge.yml

---

planning/distributed_bot.md

This PR has some notes for planning. 
cc @CJ-Wright

DOC notes for planning

---

conda_forge_tick/make_graph.py

@regro/auto-tick I think this ws the thing causing the issue once merged I'll repair the db

fix the bot rerun, since the update function doesn't handle this

---

docs/github_actions_infrastructure.rst
docs/index.rst

This PR adds documentation for the basic design of the actions service and how to control it.

DOC added docs for actions

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/arch.py

We were missing some packages
@regro/auto-tick

Fix the arm migration

---

.travis.yml
conda_forge_tick/auto_tick.py
conda_forge_tick/make_graph.py
conda_forge_tick/migrators/arch.py

This needs work, but is ready for a look over

strong exports support (and fix gdal/outputs)

---

.gitignore
.travis.yml
conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/pip_check.py
requirements/run
setup.cfg
tests/test_migrators.py
tests/test_pip_check_migrator.py
tests/test_yaml/version_pipcheck_outputs.yaml
tests/test_yaml/version_pipcheck_outputs_correct.yaml
tests/test_yaml/version_pipcheck_selector.yaml
tests/test_yaml/version_pipcheck_selector_correct.yaml
tests/test_yaml/version_pipcheck_selector_partial.yaml
tests/test_yaml/version_pipcheck_selector_partial_correct.yaml
tests/test_yaml/version_pipcheck_simple.yaml
tests/test_yaml/version_pipcheck_simple_correct.yaml

I have started on the pip check migration.
To do:
closes #771 
cc @xhochy @isuruf @jakirkham @CJ-Wright @marcelotrevisani

ENH pip check migration

---

conda_forge_tick/migrators/pip_check.py

BUG let PRs use a little more space

---

conda_forge_tick/auto_tick.py

This PR fixes and reenables the matplotlib base migration

BUG fix matplotlib-base migration again

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/core.py
conda_forge_tick/status_report.py
tests/test_matplotlib_base.py
tests/test_migrators.py

This PR adds the replacement migrators to the status report.

ENH add replacement migrator to status report

---

conda_forge_tick/migrators/matplotlib_base.py

Some of our yum files don't have a new line at the end

BUG make sure to respect newlines

---

conda_forge_tick/update_upstream_versions.py

This PR checks for upstream extensions and puts in a change that should let us migrate openssh.
Closes #777 
Closes #766

ENH check for upstream extensions, fix openssh

---

conda_forge_tick/update_upstream_versions.py

Revert "ENH check for upstream extensions, fix openssh"

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/core.py
conda_forge_tick/migrators/matplotlib_base.py

I accidentally changed the MPL migration uid which is causing bugs in reporting etc. This PR fixes that.
Closes #811

BUG fix change in mpl uid

---

conda_forge_tick/migrators/matplotlib_base.py

BUG use new graph attrs for MPL

---

conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
requirements/run

ENH try loky for upstream versions

---

conda_forge_tick/update_upstream_versions.py

This PR excludes more dev versions.

BUG exclude more dev vers

---

requirements/run

DEP downgrade distributed

---

conda_forge_tick/make_graph.py
conda_forge_tick/update_upstream_versions.py
requirements/run

This PR moves the graph building to threads to try and make it actually work.

PROD more stable config

---

conda_forge_tick/auto_tick.py
conda_forge_tick/status_report.py

Trying out stuff mentioned in https://github.com/regro/cf-scripts/pull/774#issuecomment-579807694

[WIP] Try graphviz packmode

---

.gitignore
conda_forge_tick/make_graph.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
tests/test_upstream_versions.py

Reverts regro/cf-scripts#819
man this one is a pain

ENH fix openssh versions

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/version.py

Some flake8 cleanups, fewer PRs per run, random version order updates
closes #822

ENH make fewer PRs, randomize version update order, flake8

---

conda_forge_tick/update_upstream_versions.py

DEP remove bad total of versions

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/version.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/url_transforms.py
tests/test_url_transforms.py
tests/test_version_migrator.py
tests/test_yaml/version_githuburl.yaml
tests/test_yaml/version_githuburl_correct.yaml
tests/test_yaml/version_pypiurl.yaml
tests/test_yaml/version_pypiurl_correct.yaml

Added some new code for url transforms that can be used everywhere.
closes #827 
closes #815 
To Do

ENH add url transform generators

---

conda_forge_tick/migrators/version.py
tests/test_version_migrator.py
tests/test_yaml/version_giturl.yaml
tests/test_yaml/version_giturl_correct.yaml

BUG error on git url

---

conda_forge_tick/migrators/version.py
tests/test_version_migrator.py
tests/test_yaml/version_cranmirror.yaml
tests/test_yaml/version_cranmirror_correct.yaml

BUG make sure to add cran_mirror to jinja2 if needed

---

conda_forge_tick/recipe_parser/_parser.py
tests/test_recipe_parser.py

This PR fixes some jinja2 parsing for certain requirements strings. It turns out the jinja2 parser in ruamel.yaml already has a fix for this we just need to be aware of it.
cc @isuruf @tkelman

BUG fix jinja2 parsing for req

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/extra_jinj2a_keys_cleanup.py
tests/test_extra_jinja2_keys_migrator.py
tests/test_yaml/version_extra_jinja2_keys.yaml
tests/test_yaml/version_extra_jinja2_keys_correct.yaml

Closes #847 
I kept going back and forth with how to do this (regular expressions, for loop looking at all keys at the same time, etc) and settled on this approach. I'm not 100% happy with it, but it works. I ended up spending too much time just trying to figure out how things work and thought it'd be better to get feedback before going any further. Let me know if you don't want this many jinja variables removed or if you want more tests.
CC @beckermr

Add mini-migrator to fix extra jinja2 variables

---

docs/index.rst
docs/migrators.rst
docs/version_migrator.rst

This PR has notes/docs for the version migrator.

DOC new docs on vers migration

---

conda_forge_tick/auto_tick.py

Tidy up #854 and always exclude some feedstocks

---

conda_forge_tick/auto_tick.py

Fixes the migrator which is broken.

BUG need to pop the key

---

conda_forge_tick/make_graph.py

This should fix issues where the graph has retained edges that no longer hold.
CC
@isuruf
@beckermr

drop edges before creating the edges from scratch

---

conda_forge_tick/migrators/core.py

BUG check each dep instead of nodes

---

conda_forge_tick/auto_tick.py

ENH lower PR limit

---

conda_forge_tick/auto_tick.py

ENH one pr limit

---

.travis.yml
conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/migration_yaml.py
conda_forge_tick/migrators/version.py
conda_forge_tick/utils.py
tests/test_migration_yaml_migration.py

This PR has code from @CJ-Wright's one but finishes a few extra odds and ends.
closes #861 
closes #858 
closes #665

ENH pinning migrator 

---

conda_forge_tick/migrators/arch.py
conda_forge_tick/migrators/core.py
tests/test_migration_yaml_migration.py

Another fix for aarch and pypy

BUG fix aarch again

---

conda_forge_tick/git_utils.py
conda_forge_tick/make_graph.py
conda_forge_tick/utils.py

Trying to make things a little better.

PROD make the update slower to avoid github api abuse

---

conda_forge_tick/auto_tick.py

We are hitting time limits. This change gives each migrator an equal amount of time.

ENH better control flow

---

conda_forge_tick/auto_tick.py

BUG weight by nodes

---

conda_forge_tick/auto_tick.py
conda_forge_tick/utils.py

I am trying to get more info here.

ENH better logging

---

conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/core.py
conda_forge_tick/migrators/use_pip.py
tests/test_use_pip.py
tests/test_yaml/version_usepip_selector.yaml
tests/test_yaml/version_usepip_selector_correct.yaml
tests/test_yaml/version_usepip_simple.yaml
tests/test_yaml/version_usepip_simple_correct.yaml

This PR makes sure that the pip mini-migrator keeps selectors and adds tests.
closes #886

BUG keep selectors w/ pip mini-migrator

---

requirements/run

requirements:run :same config removed

---

conda_forge_tick/migrators/core.py

This will fix the root migration

BUG if dep is self that is ok

---

conda_forge_tick/migrators/core.py

BUG check for None

---

conda_forge_tick/migrators/version.py
conda_forge_tick/recipe_parser/_parser.py
tests/test_recipe_parser.py
tests/test_version_migrator.py
tests/test_yaml/version_jinja2expr.yaml
tests/test_yaml/version_jinja2expr_correct.yaml

This PR enables simple jinja2 expressions. It solves an issue we have somewhere.

ENH enable jinja2 expressions

---

conda_forge_tick/recipe_parser/_parser.py
tests/test_recipe_parser.py

This fixes some issues w/ boto and awscli

BUG make sure to handle tuples

---

conda_forge_tick/utils.py

PROD make dump less noisy

---

conda_forge_tick/auto_tick.py

BUG use the same branch name

---

conda_forge_tick/auto_tick.py

Well this worked, but API validation failed?

REF try shorter hash

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/core.py

This needs a fix to the graph (namely the PRs "issued" against the pinning)

use the correct directionality for the graph and then use the graph only for pinning

---

conda_forge_tick/migrators/migration_yaml.py

better PR title and body for close outs

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/version.py

this should make sure recipes with yaml read errors are marked as tried.

BUG put attempts before yaml errors

---

conda_forge_tick/update_upstream_versions.py

BUG check all urls in lists

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/version.py
conda_forge_tick/status_report.py
conda_forge_tick/test_status.py

ENH make a version status report

---

conda_forge_tick/migrators/version.py
tests/test_migrators.py
tests/test_version_migrator.py

ENH added more details for the version errors

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/core.py

WIP: fix the migration graph handling

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/migration_yaml.py
tests/test_migration_yaml_migration.py

include impact of proposed migration

---

conda_forge_tick/status_report.py

closes https://github.com/regro/cf-scripts/issues/732

auto_tick.py: added feedstock url for missing PRs

---

conda_forge_tick/migrators/migration_yaml.py

ENH added automerge option

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/jinja2_vars_cleanup.py
conda_forge_tick/url_transforms.py
tests/test_jinja2_vars_cleanup.py
tests/test_url_transforms.py

This PR adds a mini-migrator to cleanup jinja2 variables.
cc @isuruf @ocefpaf @regro/auto-tick

ENH jinja2 cleanup

---

.coveragerc
conda_forge_tick/auto_tick.py
conda_forge_tick/hashing.py
conda_forge_tick/mamba_solver.py
conda_forge_tick/migrators/arch.py
conda_forge_tick/migrators/core.py
conda_forge_tick/migrators/migration_yaml.py
conda_forge_tick/migrators/version.py
requirements/run
tests/test_feedstock/.ci_support/linux_aarch64_python3.6.____73_pypy.yaml
tests/test_feedstock/.ci_support/linux_aarch64_python3.6.____cpython.yaml
tests/test_feedstock/.ci_support/linux_aarch64_python3.7.____cpython.yaml
tests/test_feedstock/.ci_support/linux_aarch64_python3.8.____cpython.yaml
tests/test_feedstock/.ci_support/linux_ppc64le_python3.6.____73_pypy.yaml
tests/test_feedstock/.ci_support/linux_ppc64le_python3.6.____cpython.yaml
tests/test_feedstock/.ci_support/linux_ppc64le_python3.7.____cpython.yaml
tests/test_feedstock/.ci_support/linux_ppc64le_python3.8.____cpython.yaml
tests/test_feedstock/.ci_support/linux_python3.6.____73_pypy.yaml
tests/test_feedstock/.ci_support/linux_python3.6.____cpython.yaml
tests/test_feedstock/.ci_support/linux_python3.7.____cpython.yaml
tests/test_feedstock/.ci_support/linux_python3.8.____cpython.yaml
tests/test_feedstock/.ci_support/osx_python3.6.____73_pypy.yaml
tests/test_feedstock/.ci_support/osx_python3.6.____cpython.yaml
tests/test_feedstock/.ci_support/osx_python3.7.____cpython.yaml
tests/test_feedstock/.ci_support/osx_python3.8.____cpython.yaml
tests/test_feedstock/.ci_support/win_python3.6.____cpython.yaml
tests/test_feedstock/.ci_support/win_python3.7.____cpython.yaml
tests/test_feedstock/.ci_support/win_python3.8.____cpython.yaml
tests/test_mamba_solvable.py

This PR adds checking if each PR is solvable with mamba. It follows on the great work by @CJ-Wright . I am using a bunch of code from @wolfv from that PRs comments. 
cc @scopatz @regro/auto-tick 
To do
closes #961

ENH mamba checking

---

conda_forge_tick/audit.py

Fix the audit system

---

conda_forge_tick/audit.py

use get rather than getitem

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/core.py
conda_forge_tick/migrators/license.py
conda_forge_tick/utils.py
tests/test_license_migrator.py
tests/test_migrators.py

This PR adds special munging for R licenses.

ENH code to munge missing R licenses

---

conda_forge_tick/migrators/license.py

This PR fixes a bug when some attributes are missing.

BUG safe attribute access

---

conda_forge_tick/mamba_solver.py

ENH get channels from configs

---

conda_forge_tick/mamba_solver.py

BUG make sure to use the channels

---

conda_forge_tick/cli.xsh

BUG make sure to try a few times

---

conda_forge_tick/auto_tick.py
conda_forge_tick/cli.xsh
conda_forge_tick/migrators/license.py
conda_forge_tick/migrators/migration_yaml.py
conda_forge_tick/utils.py

This one makes sure we catch rerendering errors. It also unshallows our clone so we can push if something goes wrong.

BUG more R bugs again blarg

---

conda_forge_tick/auto_tick.py

cc @CJ-Wright This should save us some time.

PROD update pinnings if we can

---

conda_forge_tick/update_upstream_versions.py

This one is clogging up the migrator

PROD ignore ca-policy-lcg

---

conda_forge_tick/auto_tick.py
conda_forge_tick/utils.py

PROD turn off unsatisfiable hints

---

conda_forge_tick/auto_tick.py
conda_forge_tick/utils.py

Hopefully this will fix the bot until the rerendering issue can be found.

PROD timeout rerendering

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/core.py

this pr cleans up the hacking from today
cc @isuruf @CJ-Wright

REF clean up from hacks

---

conda_forge_tick/cli.xsh

cc @CJ-Wright @regro/auto-tick

PROD unshallow the clone a bit earlier to see if we can recover

---

conda_forge_tick/status_report.py

remove the pinning node from the status

---

conda_forge_tick/auto_tick.py

allow solvability if feedstock wants it

---

conda_forge_tick/audit.py

independent writers for audits

---

conda_forge_tick/new_update_versions.py

Some bad things were happening on Circle, this is the first attempt to solve some of the bugs. Let's see what happens next.

Bug correction of `new_update_versions`

---

conda_forge_tick/update_upstream_versions.py

Try this to keep things more stable.

PROD use 10 workers

---

conda_forge_tick/make_graph.py
conda_forge_tick/utils.py

Continuing the work from [separate version updates](https://github.com/regro/cf-scripts/issues/842) and [issue](https://github.com/regro/cf-scripts/pull/1049).

make_graph update versions from .json

---

conda_forge_tick/utils.py

As an attempt to solve this [error](https://app.circleci.com/pipelines/github/regro/circle_worker/11498/workflows/35c9982e-4d91-4b0d-9438-2bb7b26859f8/jobs/27967) 
```python
TypeError: update() missing 1 required positional argument: 'data'
```

removed conflicting '.update' method

---

conda_forge_tick/auto_tick.py

This should help with a bunch of issues since we should let the maintainers know if we can't build if we don't have automerge.

Don't check solve without automerge

---

conda_forge_tick/mamba_solver.py

This should fix the kde stack
@scopatz @beckermr

check solvability with build in addition to host and run

---

conda_forge_tick/auto_tick.py

BUG more newlines

---

conda_forge_tick/utils.py

BUG don't swallow stdout on error

---

conda_forge_tick/auto_tick.py
conda_forge_tick/make_graph.py
conda_forge_tick/mamba_solver.py
conda_forge_tick/utils.py

OK @regro/auto-tick! Here is the PR I was chatting about that uses the CI support files and more of conda-build to render the metadata.

REF use the ci support files for rendering

---

conda_forge_tick/auto_tick.py
conda_forge_tick/make_graph.py
conda_forge_tick/mamba_solver.py
conda_forge_tick/utils.py

Revert "REF use the ci support files for rendering"

---

conda_forge_tick/auto_tick.py
conda_forge_tick/make_graph.py
conda_forge_tick/mamba_solver.py
conda_forge_tick/utils.py

REF use the ci support files for rendering again

---

conda_forge_tick/xonsh_utils.py

Also, I guess there was whitespace?

Use the proper import for CommandPipeline

---

conda_forge_tick/git_utils.py
conda_forge_tick/make_graph.py

add arm osx to the render matrix

---

conda_forge_tick/auto_tick.py
conda_forge_tick/git_utils.py
conda_forge_tick/make_graph.py
conda_forge_tick/migrators/arch.py
conda_forge_tick/migrators/core.py

add migrator for osx

---

conda_forge_tick/update_prs.py

Using just the basic config (and the function/process name to help inspections inside the `profile` file).

Profile for update_prs

---

conda_forge_tick/cli.xsh
conda_forge_tick/mappings.py
conda_forge_tick/pypi_name_mapping.py
conda_forge_tick/pypi_name_mapping_static.yaml
setup.py

Starting with pypi -> conda-forge name
See https://github.com/regro/circle_worker/pull/166

Add new class of action that the bot can use to update mappings

---

conda_forge_tick/migrators/version.py

DOC better error message

---

conda_forge_tick/auto_tick.py
conda_forge_tick/make_graph.py
conda_forge_tick/profiler.py
conda_forge_tick/update_prs.py

Implemented using a context manager custom class to enable and disable the profiler. I've tested it locally with a test script not related to the bot, and it worked (checked with python 3.7)

Profiler decorator

---

conda_forge_tick/make_graph.py

Reverts regro/cf-scripts#1146
We can fix the bug here @CJ-Wright

ENH only new versions

---

conda_forge_tick/make_graph.py
conda_forge_tick/update_prs.py

ENH do PRs at random - only half; turn off profiling

---

conda_forge_tick/audit.py
conda_forge_tick/pypi_name_mapping.py

This writes the ordered list of conda-packages determined for an import name to some file

Import name priority mapping

---

conda_forge_tick/make_graph.py
conda_forge_tick/utils.py
requirements/run
tests/test_utils.py

Revert "Make lazyjson lazier to deal with memory usage."

---

conda_forge_tick/cli.xsh

This PR adds logging for git deploy steps so we can see what is going on.

ENH log git deploy steps

---

conda_forge_tick/utils.py

conda build should have this fixed now
closes #1167

BUG remove catch of system exit

---

conda_forge_tick/migrators/migration_yaml.py

This PR computes noarch more precisely.

ENH more precise noarch for python

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/migration_yaml.py

We were plucking nodes too early in the process.

Ensure that we don't break the topology of the graph

---

conda_forge_tick/status_report.py

This should fix the status page. It is choking on the python graph when it writes it. IDK why.

PROD only make status page graphs for small migrations

---

conda_forge_tick/mamba_solver.py

I think this does the trick. I took a bit of hacking to figure out.
cc @mariusvniekerk

BUG do not use pip as python dep

---

conda_forge_tick/auto_tick.py

BUG catch exceptions from failed removal

---

conda_forge_tick/auto_tick.py
conda_forge_tick/mamba_solver.py
conda_forge_tick/status_report.py
tests/test_mamba_solvable.py

This PR attempts to expose mamba solving info if it is there.
cc @xhochy

ENH expose mamba info

---

conda_forge_tick/mamba_solver.py

BUG report more errors

---

conda_forge_tick/auto_tick.py
conda_forge_tick/make_graph.py

This PR special cases pypy for cffi and python.

ENH special case pypy

---

conda_forge_tick/mamba_solver.py

Fixes https://github.com/regro/cf-scripts/issues/1207

Set CONDA_OVERRIDE_GLIBC

---

conda_forge_tick/auto_tick.py

This should fix python, again.

BUG do not exclude top-level nodes, just nodes from the final graph

---

conda_forge_tick/mamba_solver.py

This PR tries to fix solving a different way.

ENH try to fix solving

---

conda_forge_tick/mamba_solver.py

ENH add back glibc override

---

conda_forge_tick/mamba_solver.py
tests/test_mamba_solvable.py

@mariusvniekerk This is a test case for the solving with virtual packages. Once we can make this work, it should unblock things.

TST added test for cupy solving

---

conda_forge_tick/auto_tick.py
conda_forge_tick/status_report.py
conda_forge_tick/utils.py
tests/test_audit.py

This PR adds reporting for bot errors.

ENH report bot errors too

---

conda_forge_tick/mamba_solver.py
tests/test_mamba_solvable.py

Revert "DEP remove explicit pinning stuff since not needed"

---

.travis.yml
conda_forge_tick/mamba_solver.py

This should get us rolling again.

PERF use requests of raw urls to solve disk space issues

---

conda_forge_tick/auto_tick.py
conda_forge_tick/git_utils.py
conda_forge_tick/git_xonsh_utils.xsh
docs/migrators.rst

We can support this via the `abi_migration_branches` key in the `bot` section of the conda-forge.yml.
closes #130

ENH support PRs into branches

---

conda_forge_tick/mamba_solver.py
tests/test_mamba_solvable.py

BUG make sure run exports cache is bounded

---

conda_forge_tick/make_graph.py
conda_forge_tick/migrators/core.py

I am seeing some archived nodes in the graph and they appear to be messing some stuff up.

BUG archived nodes are always migrated

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/core.py

I am starting from @CJ-Wright's branch and then adding the time thing.

ENH close migrations after a time

---

conda_forge_tick/migrators/__init__.py
conda_forge_tick/status_report.py

This PR separates out the long-term migrations.

ENH separate out long-term migrations for the status page

---

conda_forge_tick/status_report.py

This PR adds a few improvements to the status job.

ENH fix a bug and make more performant

---

conda_forge_tick/cli.py

BUG set debug properly

---

conda_forge_tick/mamba_solver.py
requirements/run

This PR tries to set a timeout for the solver and tracks memory usage. The bot still seems to be hanging in this step sometimes.

ENH set timeout and track mem usage

---

conda_forge_tick/auto_tick.py

The depfinder stuff broke the version status updates.

BUG make sure to update the version status too

---

conda_forge_tick/mamba_solver.py

This should help debug the bot.

DEBUG add more logging, shorter timeout

---

.gitignore
conda_forge_tick/mamba_solver.py
tests/test_mamba_solvable.py

This adds struct channel priority and fixes some long solves we've been seeing.
thanks a bunch to the bot group and especially @wolfv for helping!

ENH add strict channel priority

---

conda_forge_tick/mamba_solver.py

Minor changes to logging to improve things.

STY make the logging a bit nicer

---

conda_forge_tick/auto_tick.py

I'm not certain if this is a solution that we want to embrace for the moment, but I thought I'd put it up in case we needed it it

bypass solving for now

---

conda_forge_tick/auto_tick.py
conda_forge_tick/mamba_solver.py
tests/test_mamba_solvable.py

ENH add mamba solver timeout at very high level

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/cross_compile.py
tests/test_cross_compile.py

This PR closes #1268.
cc @isuruf

ENH add build 2 host migrator

---

conda_forge_tick/auto_tick.py

Adding it to the rest. 
cc @CJ-Wright

ENH add build2hist for all migrations

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/cross_compile.py
setup.cfg
tests/test_cross_compile.py

This PR removes inspect linkages in a migrator. 
Closes #1220

ENH remove inspect linkages

---

conda_forge_tick/make_graph.py
conda_forge_tick/update_upstream_versions.py

ENH no longer set bad in version updates

---

conda_forge_tick/auto_tick.py
conda_forge_tick/contexts.py

This catches an error with exceptions raised when getting API request limits.

BUG robustly get api request remaining

---

.github/workflows/pre-commit.yml
.github/workflows/tests.yml

Github is deprecating stuff in a few days.

ENH update workflows

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/arch.py
conda_forge_tick/migrators/core.py
conda_forge_tick/utils.py

This should let the bot issue PRs.

BUG add branch to muid

---

conda_forge_tick/auto_tick.py
conda_forge_tick/contexts.py
conda_forge_tick/migrators/core.py
conda_forge_tick/migrators/version.py

This should be the last bug for branch PRs. 🤞

BUG consider branches when filtering

---

conda_forge_tick/auto_tick.py
conda_forge_tick/contexts.py
conda_forge_tick/git_utils.py
conda_forge_tick/migrators/core.py
conda_forge_tick/utils.py

I think this should be the last of the bugs.

BUG checkout properly and do not check solvable for branches

---

conda_forge_tick/git_utils.py

BUG try again on branches

---

conda_forge_tick/auto_tick.py

BUG use sets here too

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/pypi_name_mapping.py

use pkgs not feedstocks

---

conda_forge_tick/git_utils.py
tests/test_git_utils.py

BUG make sure correct pr json blobs that are missing keys

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/migrators_types.pyi
conda_forge_tick/update_sources.py
conda_forge_tick/update_upstream_versions.py
tests/test_upstream_versions.py

This PR adds code to get openssl-like versions.
closes #1223

ENH add openssl-like version update code

---

conda_forge_tick/audit.py

handle bad feedstocks with audit

---

conda_forge_tick/audit.py

I think this will get the latest error. 
cc @CJ-Wright

BUG filter bad nodes some more for audits

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/make_graph.py
conda_forge_tick/utils.py

This PR improves the graph node parsing again, this time getting even closer to conda build. 
closes #1125

ENH improved parsing

---

conda_forge_tick/utils.py
requirements/run

ENH make this silent

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/utils.py

ENH swallow system exits here

---

conda_forge_tick/auto_tick.py

I want to make sure we see these errors right away. 
maybe related to https://github.com/regro/cf-scripts/issues/1324 or at least might help diagnose

DEBUG rerender errors

---

conda_forge_tick/utils.py
tests/pytorch-cpu-feedstock/.ci_support/linux_64_cuda_compiler_version10.2numpy1.19python3.9.____cpython.yaml
tests/pytorch-cpu-feedstock/.ci_support/osx_64_numpy1.16python3.6.____cpython.yaml
tests/pytorch-cpu-feedstock/recipe/conda_build_config.yaml
tests/pytorch-cpu-feedstock/recipe/meta.yaml
tests/test_feedstock_parser.py

This PR adds a test case and fixes the parsing bug where selectors for non-platform variables are not considered.
closes #1327

ENH fix non-platform selector parsing bug

---

conda_forge_tick/migrators/migration_yaml.py

This is a follow-on to clip the graph more.

REF only include host/build for things we build

---

conda_forge_tick/mamba_solver.py

This should close issue #1338. Sorry @isuruf. This was a bug in the bot!
Closes #1338

BUG make sure to add arm64 for arch in solver

---

.github/workflows/tests.yml
conda_forge_tick/update_sources.py
conda_forge_tick/utils.py
tests/test_feedstock_parser.py
tests/test_upstream_versions.py

This fixes a bug where if we reach the 10th version in a series, we never ship it.

ENH let it ship the 10th one if that version is ok

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/duplicate_lines.py
tests/test_duplicate_lines_cleanup_migrator.py
tests/test_yaml/version_duplicate_lines_cleanup.yaml
tests/test_yaml/version_duplicate_lines_cleanup_correct.yaml
tests/test_yaml/version_duplicate_lines_cleanup_skip.yaml
tests/test_yaml/version_duplicate_lines_cleanup_skip_correct.yaml

Some R recipes have duplicate lines that are confusing the bot. This minimigrator cleans them out.

ENH add minimigrator to skip duplicate lines

---

conda_forge_tick/migrators/version.py
conda_forge_tick/recipe_parser/_parser.py
tests/test_recipe_parser.py
tests/test_version_migrator.py
tests/test_yaml/version_boost.yaml
tests/test_yaml/version_boost_correct.yaml
tests/test_yaml/version_boostcpp.yaml
tests/test_yaml/version_boostcpp_correct.yaml
tests/test_yaml/version_icu.yaml
tests/test_yaml/version_icu_correct.yaml
tests/test_yaml/version_libevent.yaml
tests/test_yaml/version_libevent_correct.yaml
tests/test_yaml/version_mumps.yaml
tests/test_yaml/version_mumps_correct.yaml

This PR fixes multiline jinja2 parsing errors for version updates.

ENH fix multiline jinja2

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/version.py
conda_forge_tick/status_report.py

This PR improves version error messages and trys solver errors there a bit more. 
closes #1353 
closes #1344

ENH better version error reporting; try solver errors more

---

conda_forge_tick/migrators/core.py

This PR fixes a wrong attribute for testing for stale migrations
closes #1357

BUG got wrong state for PR in stale calculation

---

conda_forge_tick/auto_tick.py
conda_forge_tick/hashing.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/cos7.py
conda_forge_tick/update_sources.py
tests/test_cos7_config_migrator.py
tests/test_yaml/version_cos7_config_simple.yaml
tests/test_yaml/version_cos7_config_simple_correct.yaml

This PR makes sure that feedstocks with cos7 have the right config so they can be rerendered properly.
closes #1356

ENH make sure cos7 stuff works

---

conda_forge_tick/git_utils.py

REF replace pull with hard reset to upstream

---

conda_forge_tick/migrators/arch.py
conda_forge_tick/migrators/migration_yaml.py

check all noarch for arch migrations

---

conda_forge_tick/utils.py

BUG conda build raises

---

tests/test_recipe_parser.py

This PR adds a test for an odd round trip parsing issue in islpy. 
see https://github.com/conda-forge/islpy-feedstock/pull/21

TST added test for islpy parsing issue

---

conda_forge_tick/auto_tick.py

This should solve the extra cf pinning PRs.
cc @CJ-Wright @isuruf

BUG local var make_rerender_comment not defined

---

conda_forge_tick/migrators/migration_yaml.py

I think this will fix the bot errors.

BUG build can be None

---

conda_forge_tick/auto_tick.py
conda_forge_tick/feedstock_parser.py
conda_forge_tick/mamba_solver.py
tests/r-base-feedstock/.ci_support/osx_arm64_.yaml
tests/r-base-feedstock/recipe/bld-r-base.bat
tests/r-base-feedstock/recipe/build-r-base.sh
tests/r-base-feedstock/recipe/install-cross-activate.sh
tests/r-base-feedstock/recipe/meta.yaml
tests/test_mamba_solvable.py

This PR ignores the build platform result for solver checks when cross-compiling.
closes #1379

ENH ignore build platform for solver checks when cross compiling

---

conda_forge_tick/git_utils.py

ENH ignore draft PRs when deciding on remaking PRs

---

tests/test_mamba_solvable.py

This fixes some tests that went out of date as the ability to do some things was added.

TST fix tests

---

conda_forge_tick/auto_tick.py

This should get the bot running again.

BUG make sure to catch errors in parsing feedstocks

---

conda_forge_tick/mamba_solver.py
requirements/run
tests/r-base-feedstock/recipe/meta.yaml
tests/test_yaml/version_jinja2expr_correct.yaml

Fixes #1393 which was caused by mamba-org/mamba#856.

Fix TypeError in mamba solver

---

conda_forge_tick/update_sources.py
tests/test_mamba_solvable.py
tests/test_yaml/version_boost.yaml
tests/test_yaml/version_boost_correct.yaml
tests/test_yaml/version_boostcpp.yaml
tests/test_yaml/version_boostcpp_correct.yaml

This PR removes url encoding for version strings.

BUG remove url encoding for version strings

---

tests/test_mamba_solvable.py

Fixes the test suite bug found in a previous PR.

TST skip datalab tests for now

---

conda_forge_tick/migrators/migration_yaml.py

I put this in the wrong class. Silly me.

BUG added ordering to wrong migrator

---

conda_forge_tick/migrators/version.py
tests/test_version_migrator.py
tests/test_yaml/version_python.yaml
tests/test_yaml/version_python_correct.yaml

BUG fix python version migrator

---

conda_forge_tick/pypi_name_mapping_static.yaml

add duckdb mapping, duckdb docs: https://duckdb.org/docs/api/python

Add python-duckdb -> duckdb mapping

---

conda_forge_tick/mamba_solver.py

cc @wolfv 
This should fix some bugs.

BUG track upstream channel priority api changes

---

conda_forge_tick/migrators/version.py

This PR skips path sources if other URL sources are there. It needs a test using the conda-standalone feedstock.

BUG skip path sources if other url sources are there

---

conda_forge_tick/make_graph.py

BUG get node properly

---

conda_forge_tick/migrators/migration_yaml.py

This PR adds a logging statement for debugging.

ENH log this one too

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/version.py

This will clean up the logs a bit.

ENH less noise when running

---

conda_forge_tick/all_feedstocks.py
conda_forge_tick/auto_tick.py
conda_forge_tick/contexts.py
conda_forge_tick/git_utils.py

This should fix the API request rate limit we just hit.

ENH pull the repo branches once here

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/migration_yaml.py
conda_forge_tick/recipe_parser/_parser.py
tests/test_recipe_parser.py

This fix makes the parser fail on a weird edge case so the bot does not generate a bad PR. Instead, it will make no PR and report an error.
AFAICT this case is essentially unparseable.

BUG make parser fail on weird edge case

---

conda_forge_tick/migrators/version.py

One more tweak on this to only apply the sorting to nodes where solver checks are turned on for both nodes.

ENH tweak ver order again

---

conda_forge_tick/auto_tick.py

ENH let it go a bit more to retry old things

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/broken_rebuild.py

@isuruf here is the migrator for the broken travis stuff.

ENH add PRs for broken packages

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/broken_rebuild.py
conda_forge_tick/migrators/core.py

This should unblock borken rebuilds.

BUG allow empty commits

---

requirements/test
run_tests.py

This PR runs the tests in parallel.

ENH run tests in parallel

---

conda_forge_tick/migrators/broken_rebuild.py

BUG bump build number for reals

---

tests/test_url_exists.py

Fixing more things in the tests

TST fix up tests

---

conda_forge_tick/auto_tick.py

ENH set memory limit

---

conda_forge_tick/auto_tick.py

ENH take out the garbage

---

conda_forge_tick/auto_tick.py
conda_forge_tick/feedstock_parser.py
conda_forge_tick/migrators/migration_yaml.py

This PR tracks PR attempts and will allow the bot to retry solver errors a few times.

ENH track attempts

---

conda_forge_tick/auto_tick.py

This version is more maintainable.

REF clean this up

---

conda_forge_tick/migrators/migration_yaml.py

This should close #1484. The feedstock is solvable but the bot has moved on since it failed too much.

ENH make solver attempts configurable

---

conda_forge_tick/mamba_solver.py
tests/test_mamba_solvable.py

Trying to make the solver check tests pass.

REF fixing up some solver stuff

---

conda_forge_tick/all_feedstocks.py
conda_forge_tick/make_graph.py

This should help fix some weird bot errors and stuck PRs.
closes #1487

ENH propagate archived

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/mpi_pin_run_as_build.py
tests/test_mpi_pin_run_as_build_cleanup_migrator.py
tests/test_yaml/version_cfyaml_cleanup_simple.yaml
tests/test_yaml/version_mprab_cleanup_simple.yaml
tests/test_yaml/version_mprab_cleanup_simple_correct.yaml

This one removes the old pin_run_as_build stuff for MPI.

ENH minimigrator to fix up mpi stuff

---

conda_forge_tick/mamba_solver.py
requirements/run

This PR moves to the newest mamba APIs

ENH move to new mamba APIs

---

conda_forge_tick/migrators/version.py

BUG hints were off due to typo

---

.gitignore
conda_forge_tick/feedstock_parser.py
conda_forge_tick/migrators/version.py
conda_forge_tick/update_deps.py
conda_forge_tick/utils.py
tests/test_update_deps.py

This PR fixes a few bugs and makes a few changes:
1. The bot no longer hangs on some conda-build calls. IDK why that was happening but w/e.
2. The grayskull updates only work on the run section now.
3. The grayskull updates skip python requirements.
4. The grayskull updates use the right version. (It was using the old one.)
I added a test that all of this works.

BUG fix bot hanging w/ conda build and some recipe update stuff

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/dep_updates.py
conda_forge_tick/migrators/version.py
conda_forge_tick/update_deps.py
tests/test_update_deps.py

This PR fixes an issue where the dep updates happened in the pr_body step instead of as a minimigrator as they should have been.

BUG move dep updates to a minimigrator

---

conda_forge_tick/migrators/migration_yaml.py

check that all migrators are waited for

---

conda_forge_tick/auto_tick.py

Down weight big migrators with small #s of allowed PRs

ENH account for PR limit in time

---

conda_forge_tick/audit.py

This PR is trying to fix a problem pulling json that happens every so often.

ENH try import a few times

---

conda_forge_tick/audit.py

BUG guard more imports

---

tests/test_version_migrator.py
tests/test_yaml/version_dbt.yaml
tests/test_yaml/version_dbt_correct.yaml

This PR adds a test for a missed version PR.

TST added test for dbt

---

conda_forge_tick/migrators/version.py

The bot is choking on ansible for w/e reason. I cannot debug it in depfinder so I am going to simply skip it by default for now.
See https://github.com/regro/autotick-bot/actions/runs/3240333750/jobs/5310831496 and https://github.com/regro/autotick-bot/actions/runs/3239562526/jobs/5309092975 for example error logs.

ENH add reject list for dep updates

---

conda_forge_tick/recipe_parser/_parser.py

Fixes the issue which is currently preventing `numpy`/`scipy` from being updated:
```python
In [1]: from conda_forge_tick.recipe_parser._parser import CondaMetaYAML
...: !curl -L 'https://raw.githubusercontent.com/conda-forge/scipy-feedstock/main/recipe/meta.yaml' > test.yaml
...: meta_yaml = open("test.yaml").read()
...: cmeta = CondaMetaYAML(meta_yaml)
...: context = cmeta.jinja2_vars
...: cmeta.eval_jinja2_exprs(context)
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  7882  100  7882    0     0   140k      0 --:--:-- --:--:-- --:--:--  148k
---------------------------------------------------------------------------
UndefinedError                            Traceback (most recent call last)
Cell In [1], line …
```

Remove recursively undefined variables in eval_jinja2_exprs

---

conda_forge_tick/status_report.py

BUG make sure to always add a status

---

conda_forge_tick/mamba_solver.py

Our noarch platform recipes need all of the options.

BUG add all platform virtual packages

---

conda_forge_tick/migrators/arch.py

BUG fix handling of dicts for arch migrator

---

requirements/run

See discussion in https://github.com/conda-forge/status/issues/134

try if pinning to older distributed unblocks autotick-bot

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/utils.py

BUG fix bugs in feedstock parsing

---

conda_forge_tick/url_transforms.py
requirements/run
tests/test_url_transforms.py

This one tries a fix for pypi urls. 
Closes #1592

ENH try pypi host name subs

---

conda_forge_tick/url_transforms.py
tests/test_url_transforms.py
tests/test_version_migrator.py
tests/test_yaml/version_dash_extensions.yaml
tests/test_yaml/version_dash_extensions_correct.yaml

This PR adds more url transforms.

ENH support more url transoforms

---

conda_forge_tick/url_transforms.py
tests/test_update_deps.py
tests/test_url_transforms.py

Add another one for pypi to help some recipes.

ENH more url transforms

---

.github/workflows/bot-prs.yml
.github/workflows/bot-update-status-page.yml
conda_forge_tick/update_prs.py

This PR allows the PR updates to be run in parallel.

ENH run PRs in parallel

---

conda_forge_tick/make_graph.py

This PR puts all of the schema migrations in a single spot.

REF do all schema migrations at once

---

conda_forge_tick/migrators/version.py

The dep updates are broken, so I am turning them off by default. 
See
#1617 
#1611

DEP turn off dep updates for now

---

conda_forge_tick/pypi_name_mapping.py

The preferred package for any given import is determined by a score. This score seems to be subject to floating point errors, and this leads to random changes between runs. See the commits [here](https://github.com/regro/cf-graph-countyfair/commits/master/mappings/pypi), noting the exception of [7ccb68a](https://github.com/regro/cf-graph-countyfair/commit/7ccb68ae5c8631935c31b781dc04a714a88f6a34), which is exceptional thanks to https://github.com/conda-forge/de-bundesrat-feedstock/pull/3.
Clipping after 20 binary digits corresponds to a relative error of about 5e-7. In case scores are this close to each other, I figure it's safe for them to be considered equal.

PyPI mapping: round scores to 20 binary digits

---

.pre-commit-config.yaml
conda_forge_tick/pypi_name_mapping.py

This is in preparation for various fixes I have incoming. These changes should not alter functionality.
See commit comments for more details on some individual changes.

Refactor conda_forge_tick.pypi_name_mapping

---

conda_forge_tick/migrators/version.py

This PR adds new bot hooks to skip a random fraction of version updates.
closes #1656

ENH skip a random fraction of versions

---

conda_forge_tick/migrators/core.py

BUG run replacement for test requirements too

---

conda_forge_tick/migrators/version.py
conda_forge_tick/status_report.py
conda_forge_tick/update_upstream_versions.py

This PR adds a feature to ignore certain version updates.

ENH add feature to ignore some versions

---

conda_forge_tick/audit.py
conda_forge_tick/pypi_name_mapping.py

BUG scipy always reports scipy

---

conda_forge_tick/auto_tick.py
conda_forge_tick/git_utils.py
conda_forge_tick/status_report.py
conda_forge_tick/update_prs.py

This PR removes data from closed PRs to save space. We keep the number and the state.

ENH remove data from closed PRs

---

conda_forge_tick/auto_tick.py

This code was buggy. Not sure why but this works.

BUG clean up PRs works now

---

conda_forge_tick/auto_tick.py

we can be a bit more thorough here...

REF clean more up

---

conda_forge_tick/status_report.py

This PR cleans out old status files.

ENH remove old status files

---

conda_forge_tick/status_report.py

This PR sorts the status json blobs for easier diffs.

REF sort the json blobs for better diffs

---

conda_forge_tick/auto_tick.py

This should fix https://github.com/regro/cf-graph-countyfair/pull/2

BUG filter ignored versions

---

conda_forge_tick/utils.py

This creates noise updates to the metadata.

ENH remove tmp paths from node metadata

---

conda_forge_tick/make_graph.py

I changed the nodes to exclude the temp paths but now github is rejecting the big diffs. We'll do 10% at random for a while to ensure things get slowly updated.

BUG update a random fraction for a while so github accepts the diffs

---

conda_forge_tick/auto_tick.py
conda_forge_tick/executors.py
conda_forge_tick/git_utils.py
conda_forge_tick/make_graph.py
conda_forge_tick/migrators/arch.py
conda_forge_tick/migrators/conda_forge_yaml_cleanup.py
conda_forge_tick/migrators/cos7.py
conda_forge_tick/migrators/cross_compile.py
conda_forge_tick/migrators/disabled/legacy.py
conda_forge_tick/migrators/duplicate_lines.py
conda_forge_tick/migrators/extra_jinj2a_keys_cleanup.py
conda_forge_tick/migrators/jinja2_vars_cleanup.py
conda_forge_tick/migrators/license.py
conda_forge_tick/migrators/migration_yaml.py
conda_forge_tick/migrators/mpi_pin_run_as_build.py
conda_forge_tick/migrators/pip_check.py
conda_forge_tick/migrators/pip_wheel_dep.py
conda_forge_tick/migrators/use_pip.py
conda_forge_tick/migrators/version.py
conda_forge_tick/os_utils.py
conda_forge_tick/update_deps.py
conda_forge_tick/update_prs.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
tests/test_migration_yaml_migration.py
tests/test_migrators.py
tests/test_security.py

This PR puts some functions into new modules to help avoid circular imports in the future.

REF new modules to help avoid circular imports in the future

---

conda_forge_tick/utils.py

I think this version is better.

REF remove $ for vars

---

conda_forge_tick/all_feedstocks.py
conda_forge_tick/auto_tick.py
conda_forge_tick/make_graph.py
conda_forge_tick/status_report.py
conda_forge_tick/update_prs.py
conda_forge_tick/update_upstream_versions.py

ENH make sure all tqdm stuff is fixed width

---

tests/test_update_deps.py

Trying to make the tests pass again.

TST fix tests for praw

---

.github/workflows/bot-bot.yml
.github/workflows/bot-cache.yml
.github/workflows/bot-make-graph.yml
.github/workflows/bot-prs.yml
.github/workflows/bot-versions.yml

PROD start uploading to mongodb

---

environment.yml
tests/test_executors.py

This PR adds a test of the executors.

TST add test of executors

---

conda_forge_tick/deploy.py
conda_forge_tick/lazy_json_backends.py
conda_forge_tick/make_graph.py
tests/test_lazy_json_backends.py

This PR refactors the lazy json override to be a global context manager that can optionally sync the data after.

REF use global backend context with automatic sync

---

conda_forge_tick/migrators/migration_yaml.py

xref: https://github.com/regro/cf-scripts/pull/1713#pullrequestreview-1480427527

Add `\n\n` after `<hr>`

---

conda_forge_tick/auto_tick.py

closes #1716 
closes #1718 
closes #1717

BUG skip archived feedstocks

---

conda_forge_tick/update_prs.py

BUG skip archived nodes and nodes without pr_info in refresh

---

.github/workflows/tests.yml
autotick-bot/bump_bot_team.py
do_types.py
environment.yml

PROD see if we can update the env now

---

conda_forge_tick/auto_tick.py

Making sure this is in the logs so we can check it.

PROD print more info on solver checks

---

conda_forge_tick/migrators/version.py
conda_forge_tick/status_report.py

This should make the status page more responsive.

ENH make sure to look at latest data for version status

---

conda_forge_tick/migrators/version.py

Grayskull throws system exists so need to catch them.

BUG catch system exit

---

conda_forge_tick/migrators/dep_updates.py

BUG catch sys.exit from dep update

---

conda_forge_tick/migrators/version.py

BUG why did I mess this up so much

---

.github/workflows/tests.yml
requirements-dev.txt
tests/test_version_migrator.py
tests/test_yaml/version_mpich.yaml
tests/test_yaml/version_mpich_correct.yaml
tests/test_yaml/version_mpichv0.yaml
tests/test_yaml/version_mpichv0_correct.yaml

closes https://github.com/regro/cf-scripts/issues/1784

TST add mpich test case

---

conda_forge_tick/recipe_parser/_parser.py
tests/test_license_migrator.py
tests/test_recipe_parser.py
tests/test_update_deps.py
tests/test_yaml/version_boostcpp_correct.yaml
tests/test_yaml/version_buildbumpmpi_correct.yaml
tests/test_yaml/version_ccacheerr_correct.yaml
tests/test_yaml/version_extra_jinja2_keys_correct.yaml
tests/test_yaml/version_faiss-split_correct.yaml
tests/test_yaml/version_icu_correct.yaml
tests/test_yaml/version_jinja2nameshasel_correct.yaml
tests/test_yaml/version_jinja2selsha_correct.yaml
tests/test_yaml/version_jinja2sha_correct.yaml
tests/test_yaml/version_pypiurl_correct.yaml
tests/test_yaml/version_python_correct.yaml
tests/test_yaml/version_shaquotes_correct.yaml
tests/test_yaml/version_weird_correct.yaml

BUG fix key-value and strings

---

conda_forge_tick/auto_tick.py

This will make sure they all get some time eventually even if the bot times out.

ENH raqndomly shuffle pinning migrators

---

conda_forge_tick/auto_tick.py
conda_forge_tick/utils.py
tests/test_parse_munged_run_export.py

closes https://github.com/regro/cf-scripts/issues/1560

BUG make sure to strip the build string when making pin migrations

---

conda_forge_tick/auto_tick.py

This PR fixes the libprotobuf pin migration that was weird.
cc @jakirkham @h-vetinari

BUG fix gen for pinning migrations

---

conda_forge_tick/pypi_name_mapping_static.yaml

See https://github.com/conda-forge/ray-packages-feedstock/blob/main/recipe/meta.yaml

Add ray to pypi_name_mapping_static.yaml

---

conda_forge_tick/status_report.py

This should fix our current status page outage.

BUG make sure state is in PR status otherwise error

---

conda_forge_tick/auto_tick.py

DEP remove Cos7Config migrator

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/core.py
conda_forge_tick/migrators/dep_updates.py
conda_forge_tick/migrators/migration_yaml.py
conda_forge_tick/migrators/pip_wheel_dep.py
conda_forge_tick/migrators/version.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
tests/test_utils.py

This PR accounts for possibly None items in the cf yaml.

BUG account for possible None keys in cf yaml bot section

---

conda_forge_tick/status_report.py

Closes https://github.com/regro/cf-scripts/issues/2121

fix SVG logo URL

---

conda_forge_tick/all_feedstocks.py
conda_forge_tick/auto_tick.py
conda_forge_tick/cli.py
conda_forge_tick/cli_context.py
conda_forge_tick/deploy.py
conda_forge_tick/lazy_json_backends.py
conda_forge_tick/lazy_json_backups.py
conda_forge_tick/make_graph.py
conda_forge_tick/mappings.py
conda_forge_tick/pypi_name_mapping.py
conda_forge_tick/status_report.py
conda_forge_tick/update_prs.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
environment.yml
tests/test_cli.py

This PR introduces [click](https://github.com/pallets/click) as a new entry point for the CLI. This allows us to make the CLI more consistent, and is a good basis for extending the CLI for local debugging use as described in #2123.

Use Click for CLI Handling

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/pip_wheel_dep.py
conda_forge_tick/os_utils.py
conda_forge_tick/status_report.py
conda_forge_tick/utils.py
mypy.ini

I was on a train ride with not a lot of internet, so I fixed some of the low hanging fruit.
The majority of typing errors depend on missing attributes of `AttrsTypedDict`. @ytausch is going to look into documenting and adding them in 1-2 weeks. So I did not tackle them.

Some typing fixes

---

.github/workflows/bot-make-graph.yml
.github/workflows/bot-versions.yml
conda_forge_tick/env_management.py
conda_forge_tick/make_graph.py
conda_forge_tick/update_prs.py

REF sanitize envs a bit more

---

conda_forge_tick/auto_tick.py
conda_forge_tick/git_utils.py
conda_forge_tick/migrators/migration_yaml.py
tests/test_git_utils.py

This fixes some minor issues that were discovered while working on #2239. There are also discussions about some of the things.

Small Fixes

---

conda_forge_tick/migrators/arch.py

This PR does some minor refactoring and unifying of the arch migration graphs to ensure consistency. Specific items include:
- always plucking to ensure the connectivity is preserved
- filtering out virtual packages
- removing some code duplication where it made sense

ENH refactor and unify arch migration graphs

---

.github/workflows/relock.yml
conda-lock.yml
environment.yml

ENH relock on the regs

---

autotick-bot/relock_me.py

Adding docs on relocking. @jaimergp

DOC add docs for relocking

---

conda_forge_tick/migrators/dep_updates.py
conda_forge_tick/migrators/version.py
conda_forge_tick/update_deps.py
tests/test_update_deps.py

Support `disabled` bot inspection

---

conda_forge_tick/update_deps.py
tests/test_update_deps.py

remove support for bot.inspection = false

---

conda_forge_tick/migrators/cstdlib.py
tests/test_stdlib.py
tests/test_yaml/stdlib_arrow_after_meta.yaml
tests/test_yaml/stdlib_htcondor_after_meta.yaml
tests/test_yaml/stdlib_htcondor_before_meta.yaml
tests/test_yaml/stdlib_pagmo_after_meta.yaml
tests/test_yaml/stdlib_pagmo_before_meta.yaml

Addresses #2322 and the discussion in https://github.com/conda-forge/htcondor-feedstock/pull/225

Fix more corner cases in stdlib migrator

---

conda_forge_tick/migrators/cstdlib.py
tests/test_stdlib.py
tests/test_yaml/stdlib_fenics_after_meta.yaml
tests/test_yaml/stdlib_fenics_before_meta.yaml
tests/test_yaml/stdlib_mgis_after_meta.yaml
tests/test_yaml/stdlib_mgis_before_meta.yaml

See new stuff found in #2328 while reviewing PRs that got opened

More stdlib fixes

---

.github/workflows/docker.yml
.github/workflows/tests.yml
Dockerfile
conda_forge_tick/update_upstream_versions.py
docker/entrypoint
docker/entrypoint_source
docker/install_cmds
docker/run_bot_task.py
tests/test_container_tasks.py
tests/test_upstream_versions.py

REF use custom entrypoint and separate build workflow

---

conda-lock.yml
environment.yml

In the process of working on docker, I found that `wget` is currently being pulled from the GHA environment. I am adding it to conda here for consistency with the docker images.

BUG missing wget dep

---

conda_forge_tick/utils.py

This PR fixes up some quirks in parsing recipes.
- We now catch the numpy warning from conda-build.
- We now raise errors in parsing for both the sophisticated parser and the simpler one.

ENH catch numpy warnings and raise error for parsing failure

---

.github/workflows/tests.yml

BUG put back tests

---

README.md
conda_forge_tick/update_sources.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
docker/run_bot_task.py
tests/test_container_tasks.py
tests/test_upstream_versions.py

This PR has
- better error handling for getting latest versions
- logging for getting latest versions
- reentrant container use
- documentation for env vars added and used

ENH reentrant container use in version update, better error handling

---

conda_forge_tick/feedstock_parser.py

This PR turns on loading feedstocks in a container.

PROD load feedstocks in a container too

---

.github/workflows/tests.yml

This PR fixes the code coverage uploads.

BUG fix code cov uploads

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/migrators/arch.py
conda_forge_tick/update_sources.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
docker/run_bot_task.py
pyproject.toml
tests/test_container_tasks.py
tests/test_upstream_versions.py

This PR addresses CR comments from @jaimergp for docker.

ENH address CR for docker

---

conda_forge_tick/recipe_parser/_parser.py
conda_forge_tick/update_recipe/version.py
conda_forge_tick/utils.py
tests/test_security.py

ENH use sandboxed envs for jinja2

---

conda_forge_tick/make_graph.py
conda_forge_tick/update_upstream_versions.py

BUG make sure to not launch processes we do not need

---

conda_forge_tick/make_graph.py

BUG make sure to actually update the nodes

---

conda_forge_tick/make_graph.py

Trying to get it to run for a while.

BUG slow the bot down for now

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/update_upstream_versions.py
conda_forge_tick/utils.py
docker/run_bot_task.py

This fixes things to pass the json blob via stdin.

ENH pass json blob via stdin

---

.github/workflows/bot-make-graph.yml
.github/workflows/bot-versions.yml
conda_forge_tick/cli.py
conda_forge_tick/lazy_json_backends.py
conda_forge_tick/make_graph.py
tests/test_cli.py

This PR refactors the graph making so the jobs can run in parallel.

ENH refactor graph making so it can run in parallel

---

conda_forge_tick/lazy_json_backends.py
tests/test_lazy_json_backends.py

BUG i really messed up yep

---

README.md
conda_forge_tick/deploy.py

This PR changes the deploy to be done in batches and skips trying to push to branch since that never works and takes hours.

ENH better deploy in batches

---

conda_forge_tick/deploy.py
conda_forge_tick/make_graph.py

I am trying to make this a bit more efficient.

REF do as many run exports as we can up front

---

conda_forge_tick/utils.py

We should always mask all things here.

BUG always mask all tokens

---

conda_forge_tick/deploy.py
conda_forge_tick/make_graph.py

I am turning this all the way back up now that things are stable.

PROD increase graph making a bit

---

conda_forge_tick/make_graph.py

This PR tries to fix a race condition in setting the pr_info key that killed a recent job.

BUG fix race condition for pr_info key

---

tests/conftest.py
tests/test_container_tasks.py

This PR ensures the test suite runs without docker. 
closes #2460

BUG make sure to skip container tests if docker not there

---

autotick-bot/relock_me.py
conda_forge_tick/auto_tick.py
conda_forge_tick/deploy.py
conda_forge_tick/git_utils.py
conda_forge_tick/lazy_json_backends.py
conda_forge_tick/lazy_json_backups.py
conda_forge_tick/migrators/license.py
conda_forge_tick/migrators/migration_yaml.py
conda_forge_tick/migrators/mpi_pin_run_as_build.py
conda_forge_tick/os_utils.py
conda_forge_tick/status_report.py
tests/test_lazy_json_backups.py
tests/test_migration_yaml_migration.py

REF do not use shell for subprocesses

---

.github/workflows/tests.yml
Dockerfile
conda_forge_tick/auto_tick.py
conda_forge_tick/os_utils.py
conda_forge_tick/rerender_feedstock.py
conda_forge_tick/utils.py
docker/run_bot_task.py
tests/test_container_tasks.py
tests/test_rerender_feedstock.py
tests/test_upstream_versions.py

This PR adds rerenders in a container.

ENH rerender in containers

---

autotick-bot/install_bot_code.sh
conda_forge_tick/auto_tick.py
conda_forge_tick/rerender_feedstock.py
docker/run_bot_task.py

This PR fixes a bug where the new rerendering code does not work due to a path issue.

BUG fix rerendering in bot code by using abs path

---

.github/workflows/bot-bot.yml
README.md
conda_forge_tick/auto_tick.py

The bot failed after it didn't time out properly. IDK why it didn't, but hopefully these changes will help us fix it and add some logging.

BUG try to fix timeout

---

.github/workflows/tests.yml
conda_forge_tick/os_utils.py
conda_forge_tick/rerender_feedstock.py
docker/run_bot_task.py
tests/test_container_tasks.py
tests/test_rerender_feedstock.py

I am trying to fix failing rerenders due to permissions errors on tmpdir cleanup.

BUG fix failing rerender permissions

---

conda_forge_tick/migrators/cross_compile.py
conda_forge_tick/migrators/license.py
conda_forge_tick/provide_source_code.py
conda_forge_tick/status_report.py
conda_forge_tick/update_deps.py
conda_forge_tick/utils.py
docker/run_bot_task.py
tests/test_container_tasks.py

This changes the code to use a container to provide source code in a tmpdir.

ENH provide source from container

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/git_utils.py
conda_forge_tick/provide_source_code.py
conda_forge_tick/rerender_feedstock.py
conda_forge_tick/utils.py
docker/run_bot_task.py

PROD clean up some cruft in the logs

---

conda_forge_tick/git_utils.py

This PR cleans up more logs and refactors the code a bit.

ENH use non-deprecated api for github

---

.github/workflows/bot-bot.yml
.github/workflows/bot-keepalive.yml

This PR fixes a deadlock in the code.

ENH use a spearate workflow for keepalive

---

Dockerfile
docker/entrypoint

This PR should remove bash warnings in the logs.

REF source conda and remove -il

---

conda_forge_tick/auto_tick.py
conda_forge_tick/feedstock_parser.py

Hopefully this helps ucxs get a pinning PR. 
xref: #2519

BUG get version if not at top level

---

tests/test_container_tasks.py
tests/test_rerender_feedstock.py

This PR tries to make the tests faster.

TST run tests faster

---

conda_forge_tick/auto_tick.py
conda_forge_tick/solver_checks.py
conda_forge_tick/utils.py
docker/run_bot_task.py
tests/test_container_tasks.py
tests/test_rerender_feedstock.py

This PR moves the solver checks to containers.

REF run solver checks in a container

---

.github/dependabot.yml
.github/workflows/bot-bot.yml
.github/workflows/bot-cache.yml
.github/workflows/bot-delete-old-runs.yml
.github/workflows/bot-feedstocks.yml
.github/workflows/bot-keepalive.yml
.github/workflows/bot-make-graph.yml
.github/workflows/bot-prs.yml
.github/workflows/bot-pypi-mapping.yml
.github/workflows/bot-update-status-page.yml
.github/workflows/bot-versions.yml
.github/workflows/docker.yml
.github/workflows/keepalive.yml
.github/workflows/relock.yml
.github/workflows/test-model.yml
.github/workflows/tests.yml

xref https://github.com/conda-forge/infrastructure/pull/1

pin github actions

---

tests/test_container_tasks.py

TST update provide source code test to be more robust

---

.codespellignorelines
tests/test_stdlib.py
tests/test_yaml/stdlib_gz-common_after_meta.yaml
tests/test_yaml/stdlib_gz-common_before_meta.yaml
tests/test_yaml/stdlib_libhdbpp-timescale_after_meta.yaml
tests/test_yaml/stdlib_libhdbpp-timescale_before_meta.yaml
tests/test_yaml/stdlib_rucio-clients_after_meta.yaml
tests/test_yaml/stdlib_rucio-clients_before_meta.yaml

This PR adds failing test cases for slicing recipes into outputs. The hope is that #2543 will make them pass.

TST add failing test cases for slicing recipes

---

conda_forge_tick/migrators/core.py
tests/test_migrator_to_json.py

REF replace spaces with underscores in names

---

conda_forge_tick/auto_tick.py

ENH fold more logs

---

conda_forge_tick/utils.py

This PR will make some debugging a bit nicer I hope.

ENH make fold log lines work without folding too

---

.github/workflows/bot-make-migrators.yml
conda_forge_tick/make_migrators.py

BUG fix name of workflow for making migrators

---

conda_forge_tick/status_report.py

BUG need gx for this function

---

conda_forge_tick/auto_tick.py

This PR converts the main bot job to loading the migrators.

REF load migrators for main bot job

---

tests/test_container_tasks.py

This PR is fixing tests for smithy updates.

TST fix tests for smithy updates

---

conda_forge_tick/auto_tick.py
conda_forge_tick/status_report.py
conda_forge_tick/utils.py

This PR is trying to make the log line folding a bit cleaner. It is not nested in github so, we do not allow nested folds anymore.

PROD clean up log line folding

---

conda_forge_tick/auto_tick.py

Trying again to make the logs group nicely.

REF fix log grouping again

---

autotick-bot/bump_bot_team.py

Switch back to using the triage team for the bot.

REF use the triage team again

---

conda_forge_tick/utils.py

I am bikeshedding the logs at this point.

ENH this will hopefully look better

---

conda_forge_tick/auto_tick.py
conda_forge_tick/utils.py

ENH filter duplicated print lines in log

---

conda_forge_tick/make_migrators.py

ENH make logs a bit nicer for making migrators

---

conda_forge_tick/make_migrators.py
conda_forge_tick/utils.py
tests/test_parse_munged_run_export.py
tests/test_utils.py

Fixing some parsing errors and making this more robust.

BUG fix parsing of run exports for weak/strong/noarch

---

conda_forge_tick/make_migrators.py
conda_forge_tick/migrators/migration_yaml.py

This will make things bit less nutty.

PROD run long-term migrations last

---

conda_forge_tick/make_migrators.py

PROD be a bit more agressive and report

---

conda_forge_tick/auto_tick.py

Trying again due to bad logic bug.

BUG wrong logic again on check solvable

---

conda_forge_tick/auto_tick.py

I want to double check which PRs are being issued so I am adding some info to the logs.

ENH add some info to the logs so we can debug

---

conda_forge_tick/auto_tick.py

I am seeing randomly skipped migrations which I do not understand. This PR adds some logs to debug them.

ENH debug skips

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migration_runner.py
conda_forge_tick/status_report.py
conda_forge_tick/utils.py
tests/test_migration_runner.py

This refactor is in preparation of moving the actual migrators to run in a container.

REF move running migrations to its own function

---

README.md

This PR adds some docs on the structure of the bot's jobs. 
cc @wolfv @jaimergp

DOC added docs on bot jobs

---

conda_forge_tick/migrators/version.py

This PR allows feedstocks to opt out of version updates. 
xref #2642

ENH skip version updates

---

conda_forge_tick/migration_runner.py

BUG make sure to set feedstock_dir on context

---

conda_forge_tick/auto_tick.py
conda_forge_tick/contexts.py
conda_forge_tick/git_utils.py
conda_forge_tick/migration_runner.py
conda_forge_tick/migrators/core.py
conda_forge_tick/migrators/migration_yaml.py
conda_forge_tick/migrators/version.py
conda_forge_tick/status_report.py
tests/test_migration_runner.py
tests/test_migrators.py

This PR removes the package_name attribute.

DEP remove package_name from feedstock context object

---

conda_forge_tick/executors.py
conda_forge_tick/lazy_json_backends.py
tests/test_executors.py

This PR adds a reentrant lock for dask.

ENH add reentrant lock for dask

---

conda_forge_tick/migration_runner.py
conda_forge_tick/migrators/migration_yaml.py
conda_forge_tick/migrators/mpi_pin_run_as_build.py
docker/run_bot_task.py
tests/test_container_tasks.py

This PR moves the running of migrations into containers.

ENH run migrations in containers

---

conda_forge_tick/auto_tick.py
conda_forge_tick/utils.py

PROD print why nodes are skipped

---

conda_forge_tick/models/pr_info.py
conda_forge_tick/models/version_pr_info.py
tests/model/test_validate.py

This PR fixes some logical errors in the pydantic models.

BUG fix some errors in the pydantic models

---

conda_forge_tick/models/common.py
conda_forge_tick/models/pr_info.py
conda_forge_tick/models/version_pr_info.py

This PR is a followup to #2664 following the discussion there.

REF a few pydantic fixes

---

conda_forge_tick/migration_runner.py

This should solve the key errors on migrations.

BUG make sure to dump the dict if LazyJson

---

conda_forge_tick/models/pr_info.py
conda_forge_tick/models/pr_json.py
tests/model/test_validate.py

The pr json blobs can have special structure for PRs we do not make.

BUG fix PR json validation for no PR made

---

README.md

DOC add documentation for the migrations.

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/utils.py

BUG make sure to pass ci support file as last variant

---

conda_forge_tick/migrators/cstdlib.py

Hopefully this fixes #2696 
cc @minrk

BUG make sure to add newline to CBC

---

.github/workflows/test-model.yml

TST report model tests in PRs

---

.github/workflows/test-model.yml
tests/model/test_validate.py

TST fix model tests for passing feedstocks

---

conda_forge_tick/make_migrators.py
conda_forge_tick/migrators/migration_yaml.py
tests/test_migration_yaml_migration.py

Add support for packages to be migrated together

---

conda_forge_tick/make_migrators.py

Fix YAML file location

---

autotick-bot/bump_bot_team.py

REF bump bot team once a day

---

conda_forge_tick/auto_tick.py
conda_forge_tick/utils.py

I am trying to make the status page a bit nicer.

ENH try and format errors a bit better

---

conda_forge_tick/update_sources.py
tests/test_upstream_versions.py

Revert "Revert "Use version prefix from github URL""

---

conda_forge_tick/make_migrators.py

Fix debug message

---

conda_forge_tick/utils.py

BUG fix encode+decode of str for escape chars

---

docker/run_bot_task.py

ENH report at end

---

conda_forge_tick/models/node_attributes.py

fix typos in Pydantic error messages

---

.gitignore
tests/test_migrators.py

While looking into the tests I found a bit of dead code.
I also added pixi stuff to gitignore

chore: Remove dead code in test_migrators

---

conda_forge_tick/make_migrators.py

mpir -> gmp replacement

---

tests/test_migrators.py

As can be seen here: https://github.com/search?q=repo%3Aregro%2Fcf-scripts+prb&type=code

fix: type hint

---

.pre-commit-config.yaml
typos.toml

chore: Move from codespell to typos

---

conda_forge_tick/migration_runner.py
conda_forge_tick/provide_source_code.py
conda_forge_tick/rerender_feedstock.py
conda_forge_tick/solver_checks.py
conda_forge_tick/update_upstream_versions.py

fix: make sure container default is set correctly

---

conda_forge_tick/migrators/r_ucrt.py

Fixes https://github.com/regro/cf-scripts/issues/2847

Remove use of m2-pkg-config

---

conda_forge_tick/migrators/core.py

fix: type hints in `migrators/core.py`

---

tests/test_migrators.py
tests/test_version_migrator.py

Refactor: improve migrator tests

---

conda_forge_tick/utils.py

fix: pass RUN_URL to containers

---

conda_forge_tick/git_utils.py
tests/test_git_utils.py

fix: ensure github backend makes forks correctly

---

.github/workflows/release.yml
.github/workflows/tests.yml
autotick-bot/compute_next_version.py
autotick-bot/release.py
setup.py

feat: automatic releases w/ calver using YYYY.MM.patch

---

.github/pull_request_template.md

doc: update PR template

---

.github/workflows/bot-bot.yml
.github/workflows/bot-cache.yml
.github/workflows/bot-make-graph.yml
.github/workflows/bot-make-migrators.yml
.github/workflows/bot-prs.yml
.github/workflows/bot-pypi-mapping.yml
.github/workflows/bot-update-status-page.yml
.github/workflows/bot-versions.yml
autotick-bot/install_bot_code.sh

Description:
I busted the other jobs by not putting the proper docker tag in the right spot.
Checklist:
Cross-refs, links to issues, etc:
xref: #2894

fix: container tag is busted in pull

---

.github/workflows/bot-bot.yml
.github/workflows/bot-cache.yml
.github/workflows/bot-make-graph.yml
.github/workflows/bot-make-migrators.yml
.github/workflows/bot-prs.yml
.github/workflows/bot-pypi-mapping.yml
.github/workflows/bot-update-status-page.yml
.github/workflows/bot-versions.yml
README.md
conda_forge_tick/utils.py
pyproject.toml
tests/conftest.py

Description:
This PR converts the rest of the jobs to use a tag.
Checklist:
Cross-refs, links to issues, etc:
xref: #2894

feat: convert rest of jobs to use a tag

---

.github/workflows/tests.yml

This PR adds the SHA to the cache to ensure the cache is update as the code changes.

fix: add sha to cache to ensure it gets updated as tests runs

---

conda_forge_tick/utils.py

Fix minor typing problems in utils.py

fix: minor typing problems in utils.py

---

.github/workflows/bot-cache.yml
autotick-bot/install_bot_code.sh
conda_forge_tick/migrators/arch.py

This PR ensures we use a consistent version of the pinnings repo.

feat: move entirely to pinnings package in env

---

.github/workflows/bot-bot.yml
.github/workflows/bot-cache.yml
.github/workflows/bot-feedstocks.yml
.github/workflows/bot-keepalive.yml
.github/workflows/bot-make-graph.yml
.github/workflows/bot-make-migrators.yml
.github/workflows/bot-prs.yml
.github/workflows/bot-pypi-mapping.yml
.github/workflows/bot-update-status-page.yml
.github/workflows/bot-versions.yml
.github/workflows/release.yml
.github/workflows/tests.yml
README.md
autotick-bot/stop_me_if_needed.py

This PR moves the default branch to main.

feat: change default branch from master to main

---

conda_forge_tick/migrators/core.py

This PR fixes an incorrect log message in filtering nodes for migrations.
xref: #2961

fix: log message is wrong

---

conda-lock.yml
environment.yml

This PR updates the env for the new conda package for feedstock ops.

chore: update env for new conda package

---

.github/workflows/tests-reusable.yml

This PR enables artifacts for the lock files.

feat: enable artifacts for lock files

---

.gitignore
conda_forge_tick/container_cli.py
conda_forge_tick/update_recipe/version.py
tests/test_container_tasks.py

This PR adds a containerized version update for a recipe.

feat: add code to update recipe version

---

conda_forge_tick/migrators/r_ucrt.py

replace m2w64-toolchain

---

README.md

This PR adds docs for making developer envs and how the lockfile for production is handled.

doc: add docs on the lockfile and envs

---

.github/workflows/tests-reusable.yml
conda_forge_tick/auto_tick.py
conda_forge_tick/git_utils.py
tests/test_auto_tick.py
tests/test_git_utils.py

This is the next step after #2873 and is intended to be merged after.

(Git-3) Use GitCli to Commit Migrations

---

conda_forge_tick/migrators/r_ucrt.py

Fix filter for ucrt and fix posix

---

conda_forge_tick/migrators/r_ucrt.py

Fix pkg-config

---

environment.yml

This PR updates the requirements for v1 recipes.

chore: update requirements

---

conda_forge_tick/migrators/arch.py

Don't pin help teams

---

.github/workflows/release.yml
autotick-bot/compute_next_version.py

This PR fixes a bug in how we get the most recent tag.

fix: get most recent tag properly

---

environment.yml

This PR ensures we are always using the latest fs ops package.

chore: ensure always using latest fsops

---

.github/workflows/relock.yml

This PR adds the lock file back to this repo.

feat: add relock back to this repo

---

.github/workflows/bot-bot.yml
.github/workflows/bot-cache.yml
.github/workflows/bot-feedstocks.yml
.github/workflows/bot-make-graph.yml
.github/workflows/bot-make-migrators.yml
.github/workflows/bot-prs.yml
.github/workflows/bot-pypi-mapping.yml
.github/workflows/bot-update-status-page.yml
.github/workflows/bot-versions.yml
.github/workflows/release.yml
.github/workflows/test-model.yml
.github/workflows/tests-reusable.yml
.gitignore
README.md
conda-lock.yml

This PR puts the lockfile back here.

feat: put lock file back in this repo

---

conda_forge_tick/pypi_name_mapping.py

I was reading the code and this variable has a weird name.

fix: weird variable name

---

conda_forge_tick/provide_source_code.py
conda_forge_tick/utils.py

This PR tries to directly parse the variants when loading source code instead of adding in stubby ones.

fix: try a different approach for fixing source code loading

---

conda_forge_tick/auto_tick.py
conda_forge_tick/contexts.py
conda_forge_tick/status_report.py

These are some leftover changes from the PR splitting process.

minor fixes

---

conda_forge_tick/auto_tick.py
conda_forge_tick/contexts.py
conda_forge_tick/status_report.py

Revert "minor fixes"

---

conda_forge_tick/update_recipe/version.py
tests/test_version_migrator.py
tests/test_yaml/version_event_stream.yaml
tests/test_yaml/version_event_stream_correct.yaml

This PR better detects local source sections in recipes when updating the version and skips them. 
closes #3095

fix: better detect local source sections

---

.github/workflows/tests-reusable.yml
conda-lock.yml
environment.yml

The tests are out of balance and I cannot figure out why. I am trying this setup to see if it helps.

test: try this setup for more even test distribution

---

conda_forge_tick/url_transforms.py
tests/test_url_transforms.py
tests/test_version_migrator.py
tests/test_yaml/version_21cmfast.yaml
tests/test_yaml/version_21cmfast_correct.yaml
tests/test_yaml/version_dash_extensions_correct.yaml
tests/test_yaml/version_pypiurl_correct.yaml

PyPI now uses lowercase all the time, so let's add that to the url transforms we try.

feat: pypi lowercase transforms

---

conda_forge_tick/recipe_parser/_parser.py
tests/test_recipe_parser.py
tests/test_version_migrator.py
tests/test_yaml/stdlib_libhdbpp-timescale_after_meta.yaml
tests/test_yaml/stdlib_mgis_after_meta.yaml
tests/test_yaml/version_giturl.yaml
tests/test_yaml/version_giturl_correct.yaml
tests/test_yaml/version_pyrsmq.yaml
tests/test_yaml/version_pyrsmq_correct.yaml
tests/test_yaml/version_quart_trio.yaml
tests/test_yaml/version_quart_trio_correct.yaml
tests/test_yaml/version_reproc.yaml
tests/test_yaml/version_reproc_correct.yaml
tests/test_yaml/version_riskfolio_lib.yaml
tests/test_yaml/version_riskfolio_lib_correct.yaml

This PR fixes the recipe parser to properly munge weird jinja2 quoting so it can handle more recipes.
I also added a test of parsing the entire version update result set.

fix: munge weird jinja2 quoting

---

conda_forge_tick/lazy_json_backends.py
conda_forge_tick/utils.py

fix: address more networkx deprecations

---

conda_forge_tick/make_migrators.py

Addresses #3012, at least partially

add PyPIOrgMigrator as piggyback to version migrator

---

conda_forge_tick/migrators/migration_yaml.py
tests/test_migrators.py

This PR properly makes the build section for recipes when it is empty.

fix: ensure build section is filled in for noarch

---

conda_forge_tick/feedstock_parser.py
conda_forge_tick/make_graph.py
conda_forge_tick/status_report.py
tests/test_feedstock_parser.py

The bot was not capturing all parsing errors. This PR fixes that.

fix: capture all parsing errors

---

.github/workflows/bot-events.yml
conda_forge_tick/cli.py
conda_forge_tick/events/__init__.py
conda_forge_tick/events/pr_events.py
conda_forge_tick/git_utils.py

This PR adds a workflow that allows the bot to react to PR events.

feat: react to PR events

---

.github/workflows/bot-events.yml
autotick-bot/install_bot_code.sh
conda_forge_tick/events/pr_events.py

This PR fixes more bugs in event reactions.

fix: only update if not None and fix dry-run logic

---

.github/workflows/bot-events.yml
autotick-bot/install_bot_code.sh
conda_forge_tick/auto_tick.py

fix: dump PR json right away to avoid race condition

---

conda_forge_tick/auto_tick.py

fix: retry commits via api

---

conda_forge_tick/make_graph.py

This PR fixes a bug where nodes were updated when making the graph.

fix: do not update nodes when making graph

---

conda_forge_tick/events/pr_events.py
conda_forge_tick/events/push_events.py
docs/runner_allocation.md

This PR
- updates the docs
- pushes to the `all_feedstocks.json` blob on push updates
- fixes a bug where the tmpdir was not used properly
closes #3271

fix+feat: push to feedstocks and handle tmpdir properly

---

.github/workflows/bot-update-nodes.yml
conda_forge_tick/events/__init__.py
conda_forge_tick/make_graph.py
docs/runner_allocation.md

There are some file syncing issues here and so I am going back to the cron job for now.

fix: parse nodes all the time

---

.github/workflows/bot-update-nodes.yml
conda_forge_tick/cli.py
conda_forge_tick/make_graph.py

feat: enable only schema migrations

---

conda_forge_tick/events/push_events.py
conda_forge_tick/lazy_json_backends.py
conda_forge_tick/make_graph.py
dev/test_lazy_json_github.ipynb
tests/test_lazy_json_backends.py

This PR does the following
- enables recursive pulling and pushing of nodes via github backend and GH API
- removes schema migrations from node push events
- ensures required keys for nodes are always made

fix: more robust responses to node events

---

conda_forge_tick/lazy_json_backends.py

fix: propetly handle exceptions for API push of laxy json

---

conda_forge_tick/make_graph.py

chore: turn down update frequency

---

conda_forge_tick/events/__init__.py

chore: turn push back on

---

conda_forge_tick/lazy_json_backends.py
tests/test_lazy_json_backends.py

fix: do not push if nothing changed

---

autotick-bot/install_bot_code.sh

chore: reduce clone depth to help with disk space

---

conda_forge_tick/deploy.py

Fix: missing local variable for deploy

---

.github/workflows/bot-prs.yml
.github/workflows/bot-update-nodes.yml
.github/workflows/bot-versions.yml
conda_forge_tick/deploy.py
dev/test_lazy_json_github.ipynb
tests/test_deploy.py

fix: try to fix the pull step to commit conflicts properly

---

.github/workflows/bot-migrate-schema.yml
README.md

feat: add job for schema migration

---

conda_forge_tick/make_graph.py
conda_forge_tick/models/node_attributes.py

fix: do not record a timestamp anymore

---

conda_forge_tick/deploy.py

fix: try and resolve pull issues on first pull too

---

conda_forge_tick/utils.py

fix: capture rattler stderr too

---

conda_forge_tick/utils.py

feat: suppress more warnings from conda-build

---

.github/workflows/bot-update-nodes.yml
conda_forge_tick/make_graph.py

fix: try to update even less

---

conda_forge_tick/lazy_json_backends.py

Very rarely a LazyJson blob will show up that refers to one that does not exist. This happens because the state of the data repo is in between. Instead of committing them all at once, which is expensive via the API, we just commit the refs of refs first. That way when we finally get to the ref at the top of the tree, everything it points to already exists.

fix: prevent race conditions by pushing refs of refs for lazy json first

---

.github/workflows/bot-bot.yml
.github/workflows/bot-feedstocks.yml
.github/workflows/bot-make-graph.yml
.github/workflows/bot-make-migrators.yml
.github/workflows/bot-migrate-schema.yml
.github/workflows/bot-prs.yml
.github/workflows/bot-pypi-mapping.yml
.github/workflows/bot-update-nodes.yml
.github/workflows/bot-update-status-page.yml
.github/workflows/relock.yml

We are still running out of disk space on jobs so trying to clean up a GB or so.

fix: try and purge docker image before deploy

---

conda_forge_tick/events/pr_events.py
conda_forge_tick/lazy_json_backends.py
tests/test_lazy_json_backends.py

This PR changes the PR event code to use the GH api for everything to try and avoid out-of-order updates.

fix: use gh api for everything to fix out-of-order updates

---

conda_forge_tick/events/push_events.py

I think this another out-of-order update bug.

fix: have push event only touch top-level items

---

conda_forge_tick/lazy_json_backends.py
conda_forge_tick/make_migrators.py

I am applying this to replacement and the `noarch: python` migration as well.

feat: set adaptive PR limits for major migrators

---

.github/workflows/tests-reusable.yml
.github/workflows/tests.yml
README.md
conda_forge_tick/deploy.py
conda_forge_tick/git_utils.py
conda_forge_tick/lazy_json_backends.py
tests/test_git_utils.py
tests/test_lazy_json_backends.py

This PR tries to deploy files via the GH API when the number is small. It should help avoid deployment errors.

feat: deploy files via GH api

---

conda_forge_tick/deploy.py
conda_forge_tick/git_utils.py
conda_forge_tick/update_prs.py
tests/test_git_utils.py

This change ensures we are deleting files via the GH API when we deploy as well.

fix: make sure to delete files via GH api too

---

conda_forge_tick/auto_tick.py
conda_forge_tick/migrators/broken_rebuild.py
conda_forge_tick/migrators/core.py
conda_forge_tick/migrators/migration_yaml.py

This PR reworks the computation of the time per migrator to penalize for lots of retries. The goal is to increase the fraction of useful work done by the bot on each run. There is an associated fix to better randomize which PRs are tried.

feat: redo migrator shares to penalize for attempts

---

conda_forge_tick/auto_tick.py

feat: try to get the migrator to do more useful work

---

conda_forge_tick/auto_tick.py

fix: need not a list here

---

README.md

docs: explain to use --no-containers for debugging

---

conda_forge_tick/make_graph.py

I am trying to fix some residual errors where the graph is corrupted.

fix: do not raise and make sure to always add required json refs

---

conda_forge_tick/deploy.py

This PR ensures that deployed files via the API are then reflected in the local updated git history.

fix: update git locally

---

conda_forge_tick/auto_tick.py
conda_forge_tick/make_migrators.py

This will have the bot retry old PRs only up to a certain number per run.

feat: set limit on number of attempts

---

conda_forge_tick/cli.py
conda_forge_tick/migrators/cstdlib.py
conda_forge_tick/update_upstream_versions.py

This ensures the version debugging works.

fix: cleanup debug and fix error in getting reqs for outputs as list

---

conda_forge_tick/auto_tick.py

Hopefully this makes some errors easier to diagnose.

fix: propagate container tracebacks

---

conda_forge_tick/migrators/core.py

feat: close pinning PRs faster

---

conda_forge_tick/make_migrators.py

minor fix: don't divide by zero

---

.github/workflows/relock.yml
conda-lock.yml
environment.yml

This PR avoids the latest rattler build until we can debug the test failures more.

prod: avoid latest rattler-build for now

---

conda_forge_tick/make_migrators.py
conda_forge_tick/migrators/__init__.py
conda_forge_tick/migrators/round_trip.py
conda_forge_tick/recipe_parser/__init__.py
conda_forge_tick/recipe_parser/_parser.py
tests/test_round_trip.py

This PR adds a minimigrator that formats recipes via the parsers before we try to work on them. This can help with code bits that expect certain yaml features like indentation.

feat: add yaml roundtrip w/ tests

---

.gitignore
conda_forge_tick/migrators/replacement.py
conda_forge_tick/utils.py
tests/test_migrators.py
tests/test_migrators_v1.py

Enables replacement migrations for v1 and fixes v1 testing bugs.

fix: remove extra v1 testing code and enable replacement migrators

---

tests/test_minireplacement.py
tests/test_v1_yaml/qtqtmain_octave_after_meta.yaml
tests/test_v1_yaml/qtqtmain_octave_before_meta.yaml
tests/test_v1_yaml/qtqtmain_octave_xz_after_meta.yaml
tests/test_yaml/qtqtmain_octave_after_meta.yaml
tests/test_yaml/qtqtmain_octave_before_meta.yaml
tests/test_yaml/qtqtmain_octave_xz_after_meta.yaml

fix: move octave url to something more stable

---

conda_forge_tick/make_migrators.py

Fixing a bug in the nvidia stuff. We should be able to avoid these through a refactor in the future.
closes #3903

fix: ensure making migrators works

---

conda_forge_tick/make_migrators.py

fix: debug more for nvidia stuff

---

conda_forge_tick/migrators/staticlib.py

fix: raise if repodata download fails

---

conda_forge_tick/migrators/recipe_v1.py
tests/test_recipe_v1.py
tests/test_v1_yaml/version_pytorch.yaml
tests/test_v1_yaml/version_pytorch_correct.yaml

Support combining subconditions into superconditions while folding `if` in v1 recipes, e.g.:
```yaml
- if: A
then: FOO
- if: A and B
then: BAR
```
will be combined into:
```yaml
- if: A
then:
- FOO
- if: B
then: BAR
```

Support folding subconditions into superconditions in v1 recipes

---

conda_forge_tick/recipe_parser/_parser.py
tests/test_recipe_parser.py

fix: enable parser to work with jinja2 comments

---

.github/workflows/tests-reusable.yml
tests/test_yaml/version_jinja2expr.yaml
tests/test_yaml/version_jinja2expr_correct.yaml
tests/test_yaml/version_python.yaml
tests/test_yaml/version_python_correct.yaml

This will make the tests pass for CB 25.4.
xref: https://github.com/conda/conda-build/pull/5693

fix: remove float, os.sep from selectors

---

conda_forge_tick/migrators/arch.py

Use migration_support dir for text files

---

.github/workflows/test-integration.yml

feat: add workflow dispatch for integration tests and rename

---

.pre-commit-config.yaml
autotick-bot/bump_bot_team.py

This should make failures a bit easier to manage.

feat: edit existing comment

---

conda_forge_tick/models/pr_info.py
tests/model/test_validate.py

fix: resolve a few json validation errors

---

tests/test_yaml/version_boost_correct.yaml
tests/test_yaml/version_boostcpp_correct.yaml

fix: hash for boost tarball changed

---

conda_forge_tick/migrators/core.py

fix: prioritize failures more using a fixed fraction

---

conda_forge_tick/migrators/core.py

feat: boost big failed PRs even more

---

conda_forge_tick/update_deps.py

I've been evaluating switching the awscli2 feedstock over to rattler-build hoping grayskull might handle some recipe dependency quirks there better.
I'm getting "It was not possible to recover package metadata for awscli," I believe because the github-source codepath from #3199 needs to be ported into the new grayskull-for-v1-recipes code from #4575.
I don't quite know how to test run grayskull locally, and could use some help in coming up with a unit test for this as well.

fix grayskull for v1 recipes with github sources

---

conda_forge_tick/migrators/staticlib.py

Removed extra word
I have done no testing since this should be just a grammar fix
Example PR that has the extra word https://github.com/conda-forge/r-class-feedstock/pull/26#issue-3399097411

Fix grammar in PR message

---

.github/workflows/bot-versions.yml
conda_forge_tick/update_sources.py
conda_forge_tick/update_upstream_versions.py

fix: catch errors and deploy later if needed; set run url

---

conda_forge_tick/update_sources.py
conda_forge_tick/update_upstream_versions.py
tests/test_upstream_versions.py

fix: catch more errors and always return none

---

conda_forge_tick/lazy_json_backends.py

We had some job failures with lots of retries so going to backoff more here.

perf: backoff more on GH API w/ LazyJson

---

conda_forge_tick/migrators/core.py

fix: ensure leaf nodes come before failed nodes not being retried

---

conda_forge_tick/lazy_json_backends.py

perf: try more times on API calls and randomize backoff

---

conda_forge_tick/git_utils.py

feat: use more exp backoff in gh api calls

---

conda_forge_tick/auto_tick.py
conda_forge_tick/make_graph.py

fix: reset pre-pr priority fields when processing rerun labels

---

conda_forge_tick/auto_tick.py
conda_forge_tick/utils.py

fix: get proper migrator name from migration data

---

.github/workflows/release.yml

prod: allow releases on dispatch when bot is stopped

---

conda_forge_tick/auto_tick.py
conda_forge_tick/contexts.py
conda_forge_tick/migrators/migration_yaml.py

This PR does as it says in the title. I also went ahead and formalized the changing of the branch in the feedstock attributes.
closes #4884

feat: include branch title in ABI migration PRs
